### ISSUE TITLE
strategy for server script start/stop/reload

### ISSUE THREAD

**Issue by hugsbrugs** [voryx/Thruway#102]
Hi and thanks for this wonderful lib !

I might suggest adding a link to WampPost from Thruway README since I had to read a lot before finding it :)

I am wondering how I will be able to manage socket server script (start/stop/reload) once in production mode. When I am going to reboot system, restart apache etc, I really would like not to have to manually run socket server script. Also what if script fails, how to restart it automagically ?

Well if some of you could provide informations on how to manage this use case, I would be very grateful ! 

Hugo

**Comment by RafaelKa** [comment]
Hi hugsbrugs,

solution for your problem is supervisord and you can read http://socketo.me/docs/deploy#supervisor

**Comment by hugsbrugs** [comment]
Great ! It Rocks !
