### ISSUE TITLE
Triggering update in websockets app from PHP without long running process

### ISSUE THREAD

**Issue by Braynid** [voryx/Thruway#105]
I'm using [crossbario/crossbar](https://github.com/crossbario/crossbar) along with Thruway as "backend" and JS in the browser as "front-end" for my app.

What I'd like to do is to have the ability to trigger updates in the front-end when some action takes place within the app but there is no long running websockets connection present. For example, I'd like to be able to call an procedure when an API method is called.

I've tried creating a new connection with ->open(FALSE) and then calling ->close() after the processing is done in ->on("open"). But creating a connection like this and then closing doesn't seem like an optimal solution.

I've thought about having a middle element like a message queue but I'd really like to avoid adding another moving part to the system only for this use case.

Would there be any simpler way of triggering an update (calling a procedure, etc.) within the websockets architecture from the PHP app?

Thanks,

**Comment by mbonneau** [comment]
There are a few options.

The first is detailed in this comment here: https://github.com/voryx/Thruway/issues/42#issuecomment-59791963

Which, I agree, is a little ugly.

The other option is to create a [WampPost](https://github.com/voryx/WampPost) client.  This would allow you to publish messages to crossbar and also make RPC calls using typical http calls.

The WampPost option would require you to have a long-running PHP process.

It is possible that crossbar has this same facility built in (I know they have the [pusher service](http://crossbar.io/docs/HTTP-Pusher-Service/) which allows publishing events), but I am not sure about doing RPCs like that.

If you have the option of running the Thruway router, the WampPost client can be added in internally so both start at the same time.

**Comment by mbonneau** [comment]
I should have looked just a little longer - crossbar does have something similar using HTTP: http://crossbar.io/docs/HTTP-Bridge-Services/

**Comment by Braynid** [comment]
Thanks, that was exactly what I needed.

I should have read the docs closer, don't know how I've missed it :/
