### ISSUE TITLE
How to disconnect a PHP client from the router?

### ISSUE THREAD

**Issue by marqu3s** [voryx/Thruway#109]
Hello!

##### SITUATION:
I'm building a calendar application and I'm trying to notify connected clients (browsers) that the next event is about to start.

##### WHAT I ALREADY GOT WORKING:
1 - A PHP router running in the server.
2 - Client's Javascript code using Autobahn (running in browsers) that connects to the router, subscribes and receives the notification.
3 - A PHP client that runs on the server, query the database and if there are any event that needs to be notified to a user, it connects to the router and publish the notification to the specific user.

All of this are working fine. The router must be running as a service (will probably use a supervidord here. Suggestions?) The problem is that the PHP client keeps running forever. I can't find a way to make it stop after publishing the events. I'm thinking in run it in cron like every 5 minutes.

###### ROUTER (PHP) - Runs on server
```php
$router = new Router();
$transportProvider = new RatchetTransportProvider("0.0.0.0", 9090);
$router->addTransportProvider($transportProvider);
$router->start();
```

###### JAVASCRIPT CLIENT - Runs on browsers
```javascript
<script src="https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.jgz"></script>
<script type="text/javascript" language="JavaScript">
    var connection = new autobahn.Connection({
        url: 'ws://<?= $_SERVER['HTTP_HOST'] ?>:9090/',
        realm: 'diretor'
    });
    connection.onopen = function (session) {
        // session is an instance of autobahn.Session
        
        function nextEvent(data) {
            console.log(data) // for simplicity
        }
        
        session.subscribe('diretor.agenda.1', nextEvent);
    };
    connection.open();
</script>
```

###### PHP CLIENT - Runs on server, from cron, in 5 minutes interval
```php
$connection = new Connection([
    "url" => 'ws://127.0.0.1:9090',
    "realm" => 'diretor'
]);

$connection->on('open', function (ClientSession $session) {
    $sql = "SELECT idFunc, title, DATE_FORMAT(start, '%H:%i') as start FROM calendario_evento WHERE start > now() GROUP BY idFunc ORDER BY start";
    $rs = Yii::$app->db->createCommand($sql)->queryAll();
    foreach ($rs as $evt) {
        $session->publish('diretor.agenda.1', [$evt], [], ["acknowledge" => false])
    }

    //$session->close(); // Tried this
    //$session->shutdown(); // this also
    //$session->getLoop()->stop(); // this also (breaks the notification, it's not delivered)
});

$connection->open();
```

**Any ideas on how to make the PHP client run and after the notifications are sent, just quit?
Or maybe another approach for this cron job?**

NOTES:
1 - For simplicity in the example I used a fixed topic but in the application every user will have their own topic for receiving notifications for their events.
2 - Yeah, I'm using Yii 2 so the router and the php client are console applications.

**Comment by mbonneau** [comment]
Modify your client code to (have not run this - but it is the general idea):

```php
$connection = new Connection([
    "url" => 'ws://127.0.0.1:9090',
    "realm" => 'diretor'
]);

$connection->on('open', function (ClientSession $session) use ($connection) { // we are going to need this
    $sql = "SELECT idFunc, title, DATE_FORMAT(start, '%H:%i') as start FROM calendario_evento WHERE start > now() GROUP BY idFunc ORDER BY start";
    $rs = Yii::$app->db->createCommand($sql)->queryAll();
    foreach ($rs as $evt) {
        // set acknowledge to true so we know it sent before shutting down 
        $session->publish('diretor.agenda.1', [$evt], [], ["acknowledge" => true])->then(function () use ($connection) {
            $connection->close(); // shutdown after successful publish
        }, function () use ($session) {
            $connection->close(); // shutdown after unsuccessful publish
        });
    }

    // running this stuff here would most likely kill your connection prior to it being able to publish
    //$session->close(); // Tried this
    //$session->shutdown(); // this also
    //$session->getLoop()->stop(); // this also (breaks the notification, it's not delivered)
});

$connection->open();
```

**Comment by marqu3s** [comment]
That worked! Thank you so much.
But I had to move the ```$connection->close()``` to another place since there can be more than one event beeing published inside the foreach loop.

```php
$connection->on('open', function (ClientSession $session) use ($connection) { // we are going to need this
    $sql = "SELECT idFunc, title, DATE_FORMAT(start, '%H:%i') as start FROM calendario_evento WHERE start > now() GROUP BY idFunc ORDER BY start";
    $rs = Yii::$app->db->createCommand($sql)->queryAll();
    foreach ($rs as $evt) {
        // set acknowledge to true so we know it sent before shutting down 
        $session->publish('diretor.agenda.1', [$evt], [], ["acknowledge" => true])->then(function () use ($connection) {
            //$connection->close(); // shutdown after successful publish - Do it outside foreach
        }, function () use ($session) {
            //$connection->close(); // shutdown after unsuccessful publish - Do it outside foreach
        });
    }

    $connection->close(); // <--- This works!

    // running this stuff here would most likely kill your connection prior to it being able to publish
    //$session->close(); // Tried this
    //$session->shutdown(); // this also
    //$session->getLoop()->stop(); // this also (breaks the notification, it's not delivered)
});
```

It is working now, but do you think the approach is a good one? What would you suggest to improve it?

**Comment by davidwdan** [comment]
Instead of using cron, you might want to look at using a periodic timer and keep the client running.  

You can read more about timers here http://blog.wyrihaximus.net/2015/01/reactphp-timers/

**Comment by marqu3s** [comment]
Thanks @davidwdan.
And what do you guys like to use to keep PHP scripts running (if you need to)?
Besides keeping the router running, if I use a periodic timer I will need to keep the client running too.

**Comment by davidwdan** [comment]
Your best bet would be to use [supervisor](http://supervisord.org/).

**Comment by marqu3s** [comment]
Thank you all for your help!
