### ISSUE TITLE
How to choose debug level

### ISSUE THREAD

**Issue by hugsbrugs** [voryx/Thruway#112]
Hi there and thanks for this amazing socket router !

I'm wandering how I could tell default logger to log only for example error level and above levels messages ?

I've seen this issue (https://github.com/voryx/Thruway/issues/61) about completely disabling logging but looking at Logger class (https://github.com/voryx/Thruway/blob/master/src/Thruway/Logging/Logger.php) I can't find a "set_log_level" like function. Any suggestions and thoughts appreciated !

**Comment by oanhnn** [comment]
Dear @hugsbrugs 
```php
$logger = new \Monolog\Logger('WAMP2');
$logger->pushHandler(new \Monolog\Handler\StreamHandler('path/to/log_file', \Monolog\Logger::WARNING));
\Thruway\Logging\Logger::set($logger);
```
Good luck!

**Comment by mbonneau** [comment]
It is important to note that this solution will introduce blocking code into the router. It may be a better option to implement a logger that uses the react loop for I/O if you need the system to never block on I/O.

I am closing this issue but please feel free to reopen if there is something else you need addressed.
