### ISSUE TITLE
Wamp ZMQ InvalidArgumentException on publish

### ISSUE THREAD

**Issue by johannes-z** [voryx/Thruway#114]
I've set my Wamp Router set up as suggested at: https://github.com/voryx/Thruway/issues/96#issuecomment-98416776

The only thing I changed is the `on` block. The Exception occurs on the `publish` call. It tried some very basic things to, like `$session->publish('test', 'data'));`

```php
$pull->on('message', function ($entry) use ($session) {
	$payload = json_decode($entry, true);

	$event = $payload['event'];
	$data  = $payload['data'];

	$session->publish($event, json_encode($data));
});
```

Edit:
Package versions:
```
cboden/ratchet                        v0.3.3

ratchet/pawl                          v0.1.2
react/cache                           v0.4.0
react/dns                             v0.4.1
react/event-loop                      v0.4.1
react/promise                         v2.2.1
react/socket                          v0.4.2
react/socket-client                   v0.4.3
react/stream                          v0.4.2
react/zmq                             dev-master 78375df

voryx/thruway                         0.3.8
```

**Comment by johannes-z** [comment]
The line causing the Exception is

```php
$publishMsg = new PublishMessage($requestId, $options, $topicName, $arguments, $argumentsKw);
```

in `\Thruway\Role\Publisher`, on `line 144`

this function gets called by the `publish function` in `\Thruway\ClientSession` on `line 68`.

**Comment by johannes-z** [comment]
I found out that the constructor `\Thruway\Message\PublishMessage` is called twice. Once with the right data (the array), and another time with a stdClass object. The `\Thruway\ClientSession publish function` however is called only once (as it's supposed to be, I think).

**Comment by davidwdan** [comment]
What is the exception that you receive?

I do see a couple of issues with your code:

1.  You don't need to json_encode `$data`.  The transport provider will do that for you.
2.  The second argument for `publish` needs to be an array.  

Try this:

```PHP
$pull->on('message', function ($entry) use ($session) {
    $payload = json_decode($entry, true);

    $event = $payload['event'];
    $data  = $payload['data'];

    $session->publish('test.topic', [$data]);
});

```

Also, I just ran the tests and everything passes.  Make sure you're starting the test router for the functional tests:

``` php tests/TestServer.php 30 & phpunit```

**Comment by johannes-z** [comment]
It's an `InvalidArgumentException` thrown in the Publisher

StackTrace:
```
WSCommand.php // starts the websocket
\Thruway\ClientSession in publish
\Thruway\Role\Publisher in public // new PublishMessage...
\Thruway\Message\PublishMessage in setArguments
```

When I pass the `$data` as an array like you did, it works. The thing is though, that the `$data` originally already is an array, so I thought I didn't have to wrap it in another array.

**Comment by davidwdan** [comment]
It might be getting converted to a stdClass by json_encode.  Either way, it's not an issue with publish, so I'm going to close this.
