### ISSUE TITLE
Example for simple authentification does not work

### ISSUE THREAD

**Issue by RafaelKa** [voryx/Thruway#116]
I get following fatal error:
```
Catchable Fatal Error: 
Argument 1 passed to Thruway\Peer\Router::registerModule() must implement interface Thruway\Module\ModuleInterface, 
instance of Thruway\Transport\RatchetTransportProvider given, called in Examples/Authentication/StartRouter.php on line 19 and defined in 
/var/www/projects/wamp.dev/Packages/Libraries/voryx/thruway/src/Thruway/Peer/Router.php line 403
```

**Comment by davidwdan** [comment]
What version of Thruway are you using?

**Comment by RafaelKa** [comment]
i use 0.3.8.

I think (here)[https://github.com/voryx/Thruway/blob/master/Examples/Authentication/StartRouter.php#L19] must be `addTransportProvider()` and not `registerModule()`

**Comment by davidwdan** [comment]
Yeah, I think you're using the examples for the 0.4 branch.  The example you want is:

https://github.com/voryx/Thruway/blob/0.3/Examples/Authentication/StartRouter.php

**Comment by RafaelKa** [comment]
Ok, thanks

**Comment by RafaelKa** [comment]
Anyway it's broken:
see:
https://github.com/voryx/Thruway/blob/master/Examples/Authentication/StartRouter.php#L12
and
https://github.com/voryx/Thruway/blob/master/src/Thruway/Peer/Router.php#L161-L163

**Comment by davidwdan** [comment]
It's broken in v0.3.8?

**Comment by RafaelKa** [comment]
also concerning my previous message it's broken in master -> see both links, especially https://github.com/voryx/Thruway/blob/master/src/Thruway/Peer/Router.php#L161-L163

not sure about v0.3.8 but by using autobahn.js example method [onopen()](https://github.com/voryx/Thruway/blob/master/Examples/Authentication/simpleAutobahnAuth.html#L29-L35) is never called.

**Comment by davidwdan** [comment]
https://github.com/voryx/Thruway/commit/4bf0205970c6fccbb5520465b19b7c4c0d080504 should fix it.  

Let me know if it works.

**Comment by RafaelKa** [comment]
sorry for late answer. 
Now works it on dev-master
