### ISSUE TITLE
Can't run tests with installed libevent 

### ISSUE THREAD

**Issue by SuperStas** [voryx/Thruway#118]
Hello 

I have installed php 5.6.10 and libevent 2.0.21-stable
1 - run test server with timeout
```
php tests/TestServer.php 20
```
2 - run phpunit

On test InvocationAndCallErrorTest::testCallFailureFromException TestServer.php will stop and tests are failure. ( same behavior on InvocationAndCallErrorTest::testCallWithoutProgressOption ) 

If i comment returning LibEventLoop at React\EventLoop\Factory for StreamSelectLoop return, tests are successful.

Also, if mark as skipped testCallFailureFromException and testCallWithoutProgressOption, tests are successful with libevent.

**Comment by mbonneau** [comment]
I think there is an issue where it may create another event loop during testing. StreamSelectLoop doesn't care if you do this, but LibEventLoop complains which causes the tests to fail.

This needs to be cleaned up in the test code so that there are not multiple loops in existence at the same time.

**Comment by SuperStas** [comment]
Thank you @mbonneau

**Comment by mbonneau** [comment]
@SuperStas - Thank you for letting us know about the issue. I am going to reopen this so that we can get it fixed.

**Comment by mbonneau** [comment]
Hi @SuperStas ,

I was looking into this issue to see if I can fix it, but I am not able to reproduce it. Are you using dev-master?

I am using:
```
PHP 5.6.5 (cli) (built: Jan 25 2015 18:20:42)

libevent

libevent support => enabled
extension version => 0.0.4
Revision => $Revision: 318910 $
libevent version => 2.0.22-stable
```

**Comment by SuperStas** [comment]
Hi @mbonneau 
I'm still can reproduce it on dev-master ( last commit is  65b4feee06591012f4e33f6d1ac4959e0ae99688 )

I'm using:
```
PHP 5.6.11-1+deb.sury.org~trusty+1 (cli)

libevent

libevent support => enabled
extension version => 0.1.0
Revision => $Revision$
libevent version => 2.0.21-stable

```

After downgrade version of extension to 0.0.4, i received

```
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

.......................................[warn] event_add: event has no event_base set.
```

**Comment by davidwdan** [comment]
@SuperStas I think that this might be related to https://github.com/reactphp/stream/pull/20

Can you update to the latest version of reactphp/stream and see if you can reproduce it?

**Comment by SuperStas** [comment]
Hi @davidwdan 
Now all tests are passed.

Thank you.
