### ISSUE TITLE
Is there way to receive info about Caller into the Callee?

### ISSUE THREAD

**Issue by SuperStas** [voryx/Thruway#119]
Hi there.
Is there way to receive info about Caller into the Callee?
I want to know some information, such as IP ( if it's not an internal client ), authId, sessionId, etc.
As i understood, there is no way right now, because callee get only three params: args, argsKw, details.
https://github.com/voryx/Thruway/blob/master/src/Thruway/Role/Callee.php#L154

Is it possible in current version? 
Some snippet:
```php
 // 3) register a procedure for remoting
        $add2 = function ($args) {
            return $args[0] + $args[1];
            // would be great, to know authId here
        };
        $session->register('com.myapp.add2', $add2);

        // 4) call a remote procedure
        $session->call('com.myapp.add2', [2, 3])->then(
            function ($res) {
                echo "Result: {$res}\n";
            },
            function ($error) {
                echo "Call Error: {$error}\n";
            }
        );
```

Thank you.

**Comment by mbonneau** [comment]
Hi @SuperStas ,

Yes.

When you register, set the disclose_caller option:

```php
$session->register('com.app.fetch_user', function ($args, $argKw, $details) {
    // $details will be an object that contains caller, authid, etc. properties
}, ['disclose_caller' => true])
```

Take a look at https://github.com/voryx/Thruway/blob/b6d62af2aa2acd4389463766804c40d5ef6c3a86/src/Thruway/Call.php#L301 to get an idea of what else is in there.

This will not contain some of the information you are looking for (like IP address). If you really needed that information you would need to put together an Authentication Provider that can put that info into _thruway_authextra or keep track some other way (like redis or something).

**Comment by SuperStas** [comment]
Thank you @mbonneau  for quick response.
It's solved my issue.

**Comment by lajosbencz** [comment]
Sorry for bumping a closed thread, but I just cant get any info out of $details.

```php
        $session->register('favourites.list', function($args, $argKw, $details) {
            dump($details);
            return [];
        }, ['disclose_caller'=>true]);
```

$details is always an empty stdClass.

My router is crossbar, and I also added this to every role:
```json

              "disclose": {
                "caller": true,
                "publisher": true
              },
```
