### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by Schaumbaum** [voryx/Thruway#120]
I'm not able to pass the phpunit tests in version 0.3.8
First I get a fatal error
Class 'Thruway\Topic\TopicManager' not found in TopicStateManagerTest.php on line 8
after skipping this and the related TopicStateTest I get the following fatal error:
Cannot use object of type stdClass as array in MultipleRegistrationTest.php on line 148
After changing $args[0]['name'] to $args[0]->name
still failing the following tests:
CrossbarTest::testCall()
Failed asserting that false is true.

CrossbarTest::testSubscribe()
Failed asserting that null is greater than 0.

CrossbarTest::testRegister()
Failed asserting that null is greater than 0.

MultipleRegistrationTest::testMultiRegistration()
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'211'
+'[congestion(partitioned_rpc)][congestion(partitioned_rpc)][start 2(0)][RPC 2(0)][congestion(partitioned_rpc)][start 2(1)][start 1(2)][RPC 2(1)][RPC 1(2)]'

PingTest::testServerPing()
Error is com.example.ping.error
Failed asserting that 'com.example.ping.error' is null.

ReplaceOrphanedSessionTest::testReplaceOrphanedSession()
Error was OrphaningClient not registered
Failed asserting that 'OrphaningClient not registered' is null.

Do I miss something?
I'm new to thruway, therefore it might be an install/prerequisites issue.
Using php 5.6.11 with mcrypt 2.5.8

**Comment by mbonneau** [comment]
To run the tests, you need to run the TestServer.php script and then run phpunit from the project root.

**Comment by Schaumbaum** [comment]
I started the TestServer. Are there any parameters needed while starting?
First used phpunit within netbeans, retried it from project root, but still got the same issue.
Haven't found 'Thruway\Topic\TopicManager' in the sources, only 'Ratchet\Wamp\TopicManager'.

**Comment by RafaelKa** [comment]
i think https://github.com/voryx/Thruway/blob/master/.travis.yml can ansver your question

**Comment by Schaumbaum** [comment]
I see me failure. Should start phpunit without additional parameters. Sorry

**Comment by mbonneau** [comment]
I haven't used netbeans in a long time, but it sounds like it created its own phpunit configuration.

**Comment by Schaumbaum** [comment]
Thanks for your fast support.
