### ISSUE TITLE
A question about error message from promise.

### ISSUE THREAD

**Issue by SuperStas** [voryx/Thruway#121]
Hi there!
I have a question about error message from promise.

There is two case when i can get an error, from callee.

First case:
I registered procedure, with some logic and throwing up an exception.
```php
$session->register('com.myapp.add2', function($args, $kwargs, $details){
            //some logic
            $exception = new \Exception('Some error', 1);
            $exception->param = 1;
            throw $exception;
        });
``` 
In caller i had received:
```php
$session->call('com.myapp.add2', [2, 3])->then(
            function ($res) {
                echo "Result: {$res}\n";
            },
            function (\Thruway\Message\ErrorMessage $error) {
                var_dump($error->getArgumentsKw()->param);
                echo "Call Error: {$error}\n";
            }
        );
```
It's router log 
```
onMessage: ([8,68,7579941132210228,{},"com.myapp.add2.error",["Some error"],{"param":1}])
```

That is correct, i had received as i waited.

Second case:
I registered procedure, with some logic in future, and throwing up an exception in promise
```php
$session->register('com.myapp.add2', function ($args, $kwargs, $details) use($session) {

            $deferred = new \React\Promise\Deferred();
            $promise = $deferred->promise();

            $session->getLoop()->addTimer(2, function() use($deferred) {
                $deferred->resolve();
            });

            return $promise->then(function () {
                //some logic
                $exception = new \Exception('Some error', 1);
                $exception->param = 1;
                throw $exception;
            });
        });
```
And i had received, only errorUri.
It's router log in second case: 
```
onMessage: ([8,68,4930431279308326,{},"com.myapp.add2.error"])
```

There wasn't an args and kwargs. 

Is that true way, to add more error information to Callee::processResultAsPromise ( https://github.com/voryx/Thruway/blob/master/src/Thruway/Role/Callee.php#L212-L217 )

Does have the protocol a restriction in this case?
Thank you.

**Comment by mbonneau** [comment]
In the commit I just pushed up, I corrected the promise to behave the same way as the immediate exception does.

As a side note, you can also throw (or reject with) a WampErrorException and have full control over the error message that is sent back.

Please let me know if this resolves your issue.

**Comment by SuperStas** [comment]
Hi @mbonneau!
It works great! Thank you for quick patch.
