### ISSUE TITLE
WampCraUserDbInterface is blocking the loop

### ISSUE THREAD

**Issue by SuperStas** [voryx/Thruway#122]
Hello everyone.

My question about WampCraUserDbInterface::get method in WampCraAuthProvider class [here] (https://github.com/voryx/Thruway/blob/master/src/Thruway/Authentication/WampCraAuthProvider.php#L63) and [here](https://github.com/voryx/Thruway/blob/master/src/Thruway/Authentication/WampCraAuthProvider.php#L133).

In my case, implementation of WampCraUserDbInterface is a remote database, and everytime this method blocking the loop, while waiting response. There will not user information,  If don't waiting response from WampCraUserDbInterface::get method.

Would be great, if WampCraUserDbInterface::get method in WampCraAuthProvider class, will be as one step of chain of promises, then would can call WampCraUserDbInterface::get asynchronous.
  
Is there any way to realize remotely WampCraUserDbInterface::get method without blocking loop? ( except fast static storage )

Thank you.

**Comment by mbonneau** [comment]
Hello @SuperStas ,

Your concern is valid. In our projects, we typically use jwt tokens for authentication to avoid this. (http://voryx.net/using-json-web-token-jwt-for-thruway-authentication/)

Another option that you have, and what I would recommend if you need WampCra, is to run the WampCra authentication in a separate client process. This will prevent the it from blocking the router's event loop. The loop in the client process will still block, but requests will be handled in the order they arrive and will not hold up other processing in the router. If you feel the need to be able to process more than one authentication request at a time, you can run multiple authentication provider clients with the _thruway_multiregister option, but this would currently require overriding (or editting) [here](https://github.com/voryx/Thruway/blob/master/src/Thruway/Authentication/AbstractAuthProviderClient.php#L64-L73).

**Comment by SuperStas** [comment]
Thank you @mbonneau.
I'll look both options.
