### ISSUE TITLE
How to terminate "client" session?

### ISSUE THREAD

**Issue by Braynid** [voryx/Thruway#125]
I'm using crossbar that has a guest worker written with thruway which handles some stuff such as authentication for connections that come from the browser.

Because it handles authentication this worker knows the session IDs for each connected client and I would like to be able to disconnect a client session. Is there any way to do this?

**Comment by mbonneau** [comment]
I dug through the docs and issues on the crossbar project and did not see a way to do that with crossbar as a router. You may want to ask on that project.

**Comment by Braynid** [comment]
Thanks for the help. I thought that maybe I can access sessions from thruway but, as you said, crossbar is the router so I'll try asking there.
