### ISSUE TITLE
MapReduce

### ISSUE THREAD

**Issue by MikeSWelch** [voryx/Thruway#135]
I'm having trouble trying to implement MapReduce with Thruway.

From a high level, I'm looking to issue 100 requests and I want 100 responses.

I'm trying to create 100 clients on the same loop that each subscribe on their own topic.  When I start the loop, the clients will make a post to one of my web servers.  The web server then does the requested work, fires up a client and publishes the completed work on the same topic that the requesting client is listening on.

When I do this with 100 clients, about 90 of the clients get the desired responses and the rest just hang.  I can see that 100 web requests were made, 100 jobs completed, and 100 new clients started up to publish their completed work.  However, about 10 of the requesting clients do not receive responses on their topic.

When I run this with 10 clients, it works.  I have tested running it over 1000 times with 10 clients, and every single client gets a response every time.

How do I figure out why some clients are not receiving their responses?  Is there a TTL so I can set the clients to retry?  Is there a maximum amount of topics that a router can handle concurrently?  Is there a maximum amount of messages a router can handle conccurrently?  Is this a memory issue?

**Comment by MikeSWelch** [comment]
Here is the code:
```php
$arrayOfWork = array();

for ($i=0; $i < 10; $i++) { 
	$arrayOfWork[] = $i;
}

$results = AVThruway::processWorkArray($arrayOfWork);

var_dump(print_r($results));
```

```php
public static function processWorkArray($workArray)
	{
		$loop = \React\EventLoop\Factory::create();
		$results = array();

		Thruway\Logging\Logger::set(new Psr\Log\NullLogger());

		//$url = AVThruway::getRandomRouter();
		$url='ws://172.18.1.127:9090/';
		//$url='ws://172.18.3.10:9090/';

		foreach ($workArray as $work) {

			$topicid = md5(rand());

			$results[$topicid] = null;

		    $client = new AVThruwayClient('realm1', $loop, $work, $url, $topicid,constant('THRUWAY_RETRY_INITIAL_DELAY'));

		    $client->addTransportProvider(new \Thruway\Transport\PawlTransportProvider($url));

		    $client->start(false);
		}

		$loop->run();

		$mcache=new Mcache\MultipartCache();

		foreach ($results as $key => $value) {
			$val = $mcache->get($key);
			//echo 'stuff ' . $key . ": " . $val[0] . "\n";
			$results[$key]=$val[0];
		}

		return $results;
	}
```

```php
<?php
require_once 'classes/AVThruway.class.php';
require_once 'classes/AvAPIMonitor.class.php';

define('THRUWAY_MAX_DELAY',16);            
define('THRUWAY_RETRY_INITIAL_DELAY',1);    //seconds
define('THRUWAY_EXTENSION_FACTOR',2); 


/**
 * Class AVThruwayClient
 */
class AVThruwayClient extends \Thruway\Peer\Client
{
    /**
     * @var int
     */
    private $work;

    /**
     * @var int
     */
    private $topicid;

    /**
     * @var int
     */
    private $router;

    /**
     * @var int
     */
    private $realm;

    /**
     * @var int
     */
    private $loop;

    /**
     * @var int
     */
    private $retrydelay;

    /**
     * @var int
     */
    private $timestart;

    /**
     * Constructor
     * 
     * @param string $realm
     * @param \React\EventLoop\LoopInterface $loop
     * @param int $number
     */
    public function __construct($realm, $loop, $work, $router, $topicid, $retrydelay)
    {
        parent::__construct($realm, $loop);

        $this->work = $work;
        $this->realm = $realm;
        $this->loop = $loop;
        $this->topicid = $topicid;
        $this->router = $router;
        $this->retrydelay = $retrydelay;
        $this->timestart = microtime(true);

        $this->setAttemptRetry(false);
    }

    /**
     * Handle on session start
     * 
     * @param \Thruway\ClientSession $session
     * @param \Thruway\Transport\TransportInterface $transport
     */
    public function onSessionStart($session, $transport)
    {

        $topicid = $this->topicid;
        $router = $this->router;

        $onevent = function ($args) use ($topicid,$session){

            $jsonreturn = json_encode($args[0]);

            $jsonreturn = json_decode($jsonreturn,true);

            //echo print_r($args[0],true);
            //echo print_r($jsonreturn,true);

            
                //This work was completed successfully

                $timeend = microtime(true);
                $totaltime = $timeend - $this->timestart;

                //echo "WOOO I'M DONE! Completed in $totaltime - " . $topicid . "\n\n";
                AvAPIMonitor::incrAPICount('ThruwaySuccess');
                AvAPIMonitor::incrExecTime('ThruwaySuccess',$totaltime);
                //trigger_error('Thruway Success');
          

            //trigger_error('Thruway Session Close!');
            $session->close();

        };
        $session->subscribe($topicid.'.av.workers', $onevent);

        $workdetail = array(
            'func' => 'echo',
            'echo' => $this->work
        );

        //This sends the request to our webserver which will call publishThruwayPayload upon completion
        AVThruway::publishThruwayJob($topicid,$router,$workdetail);
    }

} 
```

```php
	public static function publishThruwayPayload($return)
	{
		$loop = \React\EventLoop\Factory::create();
		$topicid = $return->getFieldData('topicid');
		$router=$return->getFieldData('router');
		$client = new Client("realm1",$loop,$topicid);
		$client->addTransportProvider(new Thruway\Transport\PawlTransportProvider($router));
		$client->on('open', function (Thruway\ClientSession $session) use ($topicid,$return)
		{

			$arr=$return->getResponse();
			
			$session->publish($topicid.'.av.workers', [$arr], [], ["acknowledge" => true])->then(
				function () {
					error_log("Worker Publish Acknowledged!");
					//trigger_error('publishThruwayPayload Worker Publish Acknowledged');
					exit;
				},
				function ($error) {
					// publish failed
					error_log("Publish Error {$error}");
				}
			);

		}); // end client->on
		$arr=$return->getResponse();

		$client->start();
		
	}
```

**Comment by mbonneau** [comment]
It is possible that you are having this issue: https://github.com/reactphp/event-loop/issues/26

Can you try replacing the $loop with:

```php
$loop = new \React\EventLoop\StreamSelectLoop();
```

Let me know if this changes anything. If not I will dig deeper.

**Comment by MikeSWelch** [comment]
Thanks for the quick reply!  

Sadly, I'm still experiencing the same behavior.

**Comment by mbonneau** [comment]
It is possible that your publish and response is happening prior to the completion of your subscription so the client does not receive the event.

I would try publishing only after your subscription has completed:

```php
$session->subscribe($topicid.'.av.workers', $onevent)->then(function () use ($topicid, $router) {

    $workdetail = array(
        'func' => 'echo',
        'echo' => $this->work
        );

    //This sends the request to our webserver which will call publishThruwayPayload upon completion
    AVThruway::publishThruwayJob($topicid,$router,$workdetail);
});
```

I have not setup a project to try and reproduce the issue yet. Let me know if that doesn't change anything.

**Comment by MikeSWelch** [comment]
This actually works for 100 clients!  I got ambitious and tried 200 clients and it hangs.

Is there a way to set a timeout?  I still am unable to pinpoint the actual problem.

**Comment by MikeSWelch** [comment]
This is from php-fpm's slow log:

```
[10-Sep-2015 16:19:45]  [pool www] pid 18139
script_filename = /htdocs/html//thruway_handler.php
[0x00007f955c2adc80] stream_select() /htdocs/thruway/vendor/react/event-loop/StreamSelectLoop.php:255
[0x00007f955c2ada40] streamSelect() /htdocs/thruway/vendor/react/event-loop/StreamSelectLoop.php:221
[0x00007f955c2ad5f0] waitForStreamActivity() /htdocs/thruway/vendor/react/event-loop/StreamSelectLoop.php:201
[0x00007f955c2acfa8] run() /htdocs/thruway/vendor/voryx/thruway/src/Thruway/Peer/Client.php:235
[0x00007f955c2accc0] start() /htdocs/html/includes/classes/AVThruway.class.php:309
[0x00007f955c2ac828] publishThruwayPayload() /htdocs/html/thruway_handler.php:127
```

**Comment by davidwdan** [comment]
Can you try it with libevent?  What version of PHP are you using?

**Comment by recarv** [comment]
Hey David,

Mike and I are working on this together, the machine is running php 5.5 on an amazon virtual machine c3.large. libevent is not currently installed - is this really a magnitude improvement?

We debugged the stack he posted above - with 200 clients StreamSelectLoop:255 was calling usleep with a timeout of over 1.4m usec!  Our slow-log trace limit above was >60sec which caught the stack at the point of trouble. Any ideas?

Thanks to both of you guys for making this btw - we're hoping we can make it do some pretty awesome map/reduce to increase concurrency in cross db result aggregations!

**Comment by recarv** [comment]
And to ammend - 

$ sudo yum install libevent-devel

Package libevent-devel-2.0.18-1.11.amzn1.x86_64 already installed and latest version
Nothing to do

**Comment by MikeSWelch** [comment]
I forced it to use libevent and I'm getting the same results and the following in the slow log:

```
[10-Sep-2015 21:00:19]  [pool www] pid 19782
script_filename = /htdocs/html//thruway_handler.php
[0x00007ffbce52e690] event_base_loop() /htdocs/thruway/vendor/react/event-loop/LibEventLoop.php:211
[0x00007ffbce52e1e8] run() /htdocs/thruway/vendor/voryx/thruway/src/Thruway/Peer/Client.php:235
[0x00007ffbce52df00] start() /htdocs/html/includes/classes/AVThruway.class.php:328
[0x00007ffbce52da08] publishThruwayPayload() /htdocs/html/thruway_handler.php:137
```

**Comment by davidwdan** [comment]
We're running some tests, trying to isolate the issue.  How are you POSTing data to the web server?  Is it done asynchronously?

**Comment by recarv** [comment]
Thanks David, we're using stream_socket_client to post, and  we've tried both sync and async on the socket, both cause the same issue.  The requesting client ignores the response anyway. We've also done testing and can see that the posts are handled extremely quickly (as would be expected), its the point where the Thruway client is created that things slow down significantly.

**Comment by davidwdan** [comment]
We played around with this for a while and tried to make it work the way you're doing it, but we ran into two problems:

1.  When you flood the router with a lot of connections at once, you run into websocket backlog limits.  Once the limit is reach, the router returns a connection refused, which requires you to properly handle the reconnection attempt and clean up the subscription.
2.  I tested apache and nginx and they both quickly hit connection limits as I tried to scale up, which also causes errors that need to be handled properly.

I think a much better approach to this problem would be to use sub processes and RPC calls.  This way you remove the web server overhead and you have some response guarantees with RPC. 

I created a simple example that can handle over 1000 RPC calls.  To try it out, you'll want to make sure that you're using `libevent` and have the following packages installed:

```JSON
 "react/child-process": "0.4.*",
 "react/stream": "dev-master as 0.4.2"
```

start.php:
```PHP
<?php
require_once __DIR__ . '/vendor/autoload.php';

$startTime = microtime(true);
$loop      = \React\EventLoop\Factory::create();
$processes = [];

//Create and start 150 workers
for ($i = 0; $i < 150; $i++) {
    $process = new React\ChildProcess\Process(PHP_BINARY . ' worker.php');
    $process->on('exit', function ($exitCode, $termSignal) {
        echo json_encode($exitCode) . "\n";
    });
    $processes[] = $process;
    $process->start($loop);
}

$client = new \Thruway\Peer\Client('realm2', $loop);
$client->addTransportProvider(new \Thruway\Transport\PawlTransportProvider('ws://127.0.0.1:9090/'));
$client->setAttemptRetry(false);

$client->on('open', function (\Thruway\ClientSession $session) {
    $promises = [];

    for ($i = 0; $i < 1000; $i++) {
        $promises[] = $session->call('do.some.work', [$i]);
    }

    \React\Promise\all($promises)->then(
      function ($results) use ($session) {
          $session->close();
          $session->getLoop()->stop();
          echo "result" . json_encode($results) . " \n" . count($results) . "\n";
      },
      function ($error) use ($session) {
          $session->close();
          $session->getLoop()->stop();
          echo "ERROR" . json_encode($error) . "\n";
      });
});

$client->start($loop);

//End all sub processes
foreach ($processes as $process) {
    $process->terminate();
}

echo microtime(true) - $startTime . "\n";
```

worker.php (sub process):
```PHP
<?php
use Thruway\Peer\Client;

require_once __DIR__ . '/vendor/autoload.php';

$loop   = \React\EventLoop\Factory::create();
$client = new Client("realm2", $loop);
$client->addTransportProvider(new Thruway\Transport\PawlTransportProvider('ws://127.0.0.1:9090'));
$client->on('open', function (Thruway\ClientSession $session) {

    $session->register('do.some.work',
      function ($args) {
          //Simulate blocking web request
          sleep(1);

          return $args[0];
      },
      //This option will tell the router to round robin the requests to all clients that have registered this RPC
      ["thruway_multiregister" => true]);
});

//End this process if it's around for more than 15 seconds.  This is just a fail safe if the parent process doesn't exit properly.
$loop->addTimer(15, function ($timer) {
    $timer->cancel();
});

$client->start();
```

Then run:
```bash
php start.php
```

Let me know if that works for what you're trying to do.

**Comment by recarv** [comment]
David - thanks for the help.  This may work, but my only concern is that we're using the web server calls for resource load balancing (haproxy) across a fleet of machines.  If I'm understanding this example correctly it calls a sub-process on the calling client thereby concentrating any work on the single/same machine - my concern here being that you lose the horizontal scaling feature of map reduce.  Am I missing something (I haven't had coffee yet this morning)?

**Comment by davidwdan** [comment]
You can run the workers on multiple systems or have the workers make the web requests.  There are a couple of options there.

You can also still use Pub/Sub, but use one client with multiple subscriptions instead of multiple clients with one subscription.

**Comment by MikeSWelch** [comment]
David,

Thanks for the suggestions.  When I run your code I don't get any results but I do get the following error around 100 times:
```
2015-09-15T16:51:04.0980320 debug      [Thruway\Transport\PawlTransportProvider 31354] Received: [8,48,5606626964787679,{},"wamp.error.no_such_procedure"]
2015-09-15T16:51:04.0981200 debug      [Thruway\Peer\Client 31354] Client onMessage: wamp.error.no_such_procedure
```

**Comment by davidwdan** [comment]
@MikeSWelch would you mind moving this conversation over to the Thruway group? https://groups.google.com/forum/#!forum/thruway 

I think that's probably a better place to talk about this.

**Comment by davidwdan** [comment]
@MikeSWelch I'm going to go ahead an close this issue.
