### ISSUE TITLE
What is "Event History" mentioned in the feature list?

### ISSUE THREAD

**Issue by ftrrtf** [voryx/Thruway#136]
I could not find anything about this in the code.

**Comment by mbonneau** [comment]
Hi @ftrrtf ,

The "Event History" is provided by subscription state handlers. While not specifically an event history system, it could be used to implement one.

The Thruway router allows you to define handlers that are triggered when a client subscribes to a topic. This handler can then publish events to that particular client that are necessary to bring the client up-to-date on that topic.

I will try to create an example to demonstrate the use when I have a chance.

**Comment by ftrrtf** [comment]
Hi @mbonneau, 
Thank you, that would be wonderful!

**Comment by ftrrtf** [comment]
@mbonneau Any ETA? Thanks.

**Comment by mbonneau** [comment]
@ftrrtf 

I have made an example of how to use "event history" (not the official event history). For now it is located at https://github.com/mbonneau/ThruwayEventHistory/tree/master - we might pull that into the project at some later date as this functionality is pretty generic.

This is a pretty basic example but could be used to build out more complex things if the need arises (stuff that generates a state based on databases or something or only provides events that are still relevant)

Let me know how this works out.

**Comment by ftrrtf** [comment]
@mbonneau Thank you very much for this example! 

For my task I need something like `wamp.topic.history.since`, described in https://github.com/tavendo/WAMP/blob/master/spec/advanced/event-history.md
Your example has helped me better understand how all this things work in the Thruway. Now I will try to adapt it to `since`-like feature. If you have any thoughts or suggestions about that — It would also be good to write them.

Thanks again ;)

**Comment by mbonneau** [comment]
The implementation of the spec ```wamp.topic.history.since``` could all be done with a regular client (except for the feature announcement).

It would be a better approach to use the example and modify it to send you history since an option on the subscription. Otherwise you will have to deal with duplicate delivery issues or missed event issues.

This would also remove the need to make an RPC whenever you subscribe.
