### ISSUE TITLE
call internal service from other class

### ISSUE THREAD

**Issue by patie** [voryx/Thruway#144]
Hi,

i need publish message from listener (or other class) in some cases, but i must call internal client, because in internal client we have stored properties with some data.

I tried register internal client as a service, put this service into $router->addInternalClient(SERVICE HERE) and call method from this service where i need BUT $this->session->publish() doesnt work, because session was empty..

can somebody help me? where im wrong, or what is better way? thank you!

**Comment by davidwdan** [comment]
@patie anyway you can provide a simple working gist of what you're trying to do?

**Comment by patie** [comment]
solved by your symfony bundle ThruwayBundle, thank you
