### ISSUE TITLE
Support for react/stomp

### ISSUE THREAD

**Issue by k-vladyslav** [voryx/Thruway#145]
Hi dear contributors @davidwdan, @mbonneau , @ftrrtf 
Can anyone suggest - how can I integrate https://github.com/reactphp/stomp extension into server? 
I need to communicate with RabbitMQ in non-blocking manner, consume new data messages for each topic and broadcast them to JS clients (like AutobahnJS) over WAMP v2. 
I've already implemented such prototype at Ratchet + reactphp/stomp + AutobahnJS 0.8.2. My current stack uses WAMP v1 because no support of WAMP v2 in Ratchet.
And now I think about migrating to WAMP v2 in order to use mainainable solutions like Thurway + new AutobahnJS.

**Comment by davidwdan** [comment]
@k-vladyslav take a look at this issue.  You should be able replace all of the zeromq parts with stomp, without too much trouble:

https://github.com/voryx/Thruway/issues/96

**Comment by k-vladyslav** [comment]
@davidwdan Thank You for answer
Is there any legal way to subscribe my own callback to event "onSubscribe"? I meant - I want to know when any client being subscribed to any topic at our WS server and do some additional stuff at that moment.

**Comment by davidwdan** [comment]
@k-vladyslav you can subscribe to part of a URI  with the option `match: 'prefix'`.
```PHP  
$session->subscribe('com.myapp.', $onevent, ['match' => 'prefix']);
``` 
which will subscribe to all topics that start with `com.myapp.`

For open and close connections, you can subscribe to the meta events:
`wamp.metaevent.session.on_join`
`wamp.metaevent.session.on_leave`

**Comment by adamlc** [comment]
@k-vladyslav I'm using jakubkulhan/bunny which can use ReactPHP's non-blocking loop. It uses AMQP :)
