### ISSUE TITLE
Unsubscription error (code 8,34) received after unsubscription already confirmed (code 35)

### ISSUE THREAD

**Issue by romo1102** [voryx/Thruway#146]
I'm using Thruway 0.3.9 and the latest Autobahn JS in a project, and I'm having some problems with unsubscribing from topics. I have read issue #98 and #100 without resolving my problem.

This Autobahn debug output shows the problem:

> // subscribe to topic "a"
> autobahn.js:732 WebSocket transport send [32,6884581435244544,{},"a"]
> autobahn.js:732 WebSocket transport receive [33,6884581435244544,1790451923]
> 
> // unsubscribe from topic "a"
> autobahn.js:732 WebSocket transport send [34,7747134776410112,1790451923]
> autobahn.js:732 WebSocket transport receive [35,7747134776410112]
> 
> // subscribe to topic "b"
> autobahn.js:732 WebSocket transport send [32,6052640504938496,{},"b"]
> autobahn.js:732 WebSocket transport receive [8,34,7747134776410112,{},"wamp.error.no_such_subscription"]
> autobahn.js:732 failing transport due to protocol violation: UNSUBSCRIBE-ERROR received for non-pending request ID 7747134776410112
> autobahn.js:5304 Uncaught InvalidAccessError: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 1002 is neither.
> autobahn.js:732 WebSocket transport receive [33,6052640504938496,1646341430]

As you can see, the router responds with MSG_UNSUBSCRIBED (code 35) for topic "a", but then it also sends MSG_ERROR+MSG_UNSUBSCRIBE (code 8,34).

This code, quickly thrown together, reproduces the issue every time:

```html
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <title>Thruway Sub/Unsub Test</title>
</head>

<body>
   <div id="content">
      <button type="button" id="run-test">Sub/Unsub</button>
   </div>

   <script>
      AUTOBAHN_DEBUG = true;
      WEB_SOCKET_DEBUG = true;
   </script>

   <script src="jquery-1.11.3.js"></script>
   <script src="autobahn.js"></script>

   <script>
      $(document).ready(function() {
         var connection = new autobahn.Connection({
            url: 'ws://localhost:8080/',
            realm: 'test1'
         });

         connection.open();

         var active_subscription = null;

         function change_subscription(new_topic){
            console.log("Changing subscription");
            var activate_new_subscription = function() {
               console.log("Remove success. Creating new.");
               add_subscription(new_topic);
            };
            remove_subscription(activate_new_subscription);
         }

         function add_subscription(topic) {
            connection.session.subscribe(topic, function(args) {
               console.log("New topic data:", args);
            }).then(
               function (subscription) {
                  console.log("New subscription active:", topic);
                  active_subscription = subscription;
               },
               function (e) {
                  console.log("Failed subscribing with error:", e.error);
               }
            );
         }

         function remove_subscription(success_callback) {
            connection.session.unsubscribe(active_subscription).then(
               success_callback,
               function (error) {
                  console.log("Couldn't unsubscribe active subscription");
               }
            );
         }

         $("#run-test").click(function(e) {
            if(active_subscription == null)
               add_subscription("a");
            else
               change_subscription("b");
         });
      });
 </script>
</body>

</html>
```

And this is the router:

```php
<?php

require 'vendor/autoload.php';

$loop = \React\EventLoop\Factory::create();
$pusher = new \Thruway\Peer\Client("test1", $loop);

$pusher->on('open', function ($session) use ($loop) {
   $context = new React\ZMQ\Context($loop);
   $pull = $context->getSocket(ZMQ::SOCKET_PULL);
   $pull->bind('tcp://127.0.0.1:5555');

   $pull->on('message', function ($msg) use ($session) {
      $msg_data = json_decode($msg, true);
      if (isset($msg_data['category'])) {
         $session->publish($msg_data['category'], [$msg_data]);
      }
   });
});

$router = new Thruway\Peer\Router($loop);
$router->addInternalClient($pusher);
$router->addTransportProvider(
   new Thruway\Transport\RatchetTransportProvider("0.0.0.0", 8080)
);
$router->start();

?>
```

PHP version is 5.4.45 and precision has been set to 16.

Is there any more information that I can provide?

**Comment by davidwdan** [comment]
@romo1102 I've setup your test code and it subscribes and unsubscribes without any errors.

**Comment by romo1102** [comment]
@davidwdan I posted this issue on a Thursday, and on Monday the week after, everything was working fine. I didn't do anything at all during this time, so I can't really figure out why this is working now. So at least for the time being, the issue has been resolved.

However, could you let this issue stay open until the end of month? I'll report back if the issue returns and hopefully can provide some more information. If not, this probably has been permanently solved (somehow).

Thanks.

**Comment by mbonneau** [comment]
Closing this issue, please feel reopen if you find there are issues.
