### ISSUE TITLE
Accepts incoming messages, no outgoing

### ISSUE THREAD

**Issue by Tuccinator** [voryx/Thruway#148]
I tested everything first on local and it worked perfectly but it seems there is something wrong with live servers?

I am using the simple router provided with Thruway but changed the ip to 0.0.0.0 because I seen it was built upon Ratchet. The strange thing is, I can connect with AutobahnJS and my Thruway client using ws://myserver.com:port and the router logs the incoming messages but it never transmits to the clients. I can also connect to a registered callback from a different client successfully.

**Comment by davidwdan** [comment]
@Tuccinator what is your live environment setup?  What OS and PHP version?

**Comment by Tuccinator** [comment]
Ubuntu 14.10 and PHP v5.5.9

**Comment by davidwdan** [comment]
@Tuccinator can you provide a gist with the code we'll need to reproduce the issue?

**Comment by Tuccinator** [comment]
This is basically all it is. https://gist.github.com/Tuccinator/97781393a55e7653f3c8

**Comment by Tuccinator** [comment]
Anything?

**Comment by davidwdan** [comment]
@Tuccinator Nothing jumps out at me.  Is there any more info you can provide?

**Comment by Tuccinator** [comment]
I also altered the RatchetTransportProvider class instead of creating my own provider. I added it to the gist.

**Comment by davidwdan** [comment]
Does it work with the default RatchetTransportProvider?  

Also, Thruway allows you to add your own authentication provider, so there should be no need to do that within the Transport.  Take a look at the WAMP-CRA example:  https://github.com/voryx/Thruway/tree/a84dd4ca6b1f5441505f801990dad47e20903c4d/Examples/Authentication/WampCra

**Comment by Tuccinator** [comment]
Apparently it does work with the default RatchetTransportProvider, apparently it was my code. Sorry about that. I will close this issue. I really appreciate the help!
