### ISSUE TITLE
is there a way to integrate a push from another php script ?

### ISSUE THREAD

**Issue by deli6z** [voryx/Thruway#149]
I am trying to build a push integration from php script back to client using this Ratchet approach http://socketo.me/docs/push
Is it possible to accomplish this using Thruway?

Thank you.

**Comment by davidwdan** [comment]
@deli6z take a look at this issue:  https://github.com/voryx/Thruway/issues/96

**Comment by deli6z** [comment]
Thank you very much - that works.
I also was wondering whether I can listen for subscribe events like in Ratchet

    protected $subscribedTopics = array();
    public function onSubscribe(ConnectionInterface $conn, $topic) {
        $this->subscribedTopics[$topic->getId()] = $topic;
    }

**Comment by davidwdan** [comment]
@deli6z I guess it depends what you're trying to accomplish.  In dev-master you can create a realm module that subscribes to the `SubscribeMessageEvent` event.

Like this:

```PHP
<?php

class SubscribeModule implements \Thruway\Module\RealmModuleInterface
{

    /** @return array */
    public function getSubscribedRealmEvents()
    {
        return [
          "SubscribeMessageEvent" => ["handleSubscribeMessage", 100],
        ];
    }

    public function handleSubscribeMessage(\Thruway\Event\MessageEvent $event)
    {
        /** @var \Thruway\Message\SubscribeMessage $msg */
        $msg = $event->message;

        echo("topic name: {$msg->getTopicName()} \n");
    }
}
```

And then load that module into your router:

```PHP
$router->getRealmManager()->getRealm('realm1')->addModule(new SubscribeModule());
```

**Comment by deli6z** [comment]
Yeah that is probably something I can use. I was basically just wondering how I could get all current subscribers based on the certain topic, there should be a method for that I believe just need to look at the documentation.

Another concern I have is how to organize topics for all app users. For instance I have a topic for notifications then user123 should be subscribed to 'com.appname.user123.notifications' topic and server should push notifications only using ''com.appname.user123.notifications' topic if notifications belong only to user123. Does that more or less look right?

Thank you!

**Comment by deli6z** [comment]
so I am trying to not use 0mq here - is it possible? Instead of listening for messages on 5555 tcp port can I just create a client and publish a topic to the other clients which are already subscribed? The problem here is that this client should not stay opened persistently b/c it won't need to get any information back from other clients. Also I was trying to start a client within the web http request which was hosing the connection obviously. Can I stop the client right after it published ?

**Comment by davidwdan** [comment]
@deli6z you don't need to use 0mq at all.  The router will keep track of who's subscribing to what topic and then when someone publishes, the subscribers will receive the message.

Take a look at his project:  https://github.com/voryx/WampPost  It's a bridge that'll allow you to publish to the Thruway router over regular http.

**Comment by deli6z** [comment]
@davidwdan I installed WampPost but having problems making POST request from php, doing this 

$ch = curl_init('http://127.0.0.1:8181/pub');
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
	'topic' => 'com.topics.topic1',
	'args' => 'Hello, world'
]));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_VERBOSE, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
$result = curl_exec($ch);

and it does not work. I tried use guzzle instead:

$client = new \GuzzleHttp\Client(['base_uri' => 'http://127.0.0.1:8181']);
$response = $client->request('PUT', 'pub', [
	'json' => [
		'topic' => 'com.topics.topic1',
	        'args' => 'Hello, world'
	]
]);

and it returns 404 and does not work either, however command line curl is working

'curl -H "Content-Type: application/json" -d \'{"topic": "com.topics.topic1", "args": ["Hello, world"]}\' http://127.0.0.1:8181/pub'

logged msg:

[Thruway\Role\Broker 13524] Broker onMessage for {"type":"internalClient","transportAddress":"internal"}: [16,2581162361111133,{},"com.topics.topic1",["Hello, world"]]
				
This is very weird

**Comment by deli6z** [comment]
@davidwdan I fixed it:
changed
'args' => 'Hello, world'
to 
'args' => ['Hello, world']
crazy that it simply does not work b/c of that

**Comment by mbonneau** [comment]
I am closing this now, feel free to reopen if there are more issues with this.

**Comment by Maelfyn** [comment]
> @deli6z you don't need to use 0mq at all. The router will keep track of who's subscribing to what topic and then when someone publishes, the subscribers will receive the message.
> 
> Take a look at his project: https://github.com/voryx/WampPost It's a bridge that'll allow you to publish to the Thruway router over regular http.

Did I read that correctly? I can use WampPost as a drop-in replacement for 0MQ? I'll have to give that a try.
