### ISSUE TITLE
PubSub Response Event: "caller" or "publisher"?

### ISSUE THREAD

**Issue by julianstricker** [voryx/Thruway#150]
With "disclose_publisher":true, when I send a publish-event to a client, the Autobahn Client expects a "publisher"-node in EVENT-message-type details. But Thruway sends a "caller"-node in the details instead. So publisher in autobahn is always "undefined". Is this a bug in Thruway?
Response from Thruway:
[36,4561999451235920,2375946144655644,{**"caller"**:5269846428214546,"authid":"testuser","authrole":"authenticated_user","authroles":["authenticated_user"],"authmethod":"chattoken"},["testmessage"]]

**Comment by mbonneau** [comment]
Hi @julianstricker ,

I cannot find where this is happening. The disclose_publisher information is added here:

https://github.com/voryx/Thruway/blob/cfa90f280d644caea14a437717c8f1f06a992d67/src/Thruway/Message/EventMessage.php#L143

There are also functional tests that cover this here:

https://github.com/voryx/Thruway/blob/cfa90f280d644caea14a437717c8f1f06a992d67/tests/WAMP/DisclosePublisherTest.php#L57

What version of Thruway are you using?

Could you provide code necessary to reproduce this?

**Comment by mbonneau** [comment]
@julianstricker ,

I think I found it in the 0.3 branch:

https://github.com/voryx/Thruway/blob/0.3.9/src/Thruway/Message/EventMessage.php#L139

I will update this.

Thanks for the catch.

**Comment by mbonneau** [comment]
This is fixed in [0.3.10](https://github.com/voryx/Thruway/releases/tag/0.3.10) and was already fixed in the 0.4/master branch.

Please let me know if this works for you.

**Comment by julianstricker** [comment]
It works now, thank you very much!
