### ISSUE TITLE
2 questions; Guest authentication and Message validation?

### ISSUE THREAD

**Issue by Tuccinator** [voryx/Thruway#151]
1. I have found out how to use the authentication manager to allow access to the user. Is there any way to allow a guest authentication that can subscribe but not publish?

2. Is there any way to validate the message before sending to the rest of the clients? i.e.

* User submits a message to 'com.myserver.chat'.
* Router validates the message to make sure it doesn't include any XSS
* Router forwards the message to the rest of the clients subscribed to 'com.myserver.chat'.

**Comment by davidwdan** [comment]
Yes to number 1.  You'll need to setup authorization.  I don't think we have any docs written up for that yet, so I'll look around for some examples for you.

On number 2, if you're using dev-master, you can create a module that inspects the publish messages.  Take a look at this issue https://github.com/voryx/Thruway/issues/149#issuecomment-153184958, the only difference is you'll need to listen for `PublishMessageEvent`.  Any changes you make to the message will get sent on to the Broker.  If you determine that you don't want to forward on the message, you can call `$event->stopPropagation();`.

**Comment by Tuccinator** [comment]
Perfect, thank you! I'll keep this open if you are able to find some examples.

**Comment by Tuccinator** [comment]
Looked through the library and found the authorization manager but I got nothing out of it. Have you found anything for this?

**Comment by mbonneau** [comment]
Hi @Tuccinator ,

Not sure if you found an answer on authorization, but I just posted this if you need direction still:

http://voryx.net/authorization-permissions-with-thruway/

**Comment by Tuccinator** [comment]
I ended up editing the files to permit different roles of users without the authorization manager. Thanks for that post though!



On Thu, Nov 5, 2015 at 12:27 PM -0800, "Matt Bonneau" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Tuccinator<https://github.com/Tuccinator> ,

Not sure if you found an answer on authorization, but I just posted this if you need direction still:

http://voryx.net/authorization-permissions-with-thruway/

-
