### ISSUE TITLE
onhello rejected the promise

### ISSUE THREAD

**Issue by Tuccinator** [voryx/Thruway#155]
2015-11-18T01:27:45.3434650 info       [Thruway\Peer\Router 1610] New Session st
arted {"type":"ratchet","transportAddress":"50.80.16.45"}
2015-11-18T01:27:45.5945590 debug      [Thruway\Transport\RatchetTransportProvid
er 1610] onMessage: ([1,"btcroll",{"roles":{"caller":{"features":{"caller_identi
fication":true,"progressive_call_results":true}},"callee":{"features":{"caller_i
dentification":true,"pattern_based_registration":true,"shared_registration":true
,"progressive_call_results":true,"registration_revocation":true}},"publisher":{"
features":{"publisher_identification":true,"subscriber_blackwhite_listing":true,
"publisher_exclusion":true}},"subscriber":{"features":{"publisher_identification
":true,"pattern_based_subscription":true,"subscription_revocation":true}}},"auth
methods":["wampcra"],"authid":"guest"}])
2015-11-18T01:27:45.5949370 debug      [Thruway\Realm 1610] Got Hello
2015-11-18T01:27:45.5971390 debug      [Thruway\Authentication\WampCraAuthProvid
er 1610] Client onMessage: [Thruway\Message\InvocationMessage]
2015-11-18T01:27:45.6011730 debug      [Thruway\Authentication\AuthenticationMan
ager 1610] Client onMessage: thruway.auth.wampcra.onhello.error
2015-11-18T01:27:45.6024340 error      [Thruway\Authentication\AuthenticationMan
ager 1610] **onhello rejected the promise**
2015-11-18T01:27:45.6037310 debug      [Thruway\Realm 1610] Leaving realm btcrol
l
2015-11-18T01:27:45.6043190 debug      [Thruway\Peer\Router 1610] onClose from {
"type":"ratchet","transportAddress":"50.80.16.45"}
2015-11-18T01:27:45.6049060 info       [Thruway\Transport\RatchetTransportProvid
er 1610] Ratchet has closed

Prior to this error everything was working as expected, guest and users could connect perfectly fine. Now all of a sudden no users can connect and each incoming connection is rejected. Any particular reason behind this?

**Comment by mbonneau** [comment]
Hello @Tuccinator ,

Can you give some details about how your router and authentication are set up?

Was there any changes before this started happening?

Is there a "guest" user defined in the wampcra userdb?

**Comment by Tuccinator** [comment]
https://gist.github.com/Tuccinator/7eeb1f08ee76f4208517

The problem came up occasionally on old web server, for an unknown reason as well. I migrated the files over to a different web server and now it doesn't work at all.

Please refer to the gist to review my changes.

**Comment by mbonneau** [comment]
Hi @Tuccinator ,

I was not able to reproduce the issue with your sample code. I do not have the User::findFirst though, so I had replaced that with:
```php
$user = (object)[
    "secret" => "nawd09h30ha0bsdh9asdh",
    "role" => "some_role"
];
```

Is it possible that User::findFirst is throwing an exception? Thruway will send back an error message to the onhello caller if this happens.

**Comment by Tuccinator** [comment]
I tried to use the UserProvider class with something else and it worked perfectly, so I assume that is not the problem.

**Comment by Tuccinator** [comment]
Any specific files that utilize the onHelloHandler?
