### ISSUE TITLE
WampPort vs ThruwayClient with exit;

### ISSUE THREAD

**Issue by deli6z** [voryx/Thruway#156]
I am using Thruway on top of functioning project which is using php on the server side and Angularjs on the frontend. We are using traditional HTTP requests model. We are trying to utilize websockets for the purpose of notifying clients(browsers) that server has information for them - hence we don't need to have a constant websocket client on the server side, server only needs to publish events to other subscribed browsers. @davidwdan suggested in #149 to use WampPost. The problem with it is that it needs to be running constantly with a certain realm set beforehand. He have a need to run multiple projects with different realms using a single wamp router. So instead of having a WampPost Client running for every project with unique realm I was wondering if I could use ThruwayClient and when it is done publishing simply exit so it is not running for no reason.
It will look something like this:

$client = new Client("realm1");
$client->addTransportProvider(new PawlTransportProvider("ws://127.0.0.1:9090/"));

$client->on('open', function (ClientSession $session) {

   $session->publish('com.myapp.hello', ['Hello, world from PHP!!!'], [], ["acknowledge" => true])->then(
        function () {
            echo "Publish Acknowledged!\n";
            exit;
        },
        function ($error) {
            // publish failed
            echo "Publish Error {$error}\n";
            exit;
        }
    );
});

$client->start();

I don't really like this approach and was wondering if there is a cleaner way to stop client after it has published a message.

Thank you

**Comment by mbonneau** [comment]
Hi @deli6z ,

If you like the WampPost approach, you could run multiple instances of WampPost on different ports - one for each realm.

As an alternative, check out https://github.com/voryx/Thruway/issues/42#issuecomment-59791963 

That will do what you are asking with a more graceful exit.

If you are using this in a HTTP script, you may want to kill the logging to console:

```php
use Psr\Log\NullLogger;
use Thruway\Logging\Logger;

Logger::set(new NullLogger());
```

Let me know if that answers your questions.

**Comment by deli6z** [comment]
thanks that helps
