### ISSUE TITLE
Better error handling for authentication exceptions

### ISSUE THREAD

**Issue by davidwdan** [voryx/Thruway#157]
Right now we just abort without passing on any info.  Also, the abort arguments are in the wrong order.

https://github.com/voryx/Thruway/blob/master/src/Thruway/Authentication/AuthenticationManager.php#L316

**Comment by mbonneau** [comment]
This was fixed here: https://github.com/voryx/Thruway/commit/442b2b8e66c5c8b60e413594ec893256cc495b0d
