### ISSUE TITLE
Unsubscribe not implemented in ClientSession

### ISSUE THREAD

**Issue by mbonneau** [voryx/Thruway#158]

**Comment by vyk12** [comment]
@mbonneau I made the pull request #196 to propose an implementation of this feature, could you tell me how you feel about it?

**Comment by davidwdan** [comment]
@vyk12 thank's for the PR!  We'll take a look at it and get back to you with any feedback.

**Comment by jarkt** [comment]
Still missing. Is there a workaround?

**Comment by hvanoch** [comment]
I am also missing this feature.

**Comment by dearsina** [comment]
This seems like a pretty big deal, or am I missing something?

**Comment by mbonneau** [comment]
This feature has not yet been implemented in this client. I would recommend using https://github.com/voryx/RxThruwayClient which is more advanced and supports unregistration.

I am closing this issue. I will check out the PR and comment over there.
