### ISSUE TITLE
Instance of a new connected client and subscribed Topics

### ISSUE THREAD

**Issue by douglasgalico** [voryx/Thruway#159]
Hi!

I 'm implementing a Router with custom Auth then setting a RatchetTransportProvider and then I've added a new custom InternalClient to my Router.
My custom Client acts like a Pusher, I'm using ZMQ to handle the communication between this Wamp Server and the other parts of my application and Publish intelligently according to the ZMQ request.
I'ts working great!

So I 'm facing a problem that I cannot solve:
Every Client(Browser with AutobahnJS) subscribe to a different topic and I need to access this information when the Client subscribe... Something like onSubscribe.

I'm planning register inside my Pusher(custom InternalClient) a list of subscribed clients, pushing into list when the Client subscribe and pull off when the Client unsubscribe? I'ts possible? How I handle this?

Where is the best way to deal with single connected Client?(and get their subscribed topics, attributes, etc.)

**Comment by davidwdan** [comment]
You can create a module that keeps track of the subscribed events.  Something like this: https://github.com/voryx/Thruway/issues/149#issuecomment-153184958

If you want to access the subscription information from another client, have the module extend `Thruway\Module\RouterModuleClient` and then you can register RPCs in `onSessionStart`.  You'll need to register it as a router module instead of a realm module:

`$router->registerModule(new SubscribeModule('realm1'));`

You can take a look at https://github.com/voryx/Thruway/blob/master/src/Thruway/Authentication/AuthenticationManager.php to see how that type of module can be implemented.

**Comment by douglasgalico** [comment]
@davidwdan Nice! I understand the concept of a RouterModule, probably this will be the final implementation!

So, now I'm facing another issue, you're showing to me an implementation of dev-master version of Thruway, right?
I was using 0.3.10, but when I change to dev-master my Pusher implementation crashes, I cannot get the messages from ZMQ..

Resuming my custom internal client:

```php

use Thruway\Peer\Client;
use React\ZMQ\Context;
use ZMQ;

class Pusher extends Client {
    protected $sessions = [];
    public function onSessionStart( $session,  $transport)
    {
        $context = new Context($this->getLoop());
        $pull    = $context->getSocket(ZMQ::SOCKET_PULL);
        $pull->bind('tcp://127.0.0.1:5555');
        $pull->on('message', [$this, 'onPullMessage']);
    }

    public function onPullMessage($data)
    {
        $entryData = json_decode($data, true);
        if (!isset($entryData['channel'])) {
            return;
        }
        if (isset($entryData['session_id'])) {
            return;
        }
        $this->getSession()->publish($entryData['channel'], [$entryData]);
    }
}
```

Could be something with the Loop?

**Comment by davidwdan** [comment]
@douglasgalico how are you adding the Pusher client to the router?

**Comment by douglasgalico** [comment]
I've added by the router, using addInternalClient:

` $router->addInternalClient(new Pusher('services', $router->getLoop())` 

Now I'm trying like this comment too: https://github.com/voryx/Thruway/issues/96#issuecomment-98416776

Occurs in both ways...
What makes it happen is when I change the version to dev-master, from 0.3.x(10) to dev-master.

**Comment by mbonneau** [comment]
Hi @douglasgalico ,

I have setup a project with the Pusher class you have and a simple router:

```php
<?php

require __DIR__ . "/vendor/autoload.php";
require __DIR__ . "/Pusher.php";

use Thruway\Peer\Router;
use Thruway\Transport\RatchetTransportProvider;

$router = new Router();

$transportProvider = new RatchetTransportProvider("127.0.0.1", 9090);

$router->addTransportProvider($transportProvider);

$router->addInternalClient(new Pusher('services', $router->getLoop()));

$router->start();
```
This setup works for me in both 0.3.10 and dev-master.

If the only place you reference the loop is in the Context constructor, that should not be an issue as it will be the same as the loop from the router.

Is it possible that it is something else that is causing the issue? Either something more to the pusher or some other part of the router that is killing it?

If you remove ```$router->addInternalClient(new Pusher('services', $router->getLoop())``` from your router, do the other parts still work fine?

**Comment by douglasgalico** [comment]
Hi @mbonneau could be something right after ZQM emits the 'message' event.

Well, if I remove `$router->addInternalClient(new Pusher('services', $router->getLoop())` the other parts work without problem...  Actually the problem seems to be when we try to Publish after the event.

I'm using this resumed code:

```php
        $loop   = \React\EventLoop\Factory::create();
        $pusher = new \Thruway\Peer\Client("services", $loop);



        $pusher->on('open', function ($session) use ($loop) {
            Logger::info(null,'Opened!');
            $context = new \React\ZMQ\Context($loop);
            $pull    = $context->getSocket(\ZMQ::SOCKET_PULL);
            $pull->bind('tcp://127.0.0.1:5555');

            $pull->on('message', function ($entry) use ($session) {

                Logger::info(null,'MessageSent!');

                $entryData = json_decode($entry, true);
                $session->publish('main', [$entryData]);

            });
        });

        $router = new \Thruway\Peer\Router($loop);
        $router->addInternalClient($pusher);
        $router->addTransportProvider(new \Thruway\Transport\RatchetTransportProvider("127.0.0.1", 7474));
        $router->start();

```

With the `0.3.x` everithing works fine and when I push new messages to ZMQ I got my output like this:
```
2015-12-07T11:24:23.8067360 info       MessageSent!
2015-12-07T11:24:24.0490690 debug      [Thruway\Role\Broker 2537] Broker onMessage for {"type":"internalClient","transportAddress":"internal"}: [16,3843112381797210,{},"main",[{"channel":"main","type":"main","data":["sdsgf"]}]]
```

But with `dev-master` everything runs 'fine' until the Publish step, output after push to zmq:
```
2015-12-07T11:40:49.8067360 info       MessageSent!
```

ZMQ event bing is ok, but I can't publish to $session.
Really strange, this occur when I change the version.

**Comment by davidwdan** [comment]
Are you getting some sort of error or are you going by the log?  The debug info for "Broker on Message" was removed in 0.4.

**Comment by douglasgalico** [comment]
@davidwdan "Broken on Message"  is a custom message that i made.

So.. The version problem was my mistake, now I'ts all fixed and working.
I'm finishing here and I'll post here the resume of the implementation for anyone who needs for the same purpose(RouteModule, Oauth2 Auth, Subscribed topics, ...).
@davidwdan and @mbonneau  thanks for the help and the tips, this library is awsome!
Let's consider closed and then when I finish here I comment with the code.

**Comment by mbonneau** [comment]
@douglasgalico I am closing this now but please still post your implementation for others if you get a chance.
