### ISSUE TITLE
role for authorization rules is not a part of uri but is validated as uri

### ISSUE THREAD

**Issue by RafaelKa** [voryx/Thruway#161]
As you can see in [AuthorizationManager.php line 278](https://github.com/voryx/Thruway/blob/master/src/Thruway/Authentication/AuthorizationManager.php#L278) 

```
//...
static::isValidRuleUri($rule->uri) && Utils::uriIsValid($rule->role)
//...
```

rules role is validated as if it were uri.

Why can role not contain the uppercase letters and other chars?
Many Frameworks do not use lower case only role identifiers:
[Symfony Authorization uses UPPERCASE_DEVIDED_BY_UNDERLINE](http://symfony.com/doc/current/components/security/authorization.html) -> 
[Flow Security uses Vendor.PackageKey:RoleIdentifier](http://flowframework.readthedocs.org/en/stable/TheDefinitiveGuide/PartIII/Security.html)

After source invstigation i think that it is not relevant if roles identifier is valid to the the uri specs and we can conserve frameworks definitions for roles.

What do you think?

**Comment by oberstet** [comment]
This should be clarified in the WAMP spec. Using URIs makes sense IMO, else we are introducing yet another ID space.

**Comment by RafaelKa** [comment]
I do not see anything about roles definitions for authorization context in WAMP specs. 
WAMPs specs defines only [pear roles: "Callee, Caller, Publisher,  Subscriber, Dealer, Broker"](https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#page-10), which are a part of uri but for outhorization/Black- and Whitelisting WAMP specs defines ["authrole"](https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-13.4.1.2.2), which is not a part of uri and which is defined only as string.

But anyway, can somebody please clarify it by WAMP folks?

**Comment by mbonneau** [comment]
This discussion can continue in the spec issue above as it is a spec thing.
