### ISSUE TITLE
Automated Crossbar Test Failing

### ISSUE THREAD

**Issue by davidwdan** [voryx/Thruway#162]
Automated crossbar tests are failing because crossbar isn't starting.
https://travis-ci.org/voryx/Thruway/jobs/96098232#L1378

Related to this issue:  https://github.com/crossbario/autobahn-python/issues/561

**Comment by oberstet** [comment]
yeah, sorry. fixed in https://pypi.python.org/pypi/crossbar/0.11.2

**Comment by davidwdan** [comment]
Awesome!! Thank you.
