### ISSUE TITLE
Different api by client transport providers

### ISSUE THREAD

**Issue by RafaelKa** [voryx/Thruway#165]
[PawlTransportProvider](https://github.com/voryx/Thruway/blob/master/src/Thruway/Transport/PawlTransportProvider.php#L36) 
```
    /**
     * Constructor
     *
     * @param string $URL
     */
    function __construct($URL = "ws://127.0.0.1:8080/")
    {
        $this->URL     = $URL;
    }
```
and [RawSocketClientTransportProvider](https://github.com/voryx/Thruway/blob/master/src/Thruway/Transport/RawSocketClientTransportProvider.php#L37)
```
    /**
     * Constructor
     *
     * @param string $address
     * @param int $port
     */
    function __construct($address = "127.0.0.1", $port = 8181)
    {
        $this->address   = $address;
        $this->port      = $port;
        $this->transport = null;
    }
```
have different constructors.

I would like to provide a PR for united API but i'm not sure which way is preferred by community.

Please note, that react/socket-client provides [tls](https://github.com/reactphp/socket-client#async-ssltls-connections) and [UDS](https://github.com/reactphp/socket-client#unix-domain-sockets) connections 
as well ratchet/pawl provides [secure web socket connection](https://github.com/ratchetphp/Pawl/blob/3ba8d56c36e538c6d189601d58c25f406ebb2134/src/Factory.php#L46)

So i think url way will be more robust:
for Pawl
```
'ws://domain_name_or_ip:port'
'wss://domain_name_or_ip:port'
'unix:///path_to_uds.sock' 
```
Not sure but Pawl seems to support currently [unix://](http://php.net/manual/de/transports.unix.php) as well, because it uses [Connector::create() method](https://github.com/ratchetphp/Pawl/blob/3ba8d56c36e538c6d189601d58c25f406ebb2134/src/Factory.php#L48) from react/socket-client

for RawSocket
```
'tcp://domain_name_or_ip:port'
'tls://domain_name_or_ip:port'
'unix:///path_to_uds.sock'
```
Also i think that the RawSocketClientTransportProvider can be revised to give a way for similar api with Pawl.

PS: I provided PR for [react/socket UDS support](https://github.com/reactphp/socket/pull/17) and psychoticmeow did [similar for UDS but with BC break](https://github.com/reactphp/socket/pull/6) so if it is merged we can use UDS for router as well.

**Comment by davidwdan** [comment]
@RafaelKa different transport providers have different constructors because they can have different dependencies.  I see your point about using a url, but I can see circumstances where you may have a transport provider without a url - like a serial port provider. 

I think it's best to let each transport provider implementation define it's own requirements, instead of trying to shoehorn them into a format that might not be conducive to that transport.

**Comment by RafaelKa** [comment]
Why you can not define UART as URI?, just using `comm://port_id;baudrate=9600;something=bla`

With current API it is impossible to use UDS/TLS for RawSocket clients. 
I think also, because RawSocket and Pawl providers using the same protocoll and same lib for low level layer ( also react/socket-client ), oth can get same API

**Comment by mbonneau** [comment]
Right now we are going to leave it up to the transports to decide what they need for construction. I would rather not develop new URI schemes as that is outside of the project scope. http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml
