### ISSUE TITLE
Issue with multiple realms in Simple Authentication

### ISSUE THREAD

**Issue by deli6z** [voryx/Thruway#167]
Hi guys. I have a question about a specific code example you have here https://github.com/voryx/Thruway/blob/master/Examples/Authentication/StartRouter.php

Based on this code sample it looks like we need to specify a realm name so authentications works for it.
In the project I work on we have multiple instances hence we have many realms which get added/removed constantly. We are currently using simple router version which works for all realms and then client specifies what realms will it work in. Is it possible to force router to work in all realms or we have to explicitly define all reals like in the example?

Thank you.

**Comment by davidwdan** [comment]
@deli6z You can pass an asterisk as the realm, which will enable that authentication for all realms:

```$authProvClient = new SimpleAuthProviderClient(["*"]);```

**Comment by mbonneau** [comment]
Closing this issue. If @davidwdan's suggestion did not work, feel free to post again.

**Comment by deli6z** [comment]
sorry for not responding right after. Yeah that suggestion works. Thank you!
