### ISSUE TITLE
Pass message on authentication failure

### ISSUE THREAD

**Issue by RafaelKa** [voryx/Thruway#168]
Is it possible to pass messages in message: "" field of response?

```
{reason: "thruway.error.authentication_failure", message: "", retry_delay: null, retry_count: null, will_retry: false}
```

also i would like to pass messages like:
"Wrong credentials or user does not exist."
"Service currently not available." for example if database currently not available
"Signing algorithm not trusted" for example if JWT is not accepted, because algorithm is not whitelisted.

expected is following:
```
{reason: "thruway.error.authentication_failure", message: "Wrong credentials or user does not exist.", retry_delay: null, retry_count: null, will_retry: false}
```

**Comment by mbonneau** [comment]
Hi @RafaelKa ,

In https://github.com/voryx/Thruway/releases/tag/0.4.1 I have added the ability to control the abort message. On the AbstractAuthProviderClient, processHello, preProcessAuthenticate, and processAuthenticate support return failures in this format:

```php
return [
            "FAILURE",
            [
                "abort_uri" => "my.custom.abort.uri",
                "details" => [
                    "message" => "My custom abort message"
                ]
            ]
        ];
```

**Comment by RafaelKa** [comment]
@mbonneau: cool, very nice with customizable abort uri now.

**Comment by mbonneau** [comment]
@RafaelKa ,

Did this resolve your issue?

**Comment by RafaelKa** [comment]
@mbonneau, yes thanks i'll close this

**Comment by davidwdan** [comment]
try something like this:

```PHP
public function processAuthenticate($signature, $extra = null)
{

    try {
        if ($this->authenticate($signature)) {
            return ["SUCCESS"];
        } else {
            return ["FAILURE"];
        }
    } catch (Exception $e) {
        return [
            "FAILURE",
            [
                "abort_uri" => "my.custom.abort.uri",
                "details"   => ["message" => $e->getMessage()]
            ]
        ];
    }

}

public function authenticate($token)
{
    Yii::$app->db->open();
    if ($user = User::findIdentityByAccessToken($token)) {
        return true;
    }
    return false;
}
```
