### ISSUE TITLE
How to use the PhpAmqpLib with Thruway

### ISSUE THREAD

**Issue by nepda** [voryx/Thruway#169]
Hi,
like in #96 I want to use a message queue as data provider. But we have to use RabbitMQ with PhpAmqpLib (`videlalvaro/php-amqplib`).  But with the following code the loop and the $channel->wait(); will block the Thruway server.
```php
<?php

require_once 'vendor/autoload.php';

use Thruway\Peer\Router;
use Thruway\Transport\RatchetTransportProvider;
use PhpAmqpLib\Connection\AMQPStreamConnection;

$realm = 'realm1';

$router = new Router();

$client = new \Thruway\Peer\Client($realm, $router->getLoop());

$client->on('open', function () {
    $connection = new AMQPStreamConnection('localhost', 5672, 'guest', 'guest');
    $channel = $connection->channel();

    $channel->queue_declare('hello', false, false, false, false, true);

    echo ' * Waiting for messages. To exit press CTRL+C', "\n";

    $callback = function ($msg) {
        echo " * Message received", "\n";
        var_dump($msg->body);
        // TODO send msg->body to WS clients
    };

    $channel->basic_consume('hello', '', false, false, false, false, $callback);

    while (count($channel->callbacks)) {
        $channel->wait(null, true);
    }
});

$router->addInternalClient($client);

$transporter = new RatchetTransportProvider("localhost", 8080);
$router->addTransportProvider($transporter);
$router->start();
```
(gist version: https://gist.github.com/nepda/1d95e9b81ba86eca982b)

Do you have a hint, how to get this work?
Thank you!

**Comment by RafaelKa** [comment]
Also with pure PhpAmqpLib you can't do that, see [this lines in your example](https://gist.github.com/nepda/1d95e9b81ba86eca982b#file-not-working-websocket-example-php-L31-L33)
Also you can't use libs with network/file access without event loops! For your intention see please https://github.com/JCook21/ReactAMQP

**Comment by nepda** [comment]
Thank you for your fast response. Unfortunately the library you mention (https://github.com/JCook21/ReactAMQP) is deprecated. *"This library is no longer maintained and should be considered deprecated."*.
Any other ideas?

**Comment by davidwdan** [comment]
Haven't had a chance to look into it, but if you can use the STOMP protocol with RabbitMQ, you might be able to use:  https://github.com/reactphp/stomp

**Comment by RafaelKa** [comment]
there is another lib for amqp in react [bunny/bunny](https://github.com/jakubkulhan/bunny)

**Comment by cboden** [comment]
One issue you'll probably run into with either videlalvaro/php-amqplib or the PECL AMQP library is their I/O is internalized and most likely unable to hook into an EventLoop so your I/O will be blocking.

**Comment by nepda** [comment]
Okay impossible :-). So we changed our architecture. W're now using WampPost and pushing messages directly to the WebSocket server. No Queue service needed anymore.
Thanks!
