### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by drtzack** [voryx/Thruway#178]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for voryx/thruway ^0.4.2 -> satisfiable by voryx/thruway[0.4.2].
    - Conclusion: remove symfony/event-dispatcher v3.0.2
    - Conclusion: don't install symfony/event-dispatcher v3.0.2
    - voryx/thruway 0.4.2 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - guzzle/guzzle v3.9.0 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - guzzle/guzzle v3.9.1 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - guzzle/guzzle v3.9.2 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - guzzle/guzzle v3.9.3 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.10, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.11, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.12, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.13, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.7, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.8, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.9, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.7.0, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.7.1, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.7.2, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.7.3, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.7.4, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.7.5, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.7.6, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.7.7, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.7.8, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.7.9, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.8.0, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.8.1, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.8.2, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.0, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.1, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.10, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.11, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.12, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.13, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.2, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.3, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.4, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.5, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.6, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.7, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.8, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.1.9, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.0, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.1, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.10, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.11, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.2, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.3, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.4, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.5, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.6, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.7, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.8, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.2.9, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.0, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.1, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.10, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.11, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.12, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.13, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.14, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.15, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.16, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.17, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.18, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.19, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.2, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.20, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.21, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.22, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.23, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.24, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.25, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.26, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.27, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.28, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.29, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.3, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.30, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.31, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.32, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.33, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.34, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.35, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.36, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.37, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.4, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.5, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.6, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.7, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.8, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.3.9, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.0, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.1, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.10, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.2, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.3, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.4, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.5, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.6, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.7, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.8, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.4.9, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.0, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.1, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.10, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.11, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.12, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.2, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.3, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.4, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.5, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.6, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.7, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.8, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.5.9, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.0, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.1, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.2, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.3, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.4, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.5, v3.0.2].
    - Can only install one of: symfony/event-dispatcher[v2.6.6, v3.0.2].
    - Installation request for symfony/event-dispatcher == 3.0.2.0 -> satisfiable by symfony/event-dispatcher[v3.0.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by RafaelKa** [comment]
Hey @drtzack, are you trying to install Thruway for some Framework? Please show us whole composer.json file

**Comment by drtzack** [comment]
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "intervention/image": "2.*",
        "fzaninotto/faker": "^1.5",
        "lsolesen/pel": "^0.9.3",
        "barryvdh/laravel-ide-helper": "^2.1",
        "guzzlehttp/guzzle": "^6.1",
        "doctrine/dbal": "~2.3",
        "laravelcollective/remote": "5.2.*",
        "vinelab/url-shortener": "dev-master",
        "vinkla/hashids": "^2.2",
        "yajra/laravel-datatables-oracle": "~6.0",
        "laravelcollective/html": "5.2.*"
    },
    "require-dev": {
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Drtzack\\Api\\": "packages/drtzack/api-php/src"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "repositories": [{
        "type": "vcs",
        "url": "http://github.com/drtzack/url-shortener"
    }]
}

**Comment by RafaelKa** [comment]
@drtzack: see "guzzlehttp/guzzle" version requred by laravell is higher as from Thruway.
Please ask https://github.com/Vinelab/minion or laravel if there is a way to use older guzzle version for Laravel Framework.

**Comment by davidwdan** [comment]
The issue is with the versions of event-dispatcher not necessarily Guzzle or Laravel.  Guzzle3 requires ~2.1 and something else you have installed requires v3.x.

Give this a try:
composer require "symfony/event-dispatcher": "3.0.2 as 2.1"

**Comment by drtzack** [comment]
It's worked. Thank you @davidwdan

**Comment by davidwdan** [comment]
Great, I'm going to close this issue then.
