### ISSUE TITLE
Publish message every second?

### ISSUE THREAD

**Issue by Tuccinator** [voryx/Thruway#179]
This isn't exactly an issue, more of an insight.

Currently my application uses JavaScript to make a websocket call every second, which checks database and updates rows, etc. It works fine with 2 people calling every second but when a surge of 400 people are calling every second, each at different intervals, it causes huge issues; random database entries and arithmetic calculations. I have concluded that the best way to solve this would be more the users to subscribe instead of call, have a PHP websocket client that emits a message every second instead. This way all users stay the same and it limits the amount of database calls to 1 per second, relative to 400 per second.

**Comment by dschissler** [comment]
I'm still some months away from introducing websockets into my application and this is exactly the kind of thing that I was thinking about.  I think that you just need to think about the server being able to push rather than the browser needing to poll (whether by websockets or AJAX).  Thanks because this saved me some thought on the matter and once understood it is very obvious.

**Comment by Tuccinator** [comment]
You're welcome. If there is anyone else who is able to provide some kind of solution to this; it would be much appreciated.

**Comment by samizdam** [comment]
Se to periodic timer in loop. Your client code should be like this: 
```

$client->on('open', function (ClientSession $session) use ($client) {
    $client->getLoop()->addPeriodicTimer(5 /* publish every 5 secs. */, function () use ($session) {
        $session->publish('topic_name', ['Hello'], [], ["acknowledge" => true])->then(
            function () {
                echo "Publish Acknowledged!\n";
            },
            function ($error) {
                // publish failed
                echo "Publish Error {$error}\n";
            }
        );
    });
});

$client->start();

```
