### ISSUE TITLE
It is possible to send an array with keys as $arguments in publish method ? 

### ISSUE THREAD

**Issue by dnadeau-quatral** [voryx/Thruway#180]
I try to send an array with keys like this:
```
//this will not work
$this->session->publish('com.myapp.position_updated', array('user'=>12,'level'=>10));

//but this will work
$this->session->publish('com.myapp.position_updated', array(1,1,1));
```
This is the error I got in my webpage when trying with keys:
```
Potentially unhandled rejection [3] {"error":"com.example.update_position.error","args":[""],"kwargs":{"xdebug_message":"\nInvalidArgumentException:  in C:\\Users\\xxxx\\PhpstormProjects\\Thruway2\\vendor\\voryx\\thruway\\src\\Thruway\\Message\\Traits\\ArgumentsTrait.php on line 72
```
Do I'm missing something ?

**Comment by mbonneau** [comment]
All associative arrays are converted to objects when serialized through json_encode. Because JSON does not have a way to represent associative arrays and objects differently, there is not much that you can do to get around if.

In order to use it as an array, you would need to cast it back once it is in your procedure.

```php
$myRpcEndpoint = function ($args) {
    $myAssociativeArray = (array)$args[0];
    
    // ... rpc stuff
};
```

```php
$encoded = json_encode(array('user'=>12,'level'=>10));

var_dump($encoded);
// outputs: string(22) "{"user":12,"level":10}"

$decoded = json_decode($encoded);

var_dump($decoded);
// outputs:
// class stdClass#1 (2) {
//   public $user =>
//   int(12)
//   public $level =>
//   int(10)
// }


var_dump((array)$decoded);
// outputs:
// array(2) {
//    'user' =>
//    int(12)
//    'level' =>
//    int(10)
// }
```

**Comment by mbonneau** [comment]
Sorry, I misread your original question.

The arguments need to be sent as a non-associative array (array without string keys). If you wrap your array inside another array (send it as the first argument) it will pass through (although it will get converted to an object in the process as stated above).

```php
$this->session->publish('com.myapp.position_updated', array(array('user'=>12,'level'=>10)));
```

**Comment by dnadeau-quatral** [comment]
Thanks for this fast response, I'll try it.

**Comment by dnadeau-quatral** [comment]
It works like a charm. Thank a lot!
