### ISSUE TITLE
[RPC] Autobahn claims "wamp.error.no_such_procedure"

### ISSUE THREAD

**Issue by TheMiller2015** [voryx/Thruway#181]
Hello (again)!

I want to use RPCs. My setup is a crossbar.io-node with an php-guest (should be used as "websocket-server"). This guest uses Thruway and registers RPC-Functions.

When a client connects to the crossbar-node it can communicate with the "server" (client.php) via pub/sub.

But every rpc fails with "wamp.error.no_such_procedure".

I tried all examples, visited stackoverflow, google etc. but no solution.

I guess it is becaue of the HAProxy. I use HAProxy in order to do the ssl-termination. So the websocket-url is wss://. 

As said above: Communication works great over wss and worked also with RatchetPHP<->WSS. 

But when I run an example without wss, rpcs are going through. Can someone tell me, what else I do have to tunnel or proxy? I don't know right now.

Machine: Development: Win10, latest Autobahn, latest crossbar, py2.7 (followed crossbar-install-docs), latest HAProxy.

Thanks

**Comment by TheMiller2015** [comment]
Now, I switched from HAProxy to NGinX. But the error is still the same.

**Comment by mbonneau** [comment]
So you are using a crossbar router with a Thruway php client that is registering an RPC endpoint? If this works without SSL I would suspect that there is a certificate error. Are you getting any error messages on the PHP end?

**Comment by TheMiller2015** [comment]
I did more tests. It is a connection-problem. While I'm able to connect from JS to wss://site.localhost/wss/ the thruway-client (autoloaded via guest-directive from crossbar.io) can't connect to this wss-url. I just get the message (from the crossbar-process): 

> [Guest 4800] 2016-02-26T17:48:46.0276340 info       [Thruway\Transport\PawlTransportProvider 4800] Could not connect: DNS Request did not return valid answer.

I tried all formats like wss://127.0.0.1/wss/ | ws://site.localhost | with port / without port. etc. I also used the examples of thruway.

So the rpc can't be registered (I think). 

But what is the problem?
nginx with wss-conf (upgrade-header) etc everything fine. No ssl-problems. When registering a RPC from the JS-Side (Clientbrowser) it works.

**Comment by mbonneau** [comment]
If you are able to do Pub/Sub, you should be able to do RPC. Are the configurations for wss different than ws in crossbar?

**Comment by TheMiller2015** [comment]
Hey thanks for the great support. I disabled the built-in guest (thrughway) client. Then, I started crossbar and then the thrughway client via a cygwin-environment. And THEN I saw the client logs messages and what's going on. Before, the crossbar-server hungs at "Starting transport". Then, I saw, that the client had a proble
With the ssl cert (it's self-signed - may this be the problem? / dev-env). When I switched to ws, the client worked well! So, it's an ssl problem, which was not shown because the client hung. I'm tryingnto figure out, what exactly tje sal problem is. Thanks

**Comment by mbonneau** [comment]
Hi @TheMiller2015 ,

If you are still having an issue with this, check out #171 .

Please let us know what you find.

**Comment by TheMiller2015** [comment]
Hello, just saw, that you answered again. 

All problems regarding this are gone. The problem was, that the Thruway-Client that connected to crossbar threw exceptions and I didn't see the exception-messages because of a configuration-error. After I recoded the Client correctly, things were working fine.

Thanks for your help and sorry for the confusion ;)

**Comment by mbonneau** [comment]
You are welcome.
