### ISSUE TITLE
Thruway with Rachet Routing

### ISSUE THREAD

**Issue by lolek77** [voryx/Thruway#184]
Currently I use a simple Rachet WsServer and I must implement WAMP architecture. I want use Rachet Routing like:

```
        $collection = new RouteCollection;
        $collection->add('websocket', new Route('/notifications', [
            '_controller' => new WsServer(new Notification)
        ]));
        $router = new Router(
            new UrlMatcher($collection, new RequestContext()
            )
        );
        $server = IoServer::factory(
                new HttpServer(
                $router
                ), $port
        );
```

Is it possible?

**Comment by mbonneau** [comment]
With the way the Ratchet transport is setup right now this is not possible. I am assuming that you could accomplish this by modifying the transport provider, but that is an exercise I don't have time for at the moment.
