### ISSUE TITLE
Best practise - using Thruway within php-app to notify users

### ISSUE THREAD

**Issue by TheMiller2015** [voryx/Thruway#186]
Hello, it's me again ;)

Maybe it's a dump questions or a dump topic-title, but I don't know how else to call it. I have a general question on how to use Thruway for notifing users within a "normal" php-application. It's not a browser game, no collaboration-application, just a CRUD-page. When one user inserts or updates data, the saving-procedure should publish this event via thruway to a channel so that others will be informed.

I have a working solution, but I don't know, if this is best practise. 

I am running crossbar.io as router and within this router a thruway-client (running all the time) for auth- and session-handling. The user connects via autobahn. Everything fine.

But here comes the question:
On the php-app-side, I thought about a \Peer\Client-Class that connects on demand. So when an action like saving data is triggered, the Client would be instantiated, connects to the router and publishs to to specific topic. This solution works, but there are two problems. The first problem is, that the php-script is blocking when the router isn't available/down, even when I add the option that the client shouldn't reconnect (don't know option name by heart). The second "problem" is about publishing. The "publish"-method can run only once. When I try to publish ["hello1"] and lateron ["hello2"], it publishs ["hello1"] twice. So I extended the class with a function like "addToPublishQueue($topic, $args, $argsKw=NULL, $options=NULL)" and at the end of the php-script I call the client's publish with iterates through this "PublishQueue" within onSessionStart. That works great, but feels like quick and dirty.

Other workflows?
- I could use the HTTP-Bridge - but I don't want to. This even feels quick and dirty and is another component in this large set of components (php, thruway, crossbar, redis, sql, nginx, etc.)
- Is it possible (or great idea) to publish from the php-script to redis. The Thruway-Client (which is for auth and session-handling and running all the time) reads/subscribes to this redis-channel and on new data it sends a thruway-publish with the data read from redis(-channel)? 
- Does the react-loop help me? I thought, since I am using crossbar, I don't need the react-loop because crossbar doesn't listen to this loop, hence it has its own.
- Or is the solution mentioned above okay?

**I read a lot of topics/issues on this repository. I think, this is a general question and many developers using thruway would appreciate this discussion. Many thanks in advance!**

**Comment by TheMiller2015** [comment]
Hello folks, hello @mbonneau,
I don't want to be nervous, but I'm begging you all for an answer. I'm dealing with websockets for many weeks, trying to learn them in my spare-time. But at this point, I can't help myself, because it's all too new to me.
Thanks and Ratchet/Thruway is a great work, really.

**Comment by mbonneau** [comment]
@TheMiller2015 ,

The "right way" to do it is the way that works for you.

In your situation, If you are trying to add some notifications that publish into your router from a traditional web application, I would use the simplest solution, the HTTP-Bridge.

It is far more complex to start adding redis publish/subscribe or other solutions which will make things more fragile and are not necessary when starting to work with websockets.

**Comment by TheMiller2015** [comment]
Okay, thank you for your answer. So I'll have a closer look at the HTTP-Bridge.

What about my other solution I described in the first post? I wrote a class by extending \Peer\Client which connects to the router and publishs messages while going through a while-loop (because multiple calls at "publish" result in sending the same message again and again)? This a a real quick and dirty solution, isn't it?

Bringing redis to the game is indeed more complex, but isn't it a good solution? Since I'm using redis anyway (to get the session-data within the ws-auth-script) wouldn't it a good idea to make redis work with the ws-client-script that runs all the time with crossbar? I think, I won't use it, but when I would use it, how could I implement redis in the ws-script?

The longer I think about the HTTP-Bridge, the more I like the idea. I'll test it soon.

Thanks.

**Comment by TheMiller2015** [comment]
Hello @mbonneau and all others,

I set up the HTTP-Bridge successfully. But since the connection from the web application to the bridge is done via curl or in my case guzzle, it also implements blocking, when the bridge or ws-router isn't available.

Because of that, could you give me a hint, how to implement redis? As said above, I have a running php-script that handles all auth and session-data for the websockets. It's loaded with crossbar and runs all the time. Is it possible, that this script subscribes to a redis-channel and the web-app publishes to that channel? This script is based on the Client-Object of thruway.

I want to eliminate that blocking from the web-app, when ws-router isn't reachable.

But despite of the possible blocking, the HTTP-Bridge works very well, easy to set up and to use!

Thank you!

**Comment by davidwdan** [comment]
@TheMiller2015 You can make async requests with guzzle:  http://docs.guzzlephp.org/en/latest/faq.html#can-guzzle-send-asynchronous-requests

**Comment by cboden** [comment]
Guzzle's documentation is false; it's not asynchronous. 

It uses curl's sendAsync flag. curl then enters its own event loop sending its requests asynchronously but your code is blocked while it works. So in the scope, curl makes its own async requests, but at the PHP level it blocks so more accurate documentation would be "you can make **parallel** requests with guzzle".

**Comment by TheMiller2015** [comment]
Thanks, then I've another idea. What about periodically testing, if the bridge(-port) is available. If not, writing a variable in mysql oder redis or filesystem. This variable is being read at the startup of any php script which need tonpost to the bridge. If it is not available, no bridge-publish is made. The checker-script may be a cron job, running every x minute or the ws-auth/session script. Idea?
