### ISSUE TITLE
Guzzle 3.x is so deprecated !

### ISSUE THREAD

**Issue by Nek-** [voryx/Thruway#189]
There are no merge anymore ! Even for critical things... https://github.com/guzzle/guzzle3/pull/74#issue-131277533

Time to move, right ?

**Comment by mbonneau** [comment]
Guzzle is a ratchet dependency and will be updated in ratchet's next release (0.4). Expect Thruway to follow quickly behind that.

**Comment by Nek-** [comment]
Erf ok. Workaround:

```json
{
    "require": {
        "voryx/thruway": "dev-ratchet-0.4",
        "cboden/ratchet": "0.4.x-dev"
    }
}
```

But well, it's not awesome. Let's hope they will release 0.4 quickly.

**Comment by Nek-** [comment]
I wrote Woketo. If interested. https://github.com/Nekland/Woketo

**Comment by davidwdan** [comment]
Looks interesting.  Do you have support for compression?

**Comment by Nek-** [comment]
Not yet! It's on my todolist.

**Comment by davidwdan** [comment]
v0.5.0 is out, so this issue has been resolved.
