### ISSUE TITLE
Send initial data on client subscribe and then update it when new data is available

### ISSUE THREAD

**Issue by Kurairaito** [voryx/Thruway#190]
Dear,

I don't get how I can realise my piece of code. the basic idea is when a client subscribe to a topic from autobahn, php server send him some historical data, and when done, an other script publish message when new data is available.

I already have the router with autorizationRules and two Transport Providers on 2 different ports, one for user that cannot publish, and one for server that can publish.
All thoses things works, client cannot create realm, can't publish messages, but can receive those from server.

I don't understand where I can send initial data to client (and only to this client not all connected). I also would not block server during initial data transfert if many client connect at same time (using thread ?)

Can someone help me on that ?

Thanks,
Kurairaito

**Comment by davidwdan** [comment]
Take a look at https://github.com/mbonneau/ThruwayEventHistory

The [example router](https://github.com/mbonneau/ThruwayEventHistory/blob/master/examples/routerWithHistory.php#L14) starts the client as an internal client, if you need to block when getting the history, you can run that client in it's own process, instead of as an internal client.

**Comment by Kurairaito** [comment]
I tried many things but couldn't get it to works properly. I ended by creating a class : 
```
class workerThread extends \Thread {
	public function __construct($i){
		$this->i=$i;
	}
	public function run(){
		for($l_i=0;$l_i<50;$l_i++)
		{
			echo "thread :".$this->i."/".$l_i."\n";
			sleep(1);
		}
	}
}
```
then in EventHistoryClient class I Inserted (in subscribeHistoryHandler)

```
$lastPublicationId = null;
$this->thread = new workerThread($sessionId);
$this->thread->start();
\Thruway\Logging\Logger::info(null, "Thread STARTED");
```

but when I launch three time the file basic, I first get le loop of the first worker for 50 seconds, then the loop for the second worker and finally the third. Nothing is executed in parallel. I don't understand.
If I put an extra

**Comment by RafaelKa** [comment]
Hello, @Kurairaito, please see [Reacts Wiki: About threads](https://github.com/reactphp/react/wiki/FAQ#what-about-threads).
As David described you need own process, not a thread.
