### ISSUE TITLE
lost connection callback/event

### ISSUE THREAD

**Issue by deli6z** [voryx/Thruway#192]
Hello guys. Have a question about whether a router can know when a client's connection is lost / closed?
I need to add some functionality on the server side once browser is closed which indicates ws connection is closed. Thank you

**Comment by deli6z** [comment]
looks like router method onClose is called upon closeConnection - but then the question is how do I execute a callback after this is done?

**Comment by mbonneau** [comment]
You should be able to subscribe to `wamp.metaevent.session.on_leave` to get the information about sessions that are leaving.

**Comment by deli6z** [comment]
Thanks for the help. When I subscribe to that event I get session data and instead of my actual authid which is passed in from the browser I get "authenticated_user" - looks like authid gets set to this value once user is authenticated. Is there a way to know the user id upon onOpen onClose connection ?

**Comment by mbonneau** [comment]
You should be getting back an object that has all of the authentication details plus a bit more: authid, authmethod, authprovider, authrole, authroles, realm, role_features, and session.

The information is generated from here:
https://github.com/voryx/Thruway/blob/06261ca3cd90cc967ab0a9c6d119e21be0cb59dd/src/Thruway/Session.php#L216-L240

**Comment by deli6z** [comment]
looks like auth details are set in onAuthenticateHandler of AuthenticationManager
     if (isset($res[1]) && isset($res[1]->authid)) {
        $session->getAuthenticationDetails()->setAuthId($res[1]->authid);
     }
I assume this part should be executed but it is not since $res[1] in my case is null.
Does this come from processAuthenticate where we return ['SUCCESS'] Seems like I need to return a second array value here so that auth id gets set there and it looks like that second array value should be auth details object.

**Comment by deli6z** [comment]
oh I see now, looks like simple auth does not work with keeping track of authids - that is done in WampCraAuthProvider so I assume I need to use cra auth method

**Comment by mbonneau** [comment]
Other authorization methods can use authids.

Check out: http://voryx.net/using-json-web-token-jwt-for-thruway-authentication/ 

If that doesn't give you some ideas, let me know. You could also share relevant parts of your authentication and I can see if I can help more.

**Comment by deli6z** [comment]
thanks a bunch, I can take it from here.

**Comment by deli6z** [comment]
Sorry need to open it again. Seems like this example does not work https://github.com/voryx/Thruway/blob/f0e26d9637169a7a50ba7707ea080d9c4916fb3d/Examples/MetaEvent/InternalClient.php
in particular with 
        $session->subscribe('wamp.metaevent.session.on_join',  [$this, 'onSessionJoin']);
        $session->subscribe('wamp.metaevent.session.on_leave', [$this, 'onSessionLeave']);
callbacks onSessionJoin and onSessionLeave never get fired. I updated thruway till the 0.4.2 version which I assume is the latest thinking maybe it is not working due to that.
I am testing the case when browser is closing connection.

**Comment by deli6z** [comment]
I should say these are called in Session

$this->getRealm()->publishMeta('wamp.metaevent.session.on_join', [$this->getMetaInfo()]);
$this->getRealm()->publishMeta('wamp.metaevent.session.on_leave', [$this->getMetaInfo()]);

Also these two are added too in onSessionStart of internal client

$session->subscribe('wamp.metaevent.session.on_join',  [$this, 'onSessionJoin']);
$session->subscribe('wamp.metaevent.session.on_leave', [$this, 'onSessionLeave']);

but then subscriptions are not seem to be honored b/c it never gets inside of those callbacks

Maybe this makes it easier to understand what I am talking about. Thank you again.

**Comment by mbonneau** [comment]
Hi @deli6z ,

I have created a simple example at: https://github.com/mbonneau/ThruwayJwtAuthExample

You can test it as is by running `composer install`, firing up the router with `php JwtRouter.php` and running the plunkr at: http://plnkr.co/edit/tXEfeCBrXkMqCjSNPZc6

I have run this and do get the session meta events with the authid.

Let me know if that works for you and if you have other questions.

**Comment by deli6z** [comment]
thank you @mbonneau, now I see what I was missing
$router->addInternalClient(new ClientForSessionMeta('realm1', $router->getLoop()));
I was not explicitly setting realm to a correct value for the internal client with sessions check.
I see in your example you have added two internal clients, one accepts array on realms (in my case I want to support all realms so I just do ['*']) and another one only supports param type string which will be only one realm value apparently. Does it mean I will need to add a separate internal client to track sessions for every realm? (well if I think about it for a little it makes perfect sense b/c every different app is operating under new realm and we don't want mix up all the sessions together).

**Comment by mbonneau** [comment]
Yes - If you need a solution that works on all realms, you would probably look into using a module.

**Comment by deli6z** [comment]
thank you for an example!
