### ISSUE TITLE
Security regarding subscription to topics

### ISSUE THREAD

**Issue by TheMiller2015** [voryx/Thruway#193]
Hello there!

I make extensive use of the websocket-feature and now I have one question regarding the security. Let's say, we focus on a chat-application and a user subscribes to com.myapp.privatemessages.123 (where user-id = 123). The client-lib is autobahn|js, the router is crossbar and everything on the php-side (except server/router) is done via thruway. Is it possible, that a user manipulates the js in that way, that he subscribes to other channels by altering/manipulating the user-id in the topic-name?

To prevent any manipulations, the only way I could think of, was to send a RPC from client to server with the aim, that the server subscribes the session to all topics. So the server could control to which topics a user gets subscribed. But I couldn't handle this. Neither with Thruway, nor with crossbar.io - if someone has any hint, this would be great.

But I don't see other possiblities than the server-side-subscription. Maybe I'm overseeing (does this word exist?) 

Please help me, thanks in advance!

**Comment by mbonneau** [comment]
@TheMiller2015 - Maybe just have the client subscribe to `com.myapp.privatemessages` and then use whitelisting to only send to the specific client.

See: https://github.com/voryx/Thruway/issues/183#issuecomment-213056446
