### ISSUE TITLE
Disconnect issue while using MDWamp client library

### ISSUE THREAD

**Issue by zarv1k** [voryx/Thruway#194]
Can you please help me to determine why I get an assertion error while using Thruway WAMP router with [MDWamp](https://github.com/mogui/MDWamp) client library on disconnect. I even do not understand is this issue related to MDWamp library or Thruway router library. Thats why I created the ticket here and I'll create [the ticket](https://github.com/mogui/MDWamp/issues/46) in MDWamp client repo too. It is also possible that the issue I have experiencing is related with incorrect low level protocol implementation in server-side/client websocket library that Thruway/MDWamp (Ratchet/SocketRocket) uses, but I have no appropriate skills to determine what is wrong in this case.

For explain the issue in simple way I just created the simple iOS app that you can run and start to debug. Here is the [repo](https://github.com/zarv1k/test-mdwamp-thruway) that contains iOS workspace sources, the latest thruway router sources. It also contain crossbar router config.json with same simple router configuration.

When I use thruway router and I call mdwap.disconnect() I got assertion fail error:
`Assertion failed: (mapped_size >= sizeof(_currentReadMaskOffset) + offset), function __33-[SRWebSocket _readFrameContinue]_block_invoke_2, file /Test MDWamp with Thruway Router/Pods/SocketRocket/SocketRocket/SRWebSocket.m, line 1128.`

When I use crossbar router there is no such issue.

However I tried to use both Thruway and Crossbar routers in my web app using 'angular-wamp' library on client side and there are no any issues on disconnect while using either Thruway or Crossbar router.

Thank you.

**Comment by oberstet** [comment]
Might be a WebSocket impementation bug (processing of continuation frames) - Thruway uses Ratchet for WebSocket .. so you might need to move on / dig deeper with this issue. But those are just wild guesses (me, I'm not a Thruway dev!) Another idea: are you using binary serialization WAMP formats (CBOR, MessagePack, UBJSON)? I'm not sure if Ratchet even support binary WebSocket.

@mbonneau Is Ratchet tested using Autobahn WebSocet testsuite?

**Comment by zarv1k** [comment]
@oberstet thank you for quick feedback and your thoughts.
I just checked for supported serializers in Thruway. Only [JsonSerializer](https://github.com/voryx/Thruway/tree/f0e26d9637169a7a50ba7707ea080d9c4916fb3d/src/Thruway/Serializer) implemented.
I have removed the [kMDWampProtocolWamp2msgpack](https://github.com/zarv1k/test-mdwamp-thruway/commit/9509be0a802e070d175f9a1820d91835a8872657) constant from protocolVersions in MDWampTransportWebSocket constructor in my last commit but still but this does not solve the issue.

**Comment by mbonneau** [comment]
Hi @oberstet - Ratchet does use the Autobahn testsuite (thank you by the way - it is great).

Ratchet 0.3 does not support binary, nor does Thruway. The next release of Ratchet (which is pretty close) will have binary support and will allow us to use more serializations with Websockets. As of right now, Thruway only supports raw socket and web socket with JSON serialization.

@zarv1k - I have not used the MDWamp client with Thruway, but if it supports Websockets with JSON serialization it should work. When I have some time I will test this.

**Comment by davidwdan** [comment]
@zarv1k can you provide us with some sample code to reproduce the issue?

**Comment by zarv1k** [comment]
@davidwdan of course. I created the [repo](https://github.com/zarv1k/test-mdwamp-thruway) with sample app specially for reproduce the issue in easy way.

**Comment by davidwdan** [comment]
Ah, I missed that up above. Thank you!

**Comment by mbonneau** [comment]
Hi @zarv1k ,

There is an issue in the current release of Ratchet. I have opened a PR on that branch: https://github.com/ratchetphp/Ratchet/pull/421 .

This issue does not occur in the ratchet-0.4 branch of Thruway.

**Comment by zarv1k** [comment]
@mbonneau, just checked and I confirm that the issue does not occur in the ratchet-0.4 branch of Thruway. Thank you! 
I'm closing this one.

**Comment by oberstet** [comment]
@mbonneau rgd Ratchet being tested using http://autobahn.ws/testsuite/ - mmh. Maybe not? Because the testsuite has multiple tests for closing handshake ..

**Comment by mbonneau** [comment]
@oberstet 

There are some testsuite reports on http://socketo.me/reports/ab/index.html . They are rather old.

You can, however, see in the test comparison on 1.1.1 the difference between the control test (against the testsuite itself) and the test against Ratchet:

http://socketo.me/reports/ab/ratchet_0_3__utf8_case_1_1_1.html
http://socketo.me/reports/ab/autobahntestsuite_0_5_9_case_1_1_1.html

The close frames in the wirelog show that Ratchet was sending the close frame masked, while the control test was sending it unmasked.

If I have some time today, I will see if I can run the tests myself again with the current version of the testsuite.

**Comment by oberstet** [comment]
@mbonneau Thanks! Note that I am mainly asking here, because the testsuite should detect such things of course - and if not, we have a bug in AutobahnTestsuite too. So if you can reproduce using current AutobahnTestsuite, and it fails to mark the test as failed, could you please file and issue on https://github.com/crossbario/autobahn-testsuite/issues ? Thanks! (Not that I would like find time soon, but ..)

**Comment by mbonneau** [comment]
@oberstet - I just tested against Autobahn Version 0.7.5 / Autobahn Testsuite Version 0.10.9 and the Testsuite correctly failed the test when Ratchet sent back a masked close frame.

With the newer version of Ratchet, the Websocket protocol was broken out into a separate library. That library is configured with travis to automatically run the Autobahn Testsuite and fail if the Testsuite fails any tests.

**Comment by oberstet** [comment]
@mbonneau thanks for checking!

**Comment by cboden** [comment]
Nice work @mbonneau!

**Comment by ktamas77** [comment]
we're having the same issue
- Thruway server works perfectly with Autobahn clients
- MDWamp clients disconnects immediately. Cannot make it work.
Please advise.
