### ISSUE TITLE
Cannot authenticate using wampcra

### ISSUE THREAD

**Issue by cristiano-di-buduo** [voryx/Thruway#197]
I am trying to enable authentication using wampcra. I changed the password encryption method on my site from bcrypt to this:

        AppBundle\Entity\User:
            algorithm: pbkdf2
            hash_algorithm: sha256
            encode_as_base64: true
            iterations: 1000
            key_length: 32

But WampCraAuthProvider is generating a token that differs from the one autobahn is sending in processAuthenticate, resulting in FAILURE and the user not being granted access.

My autobahn code looks like this:

    function onchallenge(session, method, extra) {
       if(method === "wampcra") {
           var k = key;
           if(typeof extra.salt !== 'undefined') {
                k = autobahn.auth_cra.derive_key(key, extra.salt);
           }
           blah = autobahn.auth_cra.sign(k, extra.challenge);
           return blah;
       } else {
           return null;
       }
    }

I'm not using salt in the generation of the passwords, and the derive_key call is effectively not being called.

What could I be doing wrong?

**Comment by davidwdan** [comment]
@cristiano-di-buduo did the user exist before you changed the encryption method?

**Comment by cristiano-di-buduo** [comment]
Yes. I just generated a new password with Symfony's encode-password command.

**Comment by cristiano-di-buduo** [comment]
Also, I see that autobahn is generating a different signature every time. Is this normal?

**Comment by cristiano-di-buduo** [comment]
I'm sorry for having disturbed you, this seems indeed to be the case. I don't recall reading about this in any doc, and everyone is considering storing encrypted passwords best practice, so I thought this just would be assumed when writing the how-to. It now works like a charm, thanks!

**Comment by mbonneau** [comment]
@cristiano-di-buduo - Thanks for updating the issue.

**Comment by oberstet** [comment]
>  I see that autobahn is generating a different signature every time

The reason is: the challenge contains some randomized stuff. This is to prevent replay attacks.
