### ISSUE TITLE
Default client example not working.

### ISSUE THREAD

**Issue by WesleyChannon** [voryx/Thruway#201]
Hi there!

When I try to use the default client example found on your GitHub page (https://github.com/voryx/Thruway), I get the following error:

PHP Catchable fatal error:  Argument 1 passed to Ratchet\Client\Factory::Ratchet\Client\{closure}() must be an instance of React\Stream\DuplexStreamInterface, instance of React\Stream\Stream given, called in /home/zairc/triviabot-dev/vendor/react/promise/src/FulfilledPromise.php on line 25 and defined in /home/zairc/triviabot-dev/vendor/ratchet/pawl/src/Factory.php on line 48

I'm using PHP 5.5.9 on an Ubuntu 14.04 system.  I used Composer (as per instructions) to install Thruway.

Please advise.

**Comment by davidwdan** [comment]
@WesleyChannon Can you share your composer.lock file?

**Comment by WesleyChannon** [comment]
Appears as if I had an older install that was conflicting somehow. Deleted the entire install, and started from scratch. Resolved the issue.
