### ISSUE TITLE
Session onClose fired after router forgets session

### ISSUE THREAD

**Issue by mmelvin0** [voryx/Thruway#205]
This has the side effect that you can't access the session object via the router when handling session leave (`wamp.metaevent.session.on_leave`), although you are passed the session ID.

I can always save a reference to session object myself to work around this, but I was wondering if this is done on purpose for a reason I'm missing or if it would be a reasonable PR to swap the order of things on `Router->handleConnectionClose()`.

Not at all critical, just trying to better understand Thruway.

Link to what I'm talking about: https://github.com/voryx/Thruway/blob/ec93e008966467ffe3ffb67b8eea47137a809c39/src/Thruway/Peer/Router.php#L93

**Comment by mbonneau** [comment]
If you need to be accessing the Session inside the router consider using a realm or router module to access the `connection_close` event instead of subscribing to the meta event from a client.

**Comment by mmelvin0** [comment]
It seems `connection_close` is exactly what I was missing. In my router module's `onSessionStart` I did this:

```
$this->router->getEventDispatcher()->addListener('connection_close', [$this, 'onConnectionClose']);
```

Thank you for the awesome library and the quick reply.
