### ISSUE TITLE
Authentication failure after running for a long time

### ISSUE THREAD

**Issue by mindr242** [voryx/Thruway#207]
When thruway has been running for a long time, authentication stops working, and I get the output below:

`[Thruway\Authentication\AuthenticationManager 21241] Client onMessage: thruway.auth.apikey.onauthenticate.error
2016-08-03T18:30:30.2103200 error      [Thruway\Authentication\AuthenticationManager 21241] onauthenticate rejected the promise
2016-08-03T18:30:30.2107940 debug      [Thruway\Realm 21241] Leaving realm pos
2016-08-03T18:30:30.2111390 info       [Thruway\Transport\RatchetTransportProvider 21241] Ratchet has closed
`

I know that it might be some limitation on my system, perhaps MySQL is timing out or PHP session is ending, the main problem is that I can't see the error, all I get is the output above!

How can I tell Thruway to log all errors and where should they be logged?

**Comment by mbonneau** [comment]
Can you provide additional information?

If there is an exception in an RPC, Thruway will use that exception to reject the promise so you would not see that information there.

Are you using a MySQL data source in the same process as the router?

**Comment by mindr242** [comment]
Yes, I am using Yii2 Framwork and authenticating the client via an access_token created by Yii2.

My Auth provider client is as follows:

`public function processAuthenticate($signature, $extra = null) {
        if ($this->authenticate($signature)) {
            return ["SUCCESS"];
        } else {
            return ["FAILURE"];
        }
    }

    public function authenticate($token) {
        Yii::$app->db->open();
        if ($user = User::findIdentityByAccessToken($token)) {
            return true;
        }
        return false;
    }`

The problem is occurring on this line: `$user = User::findIdentityByAccessToken($token`

However, as you said, Thruway is using the exception to reject the promise and I can't see the error so I can fix it. 

Is there a way I can see the exceptions?

In addition, I have this line ` Yii::$app->db->open();` which makes sure that the DB connection is open in case it timed out. So the problem might be cause by something else, maybe Yii2 uses session variables that have expired or something similar.

**Comment by mbonneau** [comment]
You can wrap the `$user = User::findIdentityByAccessToken($token)` in a try catch block and use `Logger` to output the error:
```php
try {
    $user = User::findIdentityByAccessToken($token);
} catch (Exception $e) {
    Logger::error($this, $e->getMessage());
    throw $e;
}
```

As far as the database connections, I have seen issues where MySQL has an absolute connection timeout. I am not familiar enough with Yii2 to know how to handle that.

**Comment by mindr242** [comment]
I tried the code below:
        try {
            $user = User::findIdentityByAccessToken($token);
        } catch (Exception $e) {
            echo 'EXCEPTION!!! \n';
            echo 'Caught exception: ' . json_encode($e->getMessage()) . "\n";
        }

I got the same output as before:
`
2016-08-05T15:57:06.6677530 debug      [Thruway\Authentication\AuthenticationManager 13616] Client onMessage: thruway.auth.apikey.onauthenticate.error
2016-08-05T15:57:06.6687190 error      [Thruway\Authentication\AuthenticationManager 13616] onauthenticate rejected the promise
2016-08-05T15:57:06.6692650 debug      [Thruway\Realm 13616] Leaving realm pos
2016-08-05T15:57:06.6702700 info       [Thruway\Transport\RatchetTransportProvider 13616] Ratchet has closed
`

Even the 'EXCEPTION!!! \n' string can't be found in the output.

It doesn't seem like the exception can be caught and handled with a try-catch block.

Any ideas?

**Comment by davidwdan** [comment]
Take a look at https://github.com/voryx/Thruway/issues/168

you can return a failure from your catch in the authentication provider

**Comment by mindr242** [comment]
@davidwdan, I want to see the actual error message in order to fix this. Will this help me see the error message? What should I change with the code above to be able to see the error message? Thanks!

**Comment by mindr242** [comment]
@davidwdan , I have tried something like this:

```php
public function processAuthenticate($signature, $extra = null)
{

    try {
        if ($this->authenticate($signature)) {
            return ["SUCCESS"];
        } else {
            return ["FAILURE"];
        }
    } catch (Exception $e) {
        return [
            "FAILURE",
            [
                "abort_uri" => "my.custom.abort.uri",
                "details"   => ["message" => $e->getMessage()]
            ]
        ];
    }

}

public function authenticate($token)
{
    Yii::$app->db->open();
    if ($user = User::findIdentityByAccessToken($token)) {
        return true;
    }
    return false;
}
```

It doesn't actually work. Still the same output. 

Thruway does not allow catching of the error, it just aborts with a general error message like so:

```
2016-08-05T15:57:06.6677530 debug      [Thruway\Authentication\AuthenticationManager 13616] Client onMessage: thruway.auth.apikey.onauthenticate.error
2016-08-05T15:57:06.6687190 error      [Thruway\Authentication\AuthenticationManager 13616] onauthenticate rejected the promise
2016-08-05T15:57:06.6692650 debug      [Thruway\Realm 13616] Leaving realm pos
2016-08-05T15:57:06.6702700 info       [Thruway\Transport\RatchetTransportProvider 13616] Ratchet has closed
```

**Comment by mbonneau** [comment]
@mindr242 - Are you still experiencing this issue?
