### ISSUE TITLE
Publish dev/master to stable

### ISSUE THREAD

**Issue by saidmoya12** [voryx/Thruway#209]
Current dev/master work with symfony3 but the latest 0.4.2 no.

Some dependencies like voryx/ThruwayBundle use by default 0.4 

Please publish a new stable version as possible

**Comment by davidwdan** [comment]
Thanks for opening this issue.  We're not quite ready to tag a new release.

If you need to use dev-master with the ThruwayBundle, you can require it in your project.

**Comment by RafaelKa** [comment]
@saidmoya12: just use following in your root composer.json

```
"voryx/thruway": "dev-master#1fddead1dd00fda074a05c55baa70c1dd5b60859 as 0.5.0"
```

and require 0.5.0 in your composer package for your symfony 3 bundle
