### ISSUE TITLE
Question: Is long polling supported by Thruway?

### ISSUE THREAD

**Issue by dis2ro** [voryx/Thruway#213]
Hi Guys,

I am trying to create a real time notification using Thruway and ZMQ. see below code

   $loop   = React\EventLoop\Factory::create();
    $pusher = new \Thruway\Peer\Client("realm1", $loop);

    $pusher->on('open', function ($session) use ($loop) {
        $context = new React\ZMQ\Context($loop);
        $pull    = $context->getSocket(ZMQ::SOCKET_PULL);
        $pull->bind('tcp://[IP]:5555');

        $pull->on('message', function ($entry) use ($session) {
            $entryData = json_decode($entry, true);
            if (isset($entryData['category'])) {
                $session->publish($entryData['category'], [$entryData]);
            }
        });
    });

    $router = new Thruway\Peer\Router($loop);
    $router->addInternalClient($pusher);
    $router->addTransportProvider(new Thruway\Transport\RatchetTransportProvider("0.0.0.0", 8080));
    $router->start();

It is located on Server A

When i tried to connect to Thruway using Autobahn JS and transport as websocket which is located on the Server B, it's working,
but when i tried to use longpoll i'm recieving an error of "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://local.app1.dev' is therefore not allowed access. The response had HTTP status code 400."

I also tried using socket.io to connect but it doesn't work as well, XHR cross-origin issue.

 I tried different solution that i found, but unfortunately it doesn't work for me. can someone help me please?

Thanks

**Comment by mbonneau** [comment]
Thruway does not support long polling.

If you do need to access a Thruway router using HTTP, please see: https://github.com/voryx/WampPost

While this allows you some access to the router, this is still not long-polling and may also suffer from the [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) issues you are having.

**Comment by dis2ro** [comment]
Is WampPost gonna work on older browser that doesn't support websocket as a fallback?

**Comment by mbonneau** [comment]
WampPost is not a substitute for long polling.
