### ISSUE TITLE
Send incoming message to clients not working?

### ISSUE THREAD

**Issue by Tklaversma** [voryx/Thruway#214]
Hi,

Before I explain my problem, let me explain my setup / goal.

1. A server (in my example I'm just using [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop)) sends a response to my website, for example `example.com`.
2. The website `example.com` catches that response (`$_POST`-variables).
3. `example.com` than connects to the already running "Wamp2 Thruway" server and sends the `$_POST`-variables.
4. The server then notifies his clients by using `$pull->on('message', ...`
5. The clients have an open websocket to the server with AutobahnJS and they receive the message.
6. The clients who use ReactJS, update their DOM with the new info.

Ok, so here comes the problem:

The website `example.com` catches that incoming request and tries to send it to the already running  "Wamp2 Thruway" server. But this somehow fails...

```php
<?php

// This is the website example.com

try {
    $context = new \ZMQContext();
    $socket  = $context->getSocket(\ZMQ::SOCKET_PUSH, 'thisIsMyPusher');
    $socket->connect('tcp://127.0.0.1:5555');
    $socket->send(json_encode($_POST));
    sleep(3);
}
catch (\ZMQSocketException $e) {
    echo "An error occured\n";
    echo "{$e->getMessage()}\n";
}
```

So, you see I just use `send()`, but on the server-side nothing happens.

```php
<?php

use React\EventLoop\Factory;
use React\ZMQ\Context;
use Thruway\Logging\Logger;
use Thruway\Peer\Client;
use Thruway\Peer\Router;
use Thruway\Transport\RatchetTransportProvider;

require_once(realpath(__DIR__ . '/../vendor/autoload.php'));

$loop   = Factory::create();
$pusher = new Client('myCallboard', $loop);

$pusher->on('open', function ($session) use ($loop) {
    $context = new Context($loop);
    $pull    = $context->getSocket(\ZMQ::SOCKET_PULL);
    $pull->bind('tcp://127.0.0.1:5555');

    // Handle incoming messages
    $pull->on('message', function ($entry) use ($session) {

        Logger::info('Incoming message...');
        echo $entry;
        Logger::info($entry);

        // NOTHING GETS LOGGED, PRINTED, ECHOED, WHATSOEVER...

        $entryData = json_decode($entry, true);
        if (isset($entryData['category'])) {
            $session->publish($entryData['category'], [$entryData]);
            // ALSO ON THE SERVER SIDE NOTHING GETS RECEIVED
        }
    });
});

$router = new Router($loop);
$router->addInternalClient($pusher);
$router->addTransportProvider(new RatchetTransportProvider('0.0.0.0', 59123));
$router->start();
```

Am I doing something wrong, can it be that port 5555 needs to be opened, although its all "local", is it something else?

I hope you guys can help me out.

Thanks in advance!

Regards,
TK

**Comment by mbonneau** [comment]
I don't have zmq in my current setup to help test what your issue is, but you may want to take a look at [WampPost](https://github.com/voryx/WampPost) which will let you publish or call into the router from your synchronous PHP code like this:
```php
        $body = [
            "topic" => 'my.topic',
            "args" => ['arg1', 'arg2']
        ];
        $context = stream_context_create([
            'http' => [
                'method' => "POST",
                'header' => "Content-type: application/json\r\n",
                'content' => json_encode($body)
            ]
        ]);

        file_get_contents('http://127.0.0.1:8181/', null, $context);
```

**Comment by Tklaversma** [comment]
@mbonneau I understand what you are saying and if it works, it's a nice workaround, but I prefer using ZeroMQ.

The current setup I'm using is just as subscribed by @davidwdan [here](https://github.com/voryx/Thruway/issues/96#issuecomment-98416776)....so don't understand why this is not working :(

**Comment by Tklaversma** [comment]
Ok, so your gonna laugh real hard now. For some reason the the `extension=zmq.so` was not loaded....just checked with `phpinfo()`. Eventually needed to use the whole path, like so:
`extension=/usr/lib64/php/modules/zmq.so`.

Anyways, your reaction is much appreciated!
