### ISSUE TITLE
Keep router open, always?!

### ISSUE THREAD

**Issue by Tklaversma** [voryx/Thruway#216]
Hi,

I've got the following php file running as a daemon on my Linux CentOS 7 server....meaning the router loop starts when I call `systemctl start my.service`. This basically just executes my script:

```
<?php

use React\EventLoop\Factory;
use React\ZMQ\Context;
use Thruway\Logging\Logger;
use Thruway\Peer\Client;
use Thruway\Peer\Router;
use Thruway\Transport\RatchetTransportProvider;

require_once(realpath(__DIR__ . '/../vendor/autoload.php'));

set_time_limit(0);

$loop   = Factory::create();
$pusher = new Client('myCallboard', $loop);

$pusher->on('open', function ($session) use ($loop) {
    $context = new Context($loop);
    $pull    = $context->getSocket(\ZMQ::SOCKET_PULL);
    $pull->bind('tcp://127.0.0.1:5555');

    // Handle incoming data
    $pull->on('message', function ($entry) use ($session) {
        Logger::log(null, 1, 'Incoming message: ' . $entry);

        // Send data to subscribed clients
        $entryData = json_decode($entry, true);
        if (isset($entryData['category'])) {
            $session->publish($entryData['category'], [$entryData]);
        }
    });
});

$router = new Router($loop);
$router->addInternalClient($pusher);
$router->addTransportProvider(new RatchetTransportProvider('0.0.0.0', 59123));
$router->start();
```

The problem is that after 10 minutes or so, the router is closed by itself `...Leaving realm...`

Is there a way to always keep the router loop open for incoming requests? Or is this bad practise, and if so why?

I just basically want the router loop to be always open, since any time of the day a request can be incoming and the server needs to push this to the clients..

Hope anyone can help me out!

Regards,
TK

**Comment by leda-ferreira** [comment]
"Leaving realm" means that one of the peers has closed it's connection to the router, not that the router itself has stoped.

**Comment by Tklaversma** [comment]
@leda-ferreira Thanks, didn't know that. But than there is another reason why I couldn't connect to the server (router) anymore. But are you aso indirectly saying the router never closes itself?

**Comment by leda-ferreira** [comment]
I have a few routers running for almost one year and they never run into any error that caused them to stop. Under normal circunstances, they will only stop if they receive a SIGHUP or SIGKILL.

**Comment by mbonneau** [comment]
@Tklaversma - I am closing this issue. If you are still having issues, please feel free to comment and we can reopen it.
