### ISSUE TITLE
Xdebug

### ISSUE THREAD

**Issue by inovamatic** [voryx/Thruway#217]
Hello,

We use thruway as a guest for crossbar router with a lot of success. Congrats on the project.
Just tried to pass an argument for the executable so it load a special .ini file with xdebug enabled but ir seems that the guest worker do not like my custom ini or just ignores it
.
Anyone tried to use xdebug with success with a guest worker in php?

Thanks

**Comment by mbonneau** [comment]
You could try debugging it standalone if what you are trying to debug does not have to do with it running as a guest worker.

I regularly debug clients with xdebug - so that shouldn't be a problem.

**Comment by inovamatic** [comment]
Thanks for the quick reply mbonneau,

If i load the php directly from the command line xdebug works as it should.

php -c my.ini authenticator.php

By standalone do you mean loading crossbar from a json file? Thats exactly what i am doing but it seems that maybe i am not passing the arguments for php executable correctly. This is the specific guest worker part:

     }, {
        "type": "guest",
        "executable": "php",
        "arguments": [
            "-c my.ini",
            "../authenticator.php",
            "ws://127.0.0.1:9000",
            "blabla",
            "blablabla",
            "blablablabla"
        ]
    }, {

**Comment by mbonneau** [comment]
I am suggesting that while you are testing, it may be easier to not run the Thruway client as a guest but as a standalone process. Start crossbar without the worker and run your client from a separate terminal.

**Comment by inovamatic** [comment]
Thanks so much. It works perfectly. I was trying tto create a wamp router in thruway instead of crossbar but your idea seems easier. I am gonna slap myself a bit for not thinking in that before.
