### ISSUE TITLE
Send to only one session ID subscribed by many.

### ISSUE THREAD

**Issue by WesleyChannon** [voryx/Thruway#218]
Hi there!

Is there a way to only publish to one specific client session ID, where there are many client sessions subscribed to it?

I know the session ID of the connection I'd like to publish to.  I'm currently doing the following:

...
$title = "Test";
$session_id = "8589785857326457";
$session->publish('update', array('page_title',$title), [], ['eligible' => $session_id]);
...

I'm subscribing to 'update' on the client side.

Is there something I'm doing wrong?

**Comment by davidwdan** [comment]
@WesleyChannon  `eligible` takes an array of session ids.  ie:

```php 
$session->publish('update', ['page_title',$title], [], ['eligible' => [$session_id]]);
```

**Comment by WesleyChannon** [comment]
Worked like a charm! Thank you @davidwdan!
