### ISSUE TITLE
/vendor/autoload.php not found

### ISSUE THREAD

**Issue by ParVisual** [voryx/Thruway#223]
Hi, I dowloaded Thruway-master.zip, I extracted it.
I uploaded all files to my server.
When I try to run the test files, bootstrap.php for instance, Thruway not work because it's trying to load a "/vendor/autoload.php" file that is not in the distribution package.

What should I do in this case?
Thanks.
![thruway](https://cloud.githubusercontent.com/assets/19213467/20766801/9b47a4e0-b716-11e6-9ecc-4acd9844c981.png)

**Comment by RafaelKa** [comment]
@ParVisual please read https://github.com/voryx/Thruway#quick-start-with-composer

You want [Composer](https://getcomposer.org/) everywhere on PHP today!

Maybe a better start for you could [voryx/ThruwayBundle](https://github.com/voryx/ThruwayBundle), but voryx/Thruway works standalone as well!

**Comment by ParVisual** [comment]
Ok, I got it!
I had no idea what it was "Composer". I installed it and I'll it again.
Thanks.
