### ISSUE TITLE
Basic question about websocket server

### ISSUE THREAD

**Issue by ParVisual** [voryx/Thruway#224]
Hi, I downloaded all the examples to my computer, and then uploaded it to my server. To a location like: 

> http://mi-site.com/thruway/vendor/voryx/thruway/Examples/

Then I executed the SimpleWsRouter.php in my browser, and this success result appeared on screen: 

> 2016-12-01T11:20:19.0244840 notice Changing PHP precision from 14 to 16 2016-12-01T11:20:19.0264810 debug [Thruway\Peer\Router 25613] New router created 2016-12-01T11:20:19.0275480 info [Thruway\Peer\Router 25613] Starting router

My question is if that are all the steps to do, in order to open the websocket. And if after run the SimpleWsRouter.php the socket is available to communicate my apps in real time.

Thanks!

**Comment by davidwdan** [comment]
You need to run the router from the CLI not the browser.

**Comment by ParVisual** [comment]
Ok, so I should execute from the CLI something like this?

> $ php http://mi-site.com/thruway/vendor/voryx/thruway/Examples/SimpleWsRouter.php

And the websocket would be constantly available to access?

Thanks.

**Comment by davidwdan** [comment]
You would start it like this, but with your local path:
```BASH
$ php /var/www/thruway/vendor/thruway/Examples/SimpleWsRouter.php
```

By default the web socket is limited to 127.0.0.1, so you'll only be able to access it on that server running the router.  To open it up, you'll need to change this line in `SimpleWsRouter.php`
```PHP
$transportProvider = new RatchetTransportProvider("127.0.0.1", 9090);
```
to 
```PHP
$transportProvider = new RatchetTransportProvider("0.0.0.0", 9090);
```

In order to access the websocket from a browser, you'll need to use a js library like [Autobahn](http://autobahn.ws/js/).

**Comment by ParVisual** [comment]
I get it running locally now. My question is how can I access to the websocket remotely, as in this example: 

> wss://demo.crossbar.io

**Comment by davidwdan** [comment]
Replace `wss://demo.crossbar.io`, with the ip of your server.

I'm going to close this issue, since it's not an issue with Thruway.

**Comment by ParVisual** [comment]
Ok, thanks David.
