### ISSUE TITLE
[QUESTION] Does Thruway support PHP7 or not?

### ISSUE THREAD

**Issue by Yurist-85** [voryx/Thruway#227]
Does Thruway support PHP7 or not?
Can't find any word about it in poor documentation.

**Comment by davidwdan** [comment]
From the poor documentation:

`Thruway is only supported on PHP 5.4 and up.`

"5.4 and up" includes PHP 7.x

Also: https://travis-ci.org/voryx/Thruway

Pull requests are always welcome to improve the documentation.
