### ISSUE TITLE
AuthorizationManagerInterface is missing

### ISSUE THREAD

**Issue by RafaelKa** [voryx/Thruway#228]
Hello folks,

mentioned in ThruwayBundle and in tests `\Thruway\Authentication\AuthorizationManagerInterface` is missing. 
Was it removed?

**Comment by mbonneau** [comment]
This looks like it was dropped in the current branch (which is the 0.4 branch).

**Comment by mbonneau** [comment]
This was resolved here: https://github.com/voryx/ThruwayBundle/pull/33
