### ISSUE TITLE
Warning: Ambiguous class resolution, "Thruway\Common\Utils"

### ISSUE THREAD

**Issue by tacman** [voryx/Thruway#229]
I get this warning when clearing the cache (Symfony 3.2)

Generating optimized autoload files
Warning: Ambiguous class resolution, "Thruway\Common\Utils" was found in both "/var/www/Posse/vendor/voryx/thruway-message/src/Common/Utils.php" and "/var/www/Posse/vendor/voryx/thruway/src/Thruway/Common/Utils.php", the first will be used.
ocramius/pa

**Comment by mbonneau** [comment]
@davidwdan Did you fix this issue?

**Comment by mbonneau** [comment]
This issue is resolved in development branches.
