### ISSUE TITLE
Store specific data for each connected client

### ISSUE THREAD

**Issue by tsdevelopment** [voryx/Thruway#230]
Is it possible to store user specific data anywhere after the client has been authenticated successfully? I have my own authenticationProvider and authenticate the user via jwt and get their data from a database. I need the user specific ID in my registered procedures. Is that possible? Is there any example?

**Comment by mbonneau** [comment]
There is a Thruway specific feature that allows the authentication provider to store extra information with a session when it is authenticated. Unfortunately, I have no examples at the moment except for the unit tests here:

https://github.com/voryx/Thruway/blob/master/tests/WAMP/AuthExtraTest.php#L37

Once this is set, the router will send this information in the `details` as `_thruway_authextra` if `caller_id` or `publisher_id` are requested. It would be good to keep the information here very small.

**Comment by vasartam** [comment]
This one helped a lot. Thank you very much.
