### ISSUE TITLE
issue with local domains on latest stable version

### ISSUE THREAD

**Issue by paranic** [voryx/Thruway#239]
currently the latest stable version that composer installs is 0.4.2 witch depends on ratchet/pawl 0.1.*
but pawl 0.1.2 uses google's dns resolver witch of course cannot resolve local domains.

https://github.com/ratchetphp/Pawl/blob/v0.1.2/src/Factory.php#L32

this means that the latest stable version is not working on local domains
you have to either use ip address for the connection details instead of myserver.local
or install dev-master or 0.4.x-dev in order to work with local domains

**Comment by mbonneau** [comment]
@paranic - I am currently refactoring and separating out the components of Thruway so that we can possibly get a new release out. As it is right now, the dependencies are not at stable releases so we are blocked.

**Comment by davidwdan** [comment]
v0.5.0 has been released, which resolves this issue.
