### ISSUE TITLE
php WAMP2 Server example

### ISSUE THREAD

**Issue by mhf-ir** [voryx/Thruway#240]
I cant find any example like [WAMP1](http://socketo.me/docs/wamp#usage) example in this repository?
Is support for wamp2 server ?

**Comment by oanhnn** [comment]
You can see more example about WAPP2 in here `https://github.com/voryx/Thruway/tree/master/Examples`

**Comment by JFOC** [comment]
I am second to this, cannot find an example for building WAMP2 Server. If anyone has references

**Comment by mbonneau** [comment]
The WAMP2 architecture does not have "servers" per-se; it has Routers and Clients.

The router is responsible for routing RPC calls and responses and for handling subscriptions and publications.

Typical applications would have different client with different responsibilities. In my experience, I usually have front-end clients (like a web browser) and back-end clients (a php process that is publishing and servicing RPC invocations, e.g., database queries).

How these responsibilities are divided is really up to the user as all peers act as equals.

As for the original question, the simplest router can be found here: https://github.com/voryx/Thruway/blob/master/Examples/SimpleWsRouter.php

This router is an open router that will allow RPCs and publish/subscribe from any client.
