### ISSUE TITLE
Dynamic Authorization Client

### ISSUE THREAD

**Issue by zarv1k** [voryx/Thruway#244]
Hi guys!
In my app I want to use dynamic authorization. I want to store authrules in DB because they can be changed.
At the moment there is AuthenticationManager as synchronous router module. I think it is bad idea just override AuthenticationManager class and make DB queries in it because it is bad for router performance. Router should not be related to any storage requests that can slow down router's performance. Instead I want to delegate authorization process to another client, that will register special procedure (e.g. com.example.authorize) and use it for check permissions. In this case I can start many workers (multiregister) that will be able to check permissions.

Can you please help me with that? How can I implement such dynamic auth manager router that will work asynchronously?
Thank you.

**Comment by mbonneau** [comment]
Instead of overriding the `AuthenticationManager`, you should use the `AbstractAuthProviderClient` which can be run just like a regular client and will allow you to move the authentication out of the router process. Just add a `PawlTransportProvider` to it and run it. It connects to the `thruway.auth` realm (which requires a trusted transport) and communicates through regular RPCs.

There are some examples of its use in the Examples directory. Let me know if you have any other questions.

**Comment by zarv1k** [comment]
Oh, my bad. I mean AuthorizationManager, not AuthenticationManager. Is the answer the same for AuthorizationManager? 

I haven't found an example for AuthorizationManager in repo yet.

**Comment by mbonneau** [comment]
Yes, Authorization can also be done via RPC calls, but not "on demand" (you have to setup rules).

For fine control of authorization rules, I sometimes implement them in the RPC itself and examine the authorization info sent in the details.

This information is not quite complete. Let me know if it works for you: https://github.com/voryx/Thruway/wiki/Authorization

**Comment by zarv1k** [comment]
@mbonneau, thanks for quick response.

> Yes, Authorization can also be done via RPC calls, but not "on demand" (you have to setup rules).

How can I implement it on demand? I want to manage authorization rules on fly in DB. AuthorizationManager checks auth by method isAuthorizedTo() and if not authorized, then [stopPropagation()](https://github.com/voryx/Thruway/blob/master/src/Thruway/Authentication/AuthorizationManager.php#L91) called. 
Is it possible at all to stop bubbling of this event after some acync operation (like RPC call)?

**Comment by zarv1k** [comment]
In other words I need exactly same thing like [dynamic authorization](http://crossbar.io/docs/Authorization/#dynamic-authorization) in crossbar router using thruway router.

**Comment by mbonneau** [comment]
Yes - but is not in Thruway. The architecture is flexible that it could be implemented, but I have not had the need or the time yet to do so.

**Comment by mbonneau** [comment]
@zarv1k - I am closing this issue. Please let me know if you have any other questions or would like to reopen this.

**Comment by zarv1k** [comment]
@mbonneau have no questions at the moment. I migrated to crossbar.io router but still use Thruway as client library. Thank you.
