### ISSUE TITLE
wss support with SecureServer

### ISSUE THREAD

**Issue by Gemorroj** [voryx/Thruway#250]
see https://github.com/ratchetphp/Ratchet/commit/369227dc1c0e5e016e729d8ab4789a0fd0ba85e4
Is it possible to make support for `wss` protocol with [SecureServer](https://github.com/reactphp/socket#secureserver)?

**Comment by davidwdan** [comment]
We have no plans to add direct wss support to the router at this time.  Consider using [nginx](https://github.com/voryx/Thruway/issues/66#issuecomment-114301685) or another proxy instead.
