### ISSUE TITLE
Get authid of RPC caller?

### ISSUE THREAD

**Issue by StagasaurusRex** [voryx/Thruway#251]
I would like to create an internal client that registers a bunch of functions for remote clients to call.

The problem I'm having is I don't see a way to get the authid of the caller. Is this possible?

**Comment by davidwdan** [comment]
@StagasaurusRex when you register the rpc, set the option `disclose_caller` to `true` and the `authid` will be sent with each invocation:

```PHP
$session->register('com.myapp.add2', function ($args, $argKw, $details) {
    // $details will be an object that contains caller, authid, etc. properties
}, ['disclose_caller' => true])
```

**Comment by StagasaurusRex** [comment]
Thanks for your quick reply! I will try that.

**Comment by cyprus1spirit** [comment]
authid is always anonymous. Somebody knows why?

**Comment by StagasaurusRex** [comment]
I'm using this method successfully. I'm registering functions w/
`$session->register('com.companyname.read', [$this, 'readReceipt'], ['disclose_caller' => true]);`

and in my function I can access authid like so
```
    public function readReceipt($jsonArgs, $argKw, $details)
    {
        $args = json_decode($jsonArgs[0], true);
        $authId = $args['authId'];
    }
```

If that doesn't work for you i'm not sure i can help.

**Comment by cyprus1spirit** [comment]
Thank you. No it does not work. I get anonymous.
