### ISSUE TITLE
problem with listener priority

### ISSUE THREAD

**Issue by vcordes79** [voryx/Thruway#256]
Hi,

I noticed that after adding Authentication the client was not able to invoke rpc calls. I started debugging the issue and realized that the welcome message returned by thruway did not include the dealer role. When I dug deeper, I found that during the SendWelcomeMessageEvent the session listener was executed before the dealer and realm listener. Shouldn't the session listener always be called last because the message get's send over the transport there - or am I missing something?

Changing the listener priority to 1 in Session.php fixed the issue for me.

Thanks,
Volker

**Comment by mbonneau** [comment]
Hi @vcordes79  - I am not sure I understand what the issue is - do you have an example that reproduces this?

**Comment by vcordes79** [comment]
Okay, I'll try: I'm using Wampy as a client with a thruway router and have implemented authentication. The welcome message sent back back by thruway is this: 

`{ 
  authid: "...",
  authrole: "authenticated_user",
  authroles: [ "authenticated_user" ],
  roles: {
    broker: {
      features: {
        publisher_exclusion: true, 
        subscriber_blackwhite_listing: true,
        subscriber_metaevents: true
}}}}`

As you can see, the dealer role is missing. The is added to the list in Dealer.php (handleSendWelcomeMessage) which is added to the listeners with the following line:

`"SendWelcomeMessageEvent" => ["handleSendWelcomeMessage", 10]`

In Session.php there is also a listener for this event:

`"SendWelcomeMessageEvent"      => ["handleSendMessage", 10]`

As you can see both listeners have the same priority set. So the order of execution is not deterministic. In my case the Session handler was executed before the Dealer handler. The Session handler in the end executes this code:

`$this->sendMessageToTransport($event->message);`

So the message is transmitted before the dealer features are added...

Volker

**Comment by mbonneau** [comment]
@vcordes79 - you are correct - I don't see the dealer features being sent with the welcome message. This does need to be corrected.

**Comment by mbonneau** [comment]
@vcordes79 - This issue should be resolved with #258 and #260 and has also been pushed to the 0.5 branch. Please let me know if this fixes it for you.

**Comment by vcordes79** [comment]
This fixes the issue for me. Thank you
