### ISSUE TITLE
How to add sender / time

### ISSUE THREAD

**Issue by vcordes79** [voryx/Thruway#261]
Hello,

I'm developing a simple chat application and was wondering how to identify who sent / published a message and the message time (at the receiving side). I could just add it to the message when it is send, but then I couldn't verify the sender / time. So I was thinking about implementing a RealmModule to intercept the message and add the current time and the authid from the senders session data. Is this the way to go? Or should I publish on a separate channel or not use publish at all and connect to my existing application? The application / Internal client could then publish a new message with complete sender information.

My existing layout is like this:
When the user logs I subscribe to topics like chat.username and chat.group1 ... chat.groupn for groupchats. When the user writes a message it is published on the topic chat.<recipient_username> or chat.<recipient_groupname>. 

Thanks
Volker

**Comment by vcordes79** [comment]
Just tried it and it works:
`public function getSubscribedRealmEvents() {
		return [
			"PublishMessageEvent"   => ["handleMessage", 90]
		];
	}
	
	/**
     * @param \Thruway\Event\MessageEvent $messageEvent
     */
    public function handleMessage(MessageEvent $messageEvent)
    {
		$message = $messageEvent->message;
		$topic = $message->getTopicName();
		if (substr($topic, 0, 5) == 'chat.') {
			$args = $message->getArgumentsKw();
			$args->time = date('Y-m-d H:i:s');
			$args->sender = $messageEvent->session->getAuthenticationDetails()->getAuthId();
			$message->setArgumentsKw($args);
		}
    }`
Is this the correct way to do it?

**Comment by davidwdan** [comment]
It would probably be better to publish the time when the message is sent and tell the router to disclose the publisher with the `disclose_publisher` option on the subscription:

```PHP
$session->subscribe('com.example.publish', function ($args, $kwargs = null, $details, $publicationId = null) {
    $authid     = $details->authid;
    $authMethod = $details->authmethod;
    $authRoles  = $details->authroles;

}, ['disclose_publisher' => true]);
```

I'm going to close this issue.  If you're still having issues or have any more questions, feel free to reopen it.

**Comment by semoriil** [comment]
Are there any restrictions where it works? Because it doesn't work in my case, not sure why. I've similar problem with chat app. PHP client added to router as internal client. Should it be a module?
