### ISSUE TITLE
Where to fetch client IP address in auth provider?

### ISSUE THREAD

**Issue by mewejo** [voryx/Thruway#266]
Hi,

Thank you for all the hard work on this, I can't explain the frustration I was having with Autobahn until I saw Ratchet doesn't support WAMP v2!

I have looked around the source for a place to find the clients IP address, the closest I got was `Thruway\Transport\RatchetTransport::getTransportDetails()`, but I just couldn't find how to access the transport property of the session.

I have tried the following in my auth provider, but seems it's only being passed `Thruway\Transport\InternalClientTransport`, not the Ratchet version.

```
public function processAuthenticate($signature, $extra = null)
{
	var_dump($this->transportModule->getTransportDetails());
}

public function onSessionStart($session, $transport)
{
	$this->transportModule = $transport;
	return parent::onSessionStart($session, $transport);
}
```

Which results in:

```
array(2) {
  'type' =>
  string(14) "internalClient"
  'transport_address' =>
  string(8) "internal"
}
```

I'm probably barking up the wrong tree with the code above, so any help would be greatly appreciated.

Thank you,

Josh

**Comment by davidwdan** [comment]
You can override `preProcessAuthenticate` in your auth provider and get the ip information out of the hello message.

For example:

```PHP
    public function preProcessAuthenticate(array $args)
    {

        $helloMsg = HelloMessage::createMessageFromArray($args[0]->hello_message);

        $transport = $helloMsg->getDetails()->transport;

        $transportAddress = $transport->transport_address;

        
        $args = $args[0];

        $signature = isset($args->signature) ? $args->signature : null;
        $extra     = isset($args->extra) ? $args->extra : null;

        if (!$signature) {
            return ['ERROR'];
        }

        return $this->processAuthenticate($signature, $extra);
    }
```
