### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alexandrmazur96** [voryx/Thruway#267]
Two years have passed, will you write the documentation?

**Comment by mbonneau** [comment]
Hi @alexandrmazur96 ,

As with most open-source projects: "PRs are welcome": If you (or someone else) would like work on  more documentation for the project we could certainly help with any questions.

With Thruway, we (the maintainers) prioritize bug fixes, implementing features that are back-logged, testing, and PRs above adding documentation. This may not be helpful to new people, but we use this package heavily in production and need things to work well. So when we do have "free" time to work on this, we usually don't make it to the documentation.

The ideas behind the WAMPv2 architecture are very applicable and would help getting a broad overview of how Thruway and the WAMPv2 ecosystem works.

As far a Thruway-specific help: please see the examples and the issues here. They have a lot of information in them. We are usually willing to help with questions when we have time (the community here also is a big help with questions).
