### ISSUE TITLE
Make Connector injectable

### ISSUE THREAD

**Issue by davidwdan** [voryx/Thruway#269]
You should be able to pass the connector into transport providers, which allow users to control the dns resolver.

**Comment by adrianlzt** [comment]
This is something that needs to be implemented or the answer to this problem?

**Comment by mbonneau** [comment]
@adrianlzt This is something that should be added to https://github.com/thruway/pawl-transport to allow overriding all of the `Connection` options if desired.

I am going to move this issue over to there now.
