### ISSUE TITLE
How-to Example not working anymore: Class 'Thruway\Transport\PawlTransportProvider' not found

### ISSUE THREAD

**Issue by fbeaudet** [voryx/Thruway#282]
Hi Guys,

First, thanks for this great piece of software !

I cloned the project last autumn and everything worked smoothly.

Now, when I fetch the up-to-date code, it seems like lots of classes have been removed since last time, leaving the HowTo Example in the Readme not functional.

It gives a "Class 'Thruway\Transport\PawlTransportProvider' not found", and indeed this class is nowhere to be found, there is just mentions of it here and there in the examples and, more importantly, in the Readme file.

So I just wanted to know what's exactly going on, is it that the version of Thruway you are working on has some refactoring that isn't reflected yet in the Readme ?

Anyway ! Thanks a lot !

**Comment by mbonneau** [comment]
@fbeaudet We have made an attempt to separate the router from the client library. There is still a crossover between the two apparently.

Require `thruway/pawl-transport` and that should pull in that class for the example.

**Comment by fbeaudet** [comment]
Thanks @mbonneau :)

**Comment by PhilETaylor** [comment]
yup - I got this too today... in production :(

**Comment by glenndilen** [comment]
Is there any update on this?

Still a bit stuck, installed via composer but I'm unsure which transport provider to use...

**Comment by mbonneau** [comment]
`composer require thruway/pawl-transport` will allow the examples to work.

**Comment by glenndilen** [comment]
Brilliant, cheers @mbonneau

**Comment by davidwdan** [comment]
The README has been updated with instructions on how to install the pawl transport
