### ISSUE TITLE
Authentication using existing sessionid cookie

### ISSUE THREAD

**Issue by WGPSenshi** [voryx/Thruway#283]
I need to add authentication to my websocket to assign roles as well as possible restricting allowed RPC calls on the server client.

The user logins via a REST route, starting a php session, which in turn sets a PHPSESSID cookie. I would like to have this as httponly, so no direct javascript access is possible.

The idea is to start the websocket session after this authorization has been completed, using the already existing PHP sessionid.

My clients use angularwamp.

Where I'm stuck right now: How can the thruway router access that cookie? I can't send it from Javascript as an onchallenge response or anything, as it's httponly. However, as I understand it, websocket uses a http upgrade to initialize, so there should be a window to use cookies for authentication? I want the authmanager to do a simple check if this user's session exists and go from there, which would be trivial.

The examples here are based on having access to the "secret" or CRA response available in javascript.

I'm fairly confused right now after a lot of googling and I'm afraid it's perfectly possible I might have misunderstood some concepts along the way.

**Comment by mbonneau** [comment]
All of the HTTP headers are available to authenticators. Transport details are in `$helloMessage->getDetails()->transport->headers`.

I am not sure how to access the php session using the `PHPSESSID` however.

**Comment by WGPSenshi** [comment]
I was both afraid and hoping it was gonna be a lot easier than I was making it out to be.
Accessing the PHP session: I'll do that using a custom session handler to allow specific access just to the authenticator.

Thanks for your quick reply!

**Comment by WGPSenshi** [comment]
I tried fiddling with this now, but while `transport->headers` has the general headers (without cookies), there is a separate entry for cookies. However,  `transport->cookies` is an empty array, despite there being active, valid cookies. I'm checking the $args in the `processHello()` function of the AuthProviderClient:

        error_log(print_r($args[0][2]->transport,true));

**Comment by WGPSenshi** [comment]
I was stupid :) . Cookies are only accessible if their domain _really_ matches the URL used for connecting. I was using the hostname for establishing the WS session, and the cookies were set for localhost.

**Comment by mbonneau** [comment]
@WGPSenshi The format of the headers has to do with PSR-7 header formats. If there are repeats of the same header, you can get more than one.

Consider nginx if you would like to host both your request/response PHP application and your Thruway router through the same host/port combination.
