### ISSUE TITLE
Server erroneously reports it is only broker not dealer

### ISSUE THREAD

**Issue by 0Kills** [voryx/Thruway#284]
When using authentication the server replies to clients with roles: broker but does not include the dealer role. Overriding clients to force them to make calls works fine, but most will not even attempt a call unless the server replies with dealer role.

**Comment by mbonneau** [comment]
@0Kills Could you provide the router code that reproduces this issue. I use the simple authentication example and the router is correctly responding with the roles:
```json
  {
    "roles": {
      "broker": {
        "features": {
          "subscriber_blackwhite_listing": true,
          "publisher_exclusion": true,
          "subscriber_metaevents": true
        }
      },
      "dealer": {
        "features": {
          "caller_identification": true,
          "progressive_call_results": true
        }
      }
    }
  }
```

**Comment by mbonneau** [comment]
I believe this is corrected in the latest release by the `WelcomeMessage` priority fix. Please open a new issue if it is not.
