### ISSUE TITLE
Help - Session storage for (de)authentication

### ISSUE THREAD

**Issue by WGPSenshi** [voryx/Thruway#286]
I tried using the google group which is supposed to be a better fit, but I didn't get a reaction, so I'll try here. I apologize if I'm being just too impatient, but it seems activity is a bit higher here.

https://groups.google.com/forum/#!topic/thruway/ainEdP-yf3M

In short: I'm stuck trying to authenticate using information I only have during onHello(), while I'd need it during onAuthenticate(). I could pass it back to the client and have it resend it, but I don't want to trust my clients more than necessary. Please read the detailed description of my issue above.

**Comment by mbonneau** [comment]
@WGPSenshi The challenge details can be set by the `onHello` as the second return argument.
```php
return [
    'CHALLENGE',
    (object)[
        'challenge' => 'my_challenge',
        'challenge_method' => 'some_method',
        '_some_arbitrary_property' => [ 'any', 'json_serializable', 'stuff' ]
    ]
];
```
The entire second element of the array is stored in the session and is available during `onAuthenticate` as `$args[0]->extra` (I think - I have not tried this - just reading through router source).

Here is where the `AuthenticationManager` sets up the stuff it sends to `onAuthenticate`: https://github.com/voryx/Thruway/blob/d7dcf4ea117df081fd0500c2234f63b45f7214ff/src/Authentication/AuthenticationManager.php#L419-L428

You can also authenticate sessions during the `onHello` by sending back `NOCHALLENGE` and setting the `authid` property on the second return argument.

If you need further help, it would be helpful to me if you posted some source code.

**Comment by WGPSenshi** [comment]
You are correct, that's how I could make it work. But: If I return the data from onHello, it is sent back to the client, which then sends it back to the server during onAuthenticate. That leaves an opening for the client to alter that data, which it should not be able to do. The client will never need and should never have that nugget of information.
The router uses the PHPSESSID cookie to look up if there in fact is an active phpsession with that id, and retrieves the associated userid if available. It also stores the trifecta of userid, websocket-sessionid and PHPSESSID internally, so I can later query and manipulate it (check if session still valid, or deauthenticate it if user logs out via REST).
At that point, I could already return SUCCESS, but I can't do that during onHello, so I'd need to send that info straight to onAuthenticate, without the "detour" via the client.

I'll see about providing a code sample tomorrow.

**Comment by mbonneau** [comment]
The extra information is not generated from the client, but is sent to the client. It is pulled back out of the session.

**Comment by WGPSenshi** [comment]
Ah, then I worried for no reason. Thanks for clearing it up!
