### ISSUE TITLE
how to attach auth role to "authid"?

### ISSUE THREAD

**Issue by MonicaMillerr** [voryx/Thruway#290]
public function processHello(array $args) {

        $helloMsg  = HelloMessage::createMessageFromArray($args[0]);
        $transport = $helloMsg->getDetails()->transport;

        return ['NOCHALLENGE', ['authid' => 'myUserName' , 'auth_roles'=>'test']]; 
    }

is that correct? 

I guess no, because I tried the following but I got `{error: "wamp.error.not_authorized",.....` when the client subscribing. 

```

$authorizationManager = new \Thruway\Authentication\AuthorizationManager('realm1122');
$rules = [
    (object)[
        "role" => "test",
        "action" => "publish",
        "uri" => "",
        "allow" => false
    ],
    (object)[
        "role" => "test",
        "action" => "subscribe",
        "uri" => "",
        "allow" => true
    ]
];

foreach ($rules as $rule) {
    $authorizationManager->addAuthorizationRule([$rule]);
}
$router->registerModule($authorizationManager);


```

**Comment by davidwdan** [comment]
Try `'auth_role'=>'test'` or `'auth_roles'=>['test']` . Either one of those should work.

**Comment by MonicaMillerr** [comment]
Thanks a lot, this one did work: 'authrole'=>'test'
