### ISSUE TITLE
Deauthenticate/Close session from client

### ISSUE THREAD

**Issue by WGPSenshi** [voryx/Thruway#293]
I need to be able to kick user sessions (deauthenticate and/or close their session).

I use an internal client to keep track of all sessions. I grab the sessionid (which I get whenever the users authenticate with my custom AuthProviderClient), which I then store in-memory.

Now, there can be situations where a user session needs to be force-closed. E.g. if his user permissions are altered in a way (most commonly by an independent REST API).
If this happens, I need to check if the session needs to be removed: I request the sessionids from the internal client (added an RPC) and see if I find a match.
If I do,  I then would need to get the actual session with this ID and end it.
A way to do this is described in #262 .
And that's where my problem is: I don't see a way to access the realm/router from within a client. #262  simply accesses the router directly, as it is run in a loop outside of a client.

How can I get active Thruway Sessions from inside a client to close them?

**Comment by mbonneau** [comment]
@WGPSenshi You reference #26, is it possible that you meant a different issue?

I would recommend (if you are running a single realm) that you grab that realm and inject it into the InternalClient. You could then get the sessions from the realm.

Another option would be to keep track of realm creation:
```php
    public static function getSubscribedEvents()
    {
        return [
          "new_realm" => ["handleNewRealm", 10],
        ];
    }

    public function handleNewRealm(NewRealmEvent $event)
    {
        Logger::info($this, "I see a new realm: ".$event->realm->getRealmName());
        $this->realms[$event->realm->getRealmName()] = $event->realm;
    }
```
You will get handles to the actual sessions and can call `shutdown` on it.

There are a few other ways I can think to do this. Let me know if this points you in the right direction.

**Comment by WGPSenshi** [comment]
My bad, I intended to reference #262 (fixed OP).

I only use one realm (and I don't want to allow more), but I run into issues there. This is how my router sets up:
```
$router            = new Router();
$router->getRealmManager()->setAllowRealmAutocreate(false); // Forbid everyone from creating realms at will
$realm = new \Thruway\Realm('iris'); // I only want this one realm to ever exist
$router->getRealmManager()->addRealm($realm);

$authProvClient       = new IrisAuthProviderClient(['iris']); // The internal client, extended from AbstractAuthProviderClient, does the actual authentication processing
$authorizationManager = new IRISAuthorizationManager('iris'); // extended from AuthorizationManager

$router->registerModules([
    $authorizationManager,
    new \Thruway\Authentication\AuthenticationManager()
]);
$router->addInternalClient($authProvClient);
```
However, this leads to the authProvClient being ignored and everyone just being able to connect to the 'iris' realm straight away. So it seems the authmanager/providerclients are not actually tied to the realm? Where's my mistake here?

**Comment by mbonneau** [comment]
@WGPSenshi You can auto-create the realm prior to disabling the auto-create, (I believe you will want to make sure the `thruway.auth` realm is also created before shutting off auto-create):
```php
$router            = new Router();
$realm = $router->getRealmManager()->getRealm('iris');
$authRealm = $router->getRealmManager()->getRealm('thruway.auth');
$router->getRealmManager()->setAllowRealmAutocreate(false); // Forbid everyone from creating realms at will

$authProvClient       = new IrisAuthProviderClient(['iris']); // The internal client, extended from AbstractAuthProviderClient, does the actual authentication processing
$authorizationManager = new IRISAuthorizationManager('iris'); // extended from AuthorizationManager

$router->registerModules([
    $authorizationManager,
    new \Thruway\Authentication\AuthenticationManager()
]);
$router->addInternalClient($authProvClient);
```

**Comment by WGPSenshi** [comment]
Thanks for the suggestion. But it's still the same issue:
Everybody gets to join&act 'iris' realm, without any part of the Auth process being triggered or processed.

As soon as I use
```
$router            = new Router();
$realm = $router->getRealmManager()->getRealm('iris');
$authRealm = $router->getRealmManager()->getRealm('thruway.auth');
```
the issue arises. Calling getRealm() on thruway.auth alone is no problem (i.e. removing line 2).

When I create a different realm with a "wrong" name (and autocreate false), I do get the actual "no realm with such name" error message, so there doesn't seem to be a "iris ghost" realm floating around. It just seems the auth process is not triggered by the realm.
Are there any additional options to force this during creation of the auth modules/clients?

**Comment by mbonneau** [comment]
I thought about this a little more. The ordering of the modules matters because the router modules add themselves to the realms.

Register the authentication and authorization modules before calling `getRealm('iris')`.

**Comment by mbonneau** [comment]
@WGPSenshi - Did that work for you?

**Comment by kbkk** [comment]
@WGPSenshi  This is what worked for me
```
$router->getLoop()->futureTick(function () use ($router) {
  $router->getRealmManager()->getRealm('iris');
  $router->getRealmManager()->setAllowRealmAutocreate(false);
});
```
:+1:
