### ISSUE TITLE
How to run router and client in production?

### ISSUE THREAD

**Issue by aktiwers** [voryx/Thruway#298]
How do you run the router and client in production environment? 
I have created a small script I use while developing, that looks something like this:
```
#Run the simple router
nohup php vendor/voryx/thruway/Examples/SimpleWsRouter.php > /dev/null 2>&1 &
echo $! > save_pid_router.txt
# Run  client
nohup php cmd.php > cmd.log 2>&1 &
echo $! > save_pid.txt
```

But I have noticed that this process dies sometimes, when leaving it running for days.

So how do you run the router and client and make sure it keeps running?

**Comment by davidwdan** [comment]
Take a look at http://supervisord.org/ or http://pm2.keymetrics.io/
