### ISSUE TITLE
Send message to sender from RatchetTransportProvider onMessage

### ISSUE THREAD

**Issue by AdamSEY** [voryx/Thruway#301]
```
class ClientEvents extends  RatchetTransportProvider
{
public function onMessage(ConnectionInterface $from, $msg)
    {
           // Passing message to RatechetTransaportProvider
           parent::onMessage($from, $msg);

          // Passing an extra message    

           $msgAgrs = new \stdClass();
           $msgAgrs->extraMessage = 'This is an additional message.';
          $extraMessage = [16, Utils::getUniqueId() , new \stdClass() , $channelName , [$msgAgrs]];
          $createdMsg = json_encode($extraMessage);
          parent::onMessage($from, $createdMsg);
    }
}
```
Non-sender receives:
`[36,2866169358978998,3592733950951966,{},[{"extraMessage":"This is an additional message."}]]
`
The problem is the message is sent only to non-sender particpents but I want to send it only to the sender.

**Comment by mbonneau** [comment]
Publishing back to the publishing session requires you to specify `["exclude_me" => false]` as an option.

**Comment by AdamSEY** [comment]
Thanks for your reply, I'm wondering if can I publish back just to the sender rather than everyone including me.

**Comment by mbonneau** [comment]
Yes you can - by specifying `eligible` session ids. 

I would suggest reworking how you are handling these messages but I am not sure what you are trying to do so I don't know exactly what to suggest.
