### ISSUE TITLE
Do i need to create new client for each publish call ?

### ISSUE THREAD

**Issue by miranos** [voryx/Thruway#311]
Hi,

First i launched the router on my server:
```

<?php

require 'bootstrap.php';

use Thruway\Peer\Router;
use Thruway\Transport\RatchetTransportProvider;

$router = new Router();

$transportProvider = new RatchetTransportProvider("127.0.0.1", 9090);

$router->addTransportProvider($transportProvider);

$router->start();
```

And for a chat system for example, built using ajax (jQuery) and Autobahn as client on the browser to subscribe and receive events.

When user send new message, do i have to create new client each time ?

Or create function like this:

```
<?php

require __DIR__ . '/vendor/autoload.php';

use Thruway\ClientSession;
use Thruway\Peer\Client;
use Thruway\Transport\PawlTransportProvider;

function sendToBrowser($subscribe, $result) {
	$client = new Client("realm");
	$client->addTransportProvider(new PawlTransportProvider("ws://127.0.0.1:9090/"));

	$client->on('open', function (ClientSession $session) use ($subscribe, $result, $client) {

		$session->publish($subscribe, [$result], [], ["acknowledge" => true])->then(
			function () use($client) {
                               $client->close();
				echo "Publish Acknowledged!\n";
			},
			function ($error) {
				echo "Publish Error {$error}\n";
			}
		);

		
	});


	$client->start();
}
```

So, when new message is sent, will be received from AJAX and then sent to the client browser like this:

`sendToBrowser("message", "The message of user here");`

Is there any other way to do it without creating new client each time ? or is the only way to do it ? What about server loads if for each message sent i have to create new client ?

I have one problem, is that the session do not close when message is published !

Any fix or suggestion will be welcomed, thank you in advance.

**Comment by munavvard2** [comment]
you don't need to create client each time, if you create then session will be lost,
just make an internal client which have RPC  for getting message , and publish a message for receiver, and why are you using ajax ! there is no need to use it, you have bi-directional connection with server.you can do anything you want.
