### ISSUE TITLE
Segmentation fault with PHP 7.3?

### ISSUE THREAD

**Issue by alegout** [voryx/Thruway#320]
Hello,

On **PHP 7.3** i got **segmentation fault** error when `RatchetTransportProvider::onOpen`, anybody has the same issue on PHP 7.3? It **works fine on PHP 7.2**.

```
2019-03-02T18:35:42.1742850 debug      [Thruway\Transport\RatchetTransportProvider 346] RatchetTransportProvider::onOpen
Segmentation fault
```

Thank you

**Comment by mbonneau** [comment]
I run on 7.3 in a few places and have not encountered this. What is the full PHP version/os/Thruway version etc?

**Comment by alegout** [comment]
Hello @mbonneau,

Thank you for your answer.

After some research, it is caused by ev php extension. 
https://blog.remirepo.net/post/2018/07/02/PHP-extensions-status-with-upcoming-PHP-7.3
