### ISSUE TITLE
What arguments are passed to connection on('open')?

### ISSUE THREAD

**Issue by M1ke** [voryx/Thruway#322]
When running `$connection->on('open')` the second argument is a callback. The first argument of this is a `ClientSession` - are there any other arguments passed and what are their specifications? I tried to find this out by reading the code but it's just the evenement wrapper, and doing `var_dump(func_get_args())` inside it is too much information to parse.

Thanks!

**Comment by mbonneau** [comment]
Here is where this event is emitted: https://github.com/thruway/client/blob/532604ab58de1e271a368dae406685566c539c87/src/Peer/Client.php#L356

**Comment by M1ke** [comment]
Sorry for my lack of response and thanks for the pointer.
