### ISSUE TITLE
Authorization based on content

### ISSUE THREAD

**Issue by simonquest** [voryx/Thruway#323]
Hi there, 

I was successfully using an old version of Thruway to let users subscribe to several topics and, in particular, I had implemented an AuthorizationManager so that users could only subscribe to content they had permissions for: eg. users could subscribe to topic like _mywebsite.project.{id}_ and authorizationmanager would allow subscription if a query to db would show that user has access to that particular project.

Now I'm trying to do the same thing on another project using the latest version of Thruway, where authorization happens using static rules, at least that's my understanding...
How can I check if user has credentials to subscribe to a specific topic?
btw, I'm working with symfony 3.4 (LTS).

Thanks

**Comment by mbonneau** [comment]
@simonquest I am not sure what version you went from/to. I am closing this issue now as it is pretty old. Open a new issue if needed.
