### ISSUE TITLE
How to pass request headers for connection?

### ISSUE THREAD

**Issue by rst630** [voryx/Thruway#324]
I need to send cookies and etc headers

**Comment by sentiasa** [comment]
+1

**Comment by samizdam** [comment]
Hm, I amnot sure, that wamp about http transport.
Headers are http specific. It is transport protocol.
Wamp It is application level protocol.
You just want use jwt for client meta information.

**Comment by rst630** [comment]
best way to send headers is proxy via nginx and set headers, check nginx manual for socket proxy

**Comment by mbonneau** [comment]
You can create authentication providers that are sent the transport information (including headers for HTTP). If you would like them to be part of the authentication information, you can send them back the router as auth extra info.

**Comment by sentiasa** [comment]
Apparently I was a bit lost with the terminology in general. Thanks for all the responses
