### ISSUE TITLE
Logger issues.

### ISSUE THREAD

**Issue by lpj145** [voryx/Thruway#334]
![image](https://user-images.githubusercontent.com/11980109/73276517-93ab5d00-41c7-11ea-8f3f-8351aec0c082.png)
Look for this, for me is a mistake, i can't use this on web request, simple only on cli, because buffer is spammed about details of connection, have some method to shut-up this logger ?

**Comment by lpj145** [comment]
Please the docs about this library is poor, and have some other things to make more reusable, if you need a help or have interest, show it.

**Comment by davidwdan** [comment]
Please see: https://github.com/voryx/Thruway/issues/61#issuecomment-65310228

**Comment by lpj145** [comment]
> 
> 
> Please see: [#61 (comment)](https://github.com/voryx/Thruway/issues/61#issuecomment-65310228)

I make pr to show this.
