### ISSUE TITLE
Autosubscribe client on topic

### ISSUE THREAD

**Issue by hartois** [voryx/Thruway#339]
Hello
I want create one topic per user such as user.<userId>
How can I auto-subscribe client on this topic after authentification?

**Comment by cyprus1spirit** [comment]
You need to register the user as a topic as you capturing it via ZQM push php code from your application. Your application then spits the javascript to the browser with the respective name as a topic and connects to the server. 

My main concern I want to ask. If a user disconnects the single respective topic becomes deleted too? Or it remains in memory????

thanks

**Comment by mbonneau** [comment]
When a user unsubscribes from a topic, the subscription does not stay in memory.
