### ISSUE TITLE
Is it possible to get the subscriber's session id when he posts?

### ISSUE THREAD

**Issue by cyprus1spirit** [voryx/Thruway#341]
Here is how I attempt to get  subscriber's session id but I can't.
```
    // 1) subscribe to a topic
    $onevent = function ($args) {
        echo $args[0]->session;
    };
    $session->subscribe('com.myapp.hello', $onevent);
```
Thanks. I am about to give up with Thruway. No manual, no documentation. Anybody can help me?

**Comment by cyprus1spirit** [comment]
I completely abandoned the library. Nobody knows nothing. Even if it works or not. Unfortunately I had to go with nodejs / socket.io solution which by far can not be compared with Thruway. nodejs / socket.io is simple complete and functional compare to the miserably complex and probably buggy and abandoned Thruway, 

Sorry guys. I have really spent a lot of my valuable time with your undocumented and abandoned code. Thanks god that other solutions were there for me !

**Comment by davidwdan** [comment]
We're in the middle of a worldwide pandemic and you're upset that people aren't dropping everything they're doing to teach you how to use a **free** open source library?  That speaks volumes about the type of person you are.

Abandoned?  Before falsely accusing the people who made this library for FREE, you should spend 5 minutes of research.  There was a commit less than 24 hours ago.

You're clearly a leech who doesn't have the slightest idea of how open source works.

**Comment by davidwdan** [comment]
FYI, to get the auth or session id of the client that has published, use the `disclose_publisher` option when subscribing and you'll get the `authid` and `pusblisher` session id in the details.

https://github.com/voryx/Thruway/blob/7039e871bfedc319bcadf5445ac30e0fc0eb52be/tests/WAMP/DisclosePublisherTest.php#L64
