### ISSUE TITLE
[Question] Can we prevent specific sessions from registering RPCs?

### ISSUE THREAD

**Issue by Ethorsen** [voryx/Thruway#352]
Might be a simple question, might not.

I want to prevent any session from the outside world from registering RPCs, and only allow it on my trusted clients.  

It feels like our AuthProviderClient should be able to set the permissions of an authenticated session. 
Some booleans that we could set on the session, like
   - canRegister
   - canCall
   - canPublish
   - canSubscribe
  
Something that can be done with Thruway?

Thx

**Comment by mbonneau** [comment]
@Ethorsen Check out here: http://voryx.net/authorization-permissions-with-thruway/

Let me know if that helps.

**Comment by Ethorsen** [comment]
Yes thank you this is exactly it
