### ISSUE TITLE
upgrade to php 8.1

### ISSUE THREAD

**Issue by giannisdag** [voryx/Thruway#360]
As php 8.1. introduces new features, are you planning to upgrade and if yes when you plan to do so? thank you in advance

**Comment by mbonneau** [comment]
Yes. Are there any 8.1 incompatibilities?

**Comment by Ethorsen** [comment]
I'm using 8.1 without a single issue

**Comment by giannisdag** [comment]
I haven't check it myself, so as Ethorsen said it is ok, thank you guys
