### ISSUE TITLE
Implement subscription meta events

### ISSUE THREAD

**Issue by mbonneau** [voryx/Thruway#40]
See #37

**Comment by NeoVance** [comment]
I see that the broker has been set up with the feature enabled by default. Is this implemented? Is it used via subscription as described in the WAMP spec?

```
{"metatopics": ["wamp.metatopic.subscriber.add",
                     "wamp.metatopic.subscriber.remove"],
      "metaonly": 1}, "com.myapp.mytopic1" 
```

**Comment by NeoVance** [comment]
@mbonneau I have looked everywhere. I would expect this to be in the broker as described in the spec, or possibly the SubscriptionGroup object, but I don't see it implemented.

I was considering implementing this myself in a router, but the onMessage method is no longer used in that class so there does not seem to be any easy way to watch events passed to or from the broker.

**Comment by mbonneau** [comment]
Hi @NeoVance ,

The subscription meta events have not been implemented yet. I believe we mistakenly added that feature announcement somewhere along the way after implementing "session" metaevents.

I have looked into how best to implement these but there are a few things I couldn't settle on. One thing is that I am not crazy about the way the spec has you "metasubscribe" to these. I really would have preferred a regular subscribe("wamp.metatopic.subscriber.add.com.myapp.mytopic1") instead. This would make it easier to add permissions regarding who is allowed to subscribe to the meta and would also make things cleaner.

Another issue I have is that different subscriptions could possibly receive the EventMessage. One person can subscribe to the exact URI "com.myapp.mytopic1" while another might be subscribed to the prefix URI "com.myapp.". Both would receive the events to "com.myapp.mytopic1", but they are not the same. So when you subscribe to the meta event, would you get information on anyone would could see a specific URI, or only subscriptions that are exactly the same as yours?

As far as implementation, the 0.4 branch uses the event dispatcher to process messages now.

The approach I might take to implement:
- Create 2 new events, SubscribeEvent and UnsubscribeEvent that would contain all the relevant information regarding the event (session, SubscribeMessage, SubscribedMessage, subscription, subscription group)
- Dispatch them here https://github.com/voryx/Thruway/blob/c68250cd816644a1438691fb02237986be6fcfaf/src/Thruway/Subscription/SubscriptionGroup.php#L256 and here https://github.com/voryx/Thruway/blob/c68250cd816644a1438691fb02237986be6fcfaf/src/Thruway/Subscription/SubscriptionGroup.php#L278
- Create a realm module SubscriptionMetaEventModule
- The SubscriptionMetaEventModule could then just watch and keep track of sessions that want (as noted in the SubscribeMessage details) to see these events and send them accordingly.

It would be nice to be able to use the broker to handle the subscription to the meta as well. Could possibly feed a second SubscribeMessage into the dispatcher and then suppress the SubscribedMessage that gets sent for it. Then whenever a subscription happens, you could also feed a PublishMessage event into the dispatcher to send the meta event. Not sure how feasible that is though.

**Comment by ftrrtf** [comment]
Any news about meta events?

**Comment by mbonneau** [comment]
Please see: https://github.com/voryx/ThruwaySubscriptionMeta

**Comment by mbonneau** [comment]
This is implemented in the above module.
