### ISSUE TITLE
Authorization?

### ISSUE THREAD

**Issue by adosaiguas** [voryx/Thruway#41]
Ok, our users can now get authenticated into our thruway powered WAMP v2 server but... How do we control authorization? I don't want all users to be able to publish or subscribe to any topic, I would like to limit this depending on the role of the user. Is it possible? Are there any onSubcribe and onPublish events? If so, how can I access the logged in user data?

**Comment by davidwdan** [comment]
@blackeyedboy How's your project coming along?  Where you able to get everything working?
