### ISSUE TITLE
Add call timeout option

### ISSUE THREAD

**Issue by mbonneau** [voryx/Thruway#43]

**Comment by barbushin** [comment]
This is very critical, because otherwise reconnect does not works as expected. Only one single retry is occurred of router is disconnected. Also retry is not occurred if first connection is failed.

**Comment by davidwdan** [comment]
We'll be able to do this once we update the `caller` and `callee` roles to use `Rx\Observable` instead of promises.

**Comment by mbonneau** [comment]
At the moment, if you would like to support client-side timeouts and cancelation, I would recommend using the more advanced https://github.com/voryx/RxThruwayClient

I am closing this because it has been inactive for too long.
