### ISSUE TITLE
Pattern Based Subscriptions (Advanced Spec)

### ISSUE THREAD

**Issue by davidwdan** [voryx/Thruway#51]
Add support for [pattern based subscriptions](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#pattern-based-subscriptions).

See https://github.com/voryx/ThruwayBundle/issues/5

**Comment by mbonneau** [comment]
Latest commit (https://github.com/voryx/Thruway/commit/ba2166932c9e553980adf24e66e44f9cf3729f98) supports prefix matching.

New subscription group architecture supports pluggable "matchers" to allow for easier implementation of other matching schemes.
