### ISSUE TITLE
Add Capability to Remove Internal Clients from Running Router

### ISSUE THREAD

**Issue by mbonneau** [voryx/Thruway#57]

**Comment by jimjam88** [comment]
Hello, is this going to be integrated? It'd be a nice feature to have

**Comment by mbonneau** [comment]
I am not sure what the timetable is on this feature.

**Comment by mbonneau** [comment]
I am no longer sure if there is actually a good use case for this. I will leave this issue open a little longer to get feedback if there is someone that has a good use case.
