### ISSUE TITLE
Creating custom serializer

### ISSUE THREAD

**Issue by iJoyCode** [voryx/Thruway#62]
Hello!

Do you plan to implement possibility to use custom serializer in RatchetTransportProvider.
I need to switch off JsonSerializer.

**Comment by mbonneau** [comment]
There are no plans to implement the ability to have a serializer that can insert a raw encoded JSON string into the JSON string of the message.

It is possible to serialize arguments and options/details in just about any JSON supported way by either using the [JsonSerializable interface](http://php.net/manual/en/class.jsonserializable.php) or by creating the a php data structure to match what you want to be encoded.
