### ISSUE TITLE
Does Thruway support secure websockets server (wss://)?

### ISSUE THREAD

**Issue by iJoyCode** [voryx/Thruway#66]
Does Thruway support secure websockets server (wss://)?

**Comment by kcivey** [comment]
This worked for me (not on nginx 1.4.6, but it did after I upgraded to 1.8.0):

```
  location ^~ /thruway {
    proxy_pass http://localhost:8080;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
```

Then I could use `wss://example.com/thruway` for the websocket URL.

**Comment by eloirobe** [comment]
This seems to work for me in apache:

`
Listen 4043
<VirtualHost *:4043>
  ServerName example.com
  SSLCertificateFile /etc/ssl/example.com.pem
  SSLCertificateKeyFile /etc/ssl/example.com.key
  SSLEngine On
  SSLProxyEngine On
  ProxyPreserveHost On
  ProxyRequests Off
  ProxyPass / ws://localhost:8080 retry=0 keepalive=On
  ProxyPassReverse / ws://localhost:8080 retry=0
</VirtualHost>
`

Then I could use `wss://example.com:4043`

**Comment by stingus** [comment]
I used the Apache proxy at first but I was getting random 502 errors: `Broken pipe: [client xxx.xxx.xxx.xxx:xxxxx] AH01084: pass request body failed to yyy.yyy.yyy.yyy:8080`. Switching to Nginx proxy seems to work flawlessly.

**Comment by ofumbi** [comment]
I want to connect to crossbar.io server wss using the thruway client, its seems all the solutions are for a server
how can is use thruway client (NOT SERVER) for wss connections?

**Comment by mbonneau** [comment]
@ofumbi - This should not be an issue.

**Comment by ofumbi** [comment]
Actually it is. wss://myserver.com. freeszes. BUT ws://myserver.com. is fine. I had to solve this by removing TLS options  then moving the crossbar.io server behind  a proxy and then using the proxy to redirect traffic from  wss://myserver.com =>ws://myserver.com. This way the thruway client connects using   ws://myserver.com  and google chrome (which now requires wss links for Https sites can also connect ) using wss://myserver.com.

**Comment by davidwdan** [comment]
If you can't connect to wss:// it's a bug.  Can you open a new issue, for the client, with the steps to reproduce?

**Comment by nahuelhds** [comment]
Just for the record. In my case I've used the very same 443 port for the wss connection.

1. My Wamp Server works under port `9090` (listening `0.0.0.0`)
2. My AutobahnJS client connects fine at `ws://127.0.0.1:9090`

First of all, Apache needs to have enabled modules `mod_proxy` and `mod_proxy_wstunnel`. That can be done under `httpd.conf` file.

Then you need to configure the virtualhost for HTTPS and WSS proxy redirection at `httpd-vhost.conf` file:

```
<VirtualHost *:443>
        # Common SSL Config
	ServerName my-site.test

	SSLEngine on
	SSLCertificateFile "/usr/local/etc/httpd/server.crt"
	SSLCertificateKeyFile "/usr/local/etc/httpd/server.key"

	DocumentRoot "/Users/nahuelhds/Sites/my/site"
	<Directory  "/Users/nahuelhds/Sites/my/site">
		Options +Indexes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>

	# Websocket proxy
        # wss redirects to working ws protocol
	ProxyPass /wss ws://127.0.0.1:9090 retry=0 keepalive=On 
	ProxyPassReverse /wss ws://127.0.0.1:9090 retry=0 
</VirtualHost>
```

Restart Apache and the use this URL for the secure websocket: `wss://my-site.test/wss`
