### ISSUE TITLE
Mention dependencies (ie. php 5.4) 

### ISSUE THREAD

**Issue by RadekHavelka** [voryx/Thruway#74]
Please do mention what are the system requirements ... for example now I found out that running the command

```
php composer.phar require "voryx/thruway":"0.3.*"
```

returns error

```
 Problem 1
    - voryx/thruway 0.3.1 requires php >=5.4 -> no matching package found.
    - voryx/thruway 0.3.0 requires php >=5.4 -> no matching package found.
    - Installation request for voryx/thruway 0.3.* -> satisfiable by voryx/thruway[0.3.0, 0.3.1].
```

Thanks

**Comment by mbonneau** [comment]
Thruway does require php 5.4 for many reasons. We use language features that are only available in 5.4 (traits, array syntax) and there are dependencies that require 5.4 (reactphp/react, ratchet/pawl, etc.).

**Comment by RadekHavelka** [comment]
I do not doubt it in any way, just until I opened the composer file, I had no idea such dependancy exists, would be fine to mentioned in the docs as requirement. My whole installation of crossbar.io failed on that, as I am not able to install the PHP component because of php 5.3 ("non negotiable must be" as my colleagues call it :) ). Would be nice to know it in advance, thats all :)

**Comment by davidwdan** [comment]
Updated README with requirements https://github.com/voryx/Thruway/commit/db8870a2162b6263b3fdd80a7a502f3338b922d2
