### ISSUE TITLE
Permissions, roles

### ISSUE THREAD

**Issue by drtzack** [voryx/Thruway#76]
Can't find doc for permissions. Is there any chance to implement permissions to clients?

**Comment by drtzack** [comment]
I can limit users in .crossbar/config.json
         "realms": [
            {
               "name": "realm1",
               "roles": [
                  {
                     "name": "authenticator",
                     "permissions": [
                        {
                           "uri": "*",
                           "publish": true,
                           "subscribe": true,
                           "call": true,
                           "register": true
                        }
                     ]
                  },
                  {
                     "name": "frontend",
                     "permissions": [
                       {
                         "uri": "com.server.login",
                         "call": true
                       },
                       {
                         "uri": "com.app.*",
                         "publish": true,
                         "subscribe": true
                       }
                     ]
                  }
               ]
            }
         ]

How to do it?

**Comment by mbonneau** [comment]
To use permissions in Thruway, you need to load the AuthorizationManager module for the realm.

```php
$authorizationManager = new \Thruway\Authentication\AuthorizationManager('authorizing_realm');
$router->registerModule($authorizationManager);
```

The AuthorizationManager provides RPCs that can be used to change the permissions in that realm:

### add_authorization_rule

add_authorization_rule is called with a single argument that is a authorization rule:

In JSON:
```
{
    "role": "some_role",
    "action": "publish",
    "uri": "some.uri",
    "allow": true
}
```

In PHP:
```php
(object)[
   "role" => "some_role",
   "action" => "publish",
   "uri" => "some.uri",
   "allow" => true
]
```

If you would like to setup rules prior to the startup of the router, you can call the same functions in PHP prior to calling start:

```php
$authorizationManager->addAuthorizationRule((object)[
    "role" => "some_role",
    "action" => "publish",
    "uri" => "some.uri",
    "allow" => true
]);
```

## remove_authorization_rule

This is not implemented yet.

## flush_authorization_rules

This takes a true/false argument that will set the default policy of the realm.

## get_authorization_rules

This returns all of the authorization rules that have been set.

## test_authorization

This allows testing of actions to return whether or not the current permissions will allow or deny an action.

test_authorization takes 3 arguments.

[["role1", "role2"], "publish|subscribe|register|call", "my.uri"]

- An array of roles that will be tested.
- The action being tested.
- The URI that is being tested.

I am in the process of writing a post to demonstrate the use of permissions. I will repost that here when it is complete. Please let me know if you have any other questions.

**Comment by drtzack** [comment]
$authorizationManager = new AuthorizationManager('realm1');
    $rule = new stdClass();
    $rule->role = 'user';
    $rule->action = 'subscribe';
    $rule->uri = 'com.app.notification';
    $rule->allow = true;

    $authorizationManager->addAuthorizationRule([$rule]);

    $router->registerModules([
      $this->client,
      $authorizationManager
    ]);

I wrote these but client fails
 WebSocket transport send [32,3855076802166784,{},"com.app.notification"]
autobahn.min.js:33 WebSocket transport receive [8,32,3855076802166784,{},"wamp.error.not_authorized"]
autobahn.min.js:257 [promises] Unhandled rejections: 1

also 
$msg = new SubscribeMessage(12345, [], 'com.app.notification');
$session = //How to get a session?
$authorizationManager->isAuthorizedTo($session, $msg)

Tried to use my InternalClient session but getSession returns null.

I couldn't any test.

I guess I can't type wildcard like * when I type it just returns "ERROR"

**Comment by drtzack** [comment]
I added this and it worked. But is it necessary?
$authorizationManager->setReady(true);

I have just found usages of setReady in AuthorizationManager@onSessionStart. It seems function is not called.

**Comment by mbonneau** [comment]
setReady should be called once all the authorization RPCs are registered. This does not happen until the authorization manager session is up and running (the AuthorizationManager is an internal client).  If you are calling them inside of your internal client before the router is started, they will not be ready to go.

It is possible that the ordering of the modules may change the behavior. I would have to give this a try to see.

**Comment by mbonneau** [comment]
Hi @drtzack ,

Are you still having an issue with this?

**Comment by drtzack** [comment]
I have tested it now it works thank you.

Here is the full code

    $loop = Factory::create();
    $router = new Router($loop);
    $authMgr = new AuthenticationManager();

    $router->setAuthenticationManager($authMgr);
    $router->addTransportProvider(new InternalClientTransportProvider($authMgr));

    $authProvClient = new OAuth2Provider(config('socket.realms'));
    $router->addTransportProvider(new InternalClientTransportProvider($authProvClient));


    $transportProvider = new RatchetTransportProvider(config('socket.host'), config('socket.port'));
    $router->addTransportProvider($transportProvider);
    $this->client = new InternalClient(config('socket.realm'));


    $authorizationManager = new AuthorizationManager(config('socket.realm'));
    $authorizationManager -> setAuthId('AuthorizationManager');
    $rule = new stdClass();
    $rule->role = 'frontend';
    $rule->action = 'subscribe';
    $rule->uri = 'com.app.';
    $rule->allow = true;
    $authorizationManager->addAuthorizationRule([$rule]);
    $rule = new stdClass();
    $rule->role = 'frontend';
    $rule->action = 'call';
    $rule->uri = 'com.app.';
    $rule->allow = true;
    $authorizationManager->addAuthorizationRule([$rule]);
    $router->registerModules([
      $authorizationManager,
      $this->client,
    ]);
    $router->start();
