### ISSUE TITLE
Get Session by ID

### ISSUE THREAD

**Issue by drtzack** [voryx/Thruway#77]
I want to associate session id to user.
When an event fired, I will send a message to spesific user.
Just stucked. Don't know how to do.

**Comment by davidwdan** [comment]
@talhazekeriyadurmus there no way to whitelist based upon the user name, only the session id.  A work around, is to use the meta events to keep track of sessions and then get the lists of sessions for that user.

Here's an example with untested code.  It should be enough for you to get the basic idea.

Create an [internal client](https://github.com/voryx/Thruway/tree/master/Examples/InternalClient) that stores the user/session info in memory:
```PHP
<?php

$sessions = [];

$connection->on(
    'open', function (ClientSession $session) use ($sessions){

    $session->subscribe('wamp.metaevent.session.on_join', function($args) use ($sessions){
                $sessions[$args->authid][] = $args->session;
    });

    $session->subscribe('wamp.metaevent.session.on_leave', function($args) use ($sessions){
        //remove the session
        if (!isset($sessions[$args->authid])){
            return;
        }
        
        foreach ($sessions[$args->authid] as $k => $session) {
            if ($session === $args->session){
                unset($sessions[$args->authid][$k]);
            }
        }
        $sessions[$args->authid] = $args->session;
    });

    $session->register('com.example.get_user_sessions', function($args) use ($sessions){
        return $sessions[$args[0]];
    });
    
});

```

Then from the client that you want to publish to just one user:
```PHP


// Publish to all sessions associated with one authid
$session->call('com.example.get_user_sessions', [$authid])->then(
    function ($res) use ($session) {

        $session->publish('com.example.test_publish', array('Testing'), [], ['eligible' => $res[0]]);

    }
);


```

**Comment by talhazekeriyadurmus** [comment]
Thanks for reply.

I changed the lines like $args->authid to $args[0]['authid'] and it worked but when i get session it just returns id like 1311015427. Doesn't return the class so cant publish it.

**Comment by talhazekeriyadurmus** [comment]
Found getSessionBySessionId but it returns Thruway\Session not ClientSession.

**Comment by davidwdan** [comment]
The wamp meta events only includes the session id, not the entire session object, so when you call `com.example.get_user_sessions`, you'll get a list of sessions ids, not session objects.

You can then pass that array to the `eligible` option when you publish, which will restrict that publish to just those session ids for that user.

**Comment by drtzack** [comment]
I am really sorry. I recognized it just now and you replied :)
Thank you.

**Comment by drtzack** [comment]
What about getting ID of user who calls fetchUser function
	....
	$session->register('com.app.fetchUser', [$this, "fetchUser"]);
	...
	public function fetchUser($args, $kwArgs, $options){
		$userid = ....
		return User::find($userid)->toArray();
	}

**Comment by davidwdan** [comment]
When you register the call, use the option ``disclose_caller``, which will tell the router to include the caller information with the response.

```PHP
$session->register('com.app.fetch_user', [$this, "fetchUser"], ['disclose_caller' => true])
```

Then on your fetchUser method

```PHP
public function fetchUser($args, $kwArgs, $details){
    if (isset($details->caller){
        $callerSessionId = $details->caller; 
        return User::find($callerSessionId)->toArray();
    }
}

```

**Comment by cyprus1spirit** [comment]
Hi guys in the above example I can't get the $session variable to be global. Therefore in the following section the $sessions are always non inset. 

$session->subscribe('wamp.metaevent.session.on_leave', function($args) use ($sessions){
        //remove the session
        if (!isset($sessions[$args[0]->authid])){
            return;
        }

Any ideas?
