### ISSUE TITLE
Internal Client Auth Id

### ISSUE THREAD

**Issue by drtzack** [voryx/Thruway#78]
class InternalClient extends Module
	{
	  public function __construct($realm, LoopInterface $loop = null)
	  {
		parent::__construct($realm, $loop);
		$this->setAuthId('InternalClient');
	  }

I did this but in onJoin function authid returns anonymous

	public function onJoin($args, $kwArgs, $options){
		echo $args[0]['authid']."\n";
		$this->sessions[$args[0]['authid']][$args[0]['session']] = $args[0];
	}

If I change authId in Client, it's working.

    public function __construct($realm, LoopInterface $loop = null)
    {
        $this->checkPrecision();

        $this->realm                = $realm;
        $this->loop                 = $loop ? $loop : Factory::create();
        $this->transportProvider    = null;
        $this->roles                = [];
        $this->authMethods          = [];
        $this->manager              = new ManagerDummy();
        $this->session              = null;
        $this->clientAuthenticators = [];
        $this->authId               = "anonymous";

So how to change it?

**Comment by drtzack** [comment]
Sorry It was id of AuthenticationManager.
	$authMgr = new AuthenticationManager();
	$authMgr->setAuthId('AuthenticationManager');
but still I get anonymous

**Comment by mbonneau** [comment]
I was not able to reproduce this issue.

When I did try, I ran into a few internal clients that I needed to set the authid of to stop seeing some anonymous clients.

**Comment by drtzack** [comment]
You're right. Problem solved.


    $authorizationManager = new AuthorizationManager(config('socket.realm'));
    $authorizationManager -> setAuthId('AuthorizationManager');
    $rule = new stdClass();
    $rule->role = 'frontend';
    $rule->action = 'subscribe';
    $rule->uri = 'com.app.notification';
    $rule->allow = true;

    //$authorizationManager->flushAuthorizationRules(true);
    $authorizationManager->addAuthorizationRule([$rule]);
    $authorizationManager->setReady(true);

    $router->registerModules([
      $this->client,
      $authorizationManager,
    ]);

    $router->start();

also changed order of modules and not seeing it anymore.

Thank you.
