### ISSUE TITLE
[question] non event loop 

### ISSUE THREAD

**Issue by basz** [voryx/Thruway#80]
Hello, first off I'm new to PHP event loop and web sockets via thruway and crossbar.io. Looks like a great fit for my stack. Secondly, apologies if this is the wrong place or project to ask.

I got a php worker (http://github.com/juriansluiman/SlmQueue) and I wish to extend that (simple via it's own 'strategies' that hook into events) to publish WAMP messages while it is processing it's jobs.

However that project uses a '[do while $shouldExitWorkerLoop](https://github.com/juriansluiman/SlmQueue/blob/master/src/SlmQueue/Worker/AbstractWorker.php#L45)' loop. This seems incompatible with the reactor pattern ratchet and thruway use. I am able to connect, publish and then disconnect again to resume 'my' loop (I've got that working, see gist) but that seems a little, well, inefficient.

So, is there a (better) way to use Thruway in a long running script in such that it does not utilize the event loop? Can I manually 'clear' or 'flush' or 'progress' the event loop that is internally created?

I understand that would be problematic listening for incoming data, but since i only wish to publish I hoping something may be done here...

https://gist.github.com/basz/0b16dc3db157d3fd7afb

**Comment by mbonneau** [comment]
Hi @basz ,

I am not familiar with SlmQueue.

Unfortunately, Thruway is totally dependent on the event loop. You can, however, use HTTP calls to publish events to a WAMP server if you think this is an easier/cleaner solution. 

If you are using crossbar, you can use the [pusher service](http://crossbar.io/docs/HTTP-Pusher-Service/) or if you use the Thruway router, you could use our [WampPost](https://github.com/voryx/WampPost) client.

**Comment by basz** [comment]
Thank you @mbonneau I was afraid of that. 

But you provided a perfect solution, a pusher service...  amazing :-)
