### ISSUE TITLE
traitSetOptions() undefined

### ISSUE THREAD

**Issue by nahuelhds** [voryx/Thruway#81]
I'm trying to implement the client for this pattern.

When I do it without closing the connection, the script gets unfinished forever. Instead, I need to close the connection in order to receive the data I sent for my app.

When doing so, I got this error when trying to publish a message (maybe I'm doing it wrong, there is no many documentation about how to do the basics in this PHP implementation, so I'm doing a lot of manual test).

The error message is:

Fatal error: Call to undefined method Thruway\Message\PublishMessage::traitSetOptions() in {root}\vendor\voryx\thruway\src\Thruway\Message\PublishMessage.php on line 150

I'm using the example code for the Client:

    $onClose = function ($msg)
        {
            echo null;
        };

        Logger::set(new NullLogger);

        $connection = new Connection([
            "realm" => 'realm1',
            "onClose" => $onClose,
            "url" => 'ws://127.0.0.1:9090',
        ]);

        $connection->on('open', function (ClientSession $session) use ($connection)
        {
            // 2) publish an event
            $session->publish('com.myapp.notification', ['Hello PHP!!!'], [], ["acknowledge" => true])->done(function() use($connection){
                $connection->close();
            });
        });

        $connection->open();

For the WAMP server I'm using the vendor/voryx/thryway/Examples/SimpleWsServer.php code.

I'd lke to have some guidance. I need to close the connection after I publish the message, in order to send some json data to the app in order to continue the process.

Thanks in advance

**Comment by davidwdan** [comment]
@nahuelhds I tested your code with the latest version of Thruway, and it worked without any errors.  What are your versions of Thruway and PHP?

If you just need to publish, take a look at [WampPost](https://github.com/voryx/WampPost).  It allows you to publish to the WAMP router with regular http calls.

**Comment by nahuelhds** [comment]
PHP 5.4.7
Thruway 0.3.* (installed by Composer just yesterday).

The first time I publish it does it fine, the problem appears after three or four publishes.
I'm executing the script through AJAX. I need to close the connection in order to receive feedback. If I don't do it the script gets running forever.
If I close the session and the connection altogether the AJAX request dies, not returing the feedback. If I close only the connection, as I say, it works the first time or the second, but it starts giving me that error after those tries.

On the other hand, is the way I'm closing the connection ok? Just to confirm.

I'll try some different ways today, if I get it working I'll let you know.

Thanks for your fast response

**Comment by davidwdan** [comment]
Yeah, you shouldn't have any problems closing the connection that way. 

I'd still recommend using WampPost.  I think that it will work much better in your scenario.

**Comment by nahuelhds** [comment]
I've finally implemented WampPost with Wamp Server with internal Client (just in the way your example is set in that project). Now, I send curl posts with Guzzle to the WampPost Client and it works a lot faster than the initial way and with no issues.

Now, I'd like to give feedback to the curl request through the WampPost Client, but that's another issue. If I need anything regarding to this, I'll let you know in the WampPost project.

Thanks for your help
