### ISSUE TITLE
Subscriber not receiving any data on publish

### ISSUE THREAD

**Issue by pdesmarais** [voryx/Thruway#82]
Hi! I'm using the Thruway and the ThruwayBundle in a Symfony project.

My router is setup correctly (or so I think) since I'm able to subscribe and publish to topics using autobahn in my browser using my router and I do receive the updates when a new message is published.

The problem I have is that I need a PHP based client that subscribes to the chat topics to save some messages (when message object matches certain criteria) to the database.

My setup currently consists of a copy of the `ThruwayClientCommand` which instead of creating a new `Thruway\Peer\Client`, creates a new `SocketClient` (which is a class I created that extends `Thruway\Peer\Client`). This `SocketClient` class only has a `onSessionStart` method in which I subscribe to the topics using the prefix matcher to match all chat topics.

```php
public function onSessionStart($session, $transport)
{
    $onevent = function ($args) {
        $this->receiveMessage($args);
    };

    $session->subscribe('com.myproject.chat', $onevent, array('match' => 'prefix'));
}

public function receiveMessage($args)
{
    var_dump('received a message');
    var_dump($args);
}
```

Whenever I publish a message to a matching topic from my JS client, this is the output I get on the console on my router...

```bash
2015-02-17T08:50:26.3977790 debug      [Thruway\Transport\RatchetTransportProvider 1902] onMessage: ([16,7523572423589888,{},"com.myproject.chat.client.2ed47082051d301825fd8eb94078272d",[],{"message":{"from_client":true,"message":"44444","sent_at":"2015-02-17T13:50:26.396Z"}}])
2015-02-17T08:50:26.3980280 debug      [Thruway\Role\Broker 1902] Broker onMessage for {"type":"ratchet","transportAddress":"127.0.0.1"}: [16,7523572423589888,{},"com.myproject.chat.client.2ed47082051d301825fd8eb94078272d",[],{"message":{"from_client":true,"message":"44444","sent_at":"2015-02-17T13:50:26.396Z"}}]
2015-02-17T08:50:26.3989360 debug      [MyProject\SystemBundle\Peer\SocketClient 1902] Client onMessage: [Thruway\Message\EventMessage]
string(18) "received a message"
array(0) {
}
```

The `$args` variable is always empty... Am I doing something wrong?

Thanks!

**Comment by davidwdan** [comment]
@pdesmarais It looks like only ArgsKW has any values.  Can you show the code you use to publish the message?

**Comment by pdesmarais** [comment]
Aw man! You are so right!!

This is what I use to publish :

```javascript
session.publish('com.myproject.chat.client.' + clientGuid, [], {"message":{"from_client": true, "message": message, "sent_at": sentAt.toISOString()}});
```

Thanks @davidwdan you make my day! :) :+1:

**Comment by davidwdan** [comment]
It's still pretty early, better things might still happen today :smile:

**Comment by pdesmarais** [comment]
Hahaha! Thanks! Awesome work on Thruway btw. :)
