### ISSUE TITLE
Unable to complete SSL/TLS handshake

### ISSUE THREAD

**Issue by mbonneau** [voryx/Thruway#83]
When trying to have client connect to wss://dns.domain.name/ I get an error from PawlTransportProvider:

Could not connect: Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): Peer certificate CN=`dns.domain.name' did not match expected CN=`IP Address'

dig @8.8.8.8 dns.domain.name returns a valid A record corresponding to IP Address.

("dns,domain.name" and "IP Address" were substituted from the actual values)

**Comment by cboden** [comment]
What version of PHP are you using? This may be related to reactphp/socket-client#23

I'm hoping to get a new release of SocketClient out next week.

**Comment by mbonneau** [comment]
Hi @cboden,

5.6.5

Thanks for answering so quickly. Adding the peer_name fixed this issue for me.

**Comment by ihabunek** [comment]
Having the same issue connection to Slack.

```
[Thruway\Transport\PawlTransportProvider 4156] 
Could not connect: Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): Peer certificate CN=`*.slack-msgs.com' did not match expected CN=`54.162.147.208'
```
PHP 5.6.0, using FQDN, not IP address.

**Comment by ihabunek** [comment]
Sorry, didn't read your comment fully before posting. I can confirm this is solved by adding `peer_name` to the connection context as noted on issue you linked. :+1:

**Comment by cboden** [comment]
[SocketClient v0.4.3](https://github.com/reactphp/socket-client/releases/tag/v0.4.3) has been tagged. Upgrading should fix this issue.

**Comment by mbonneau** [comment]
That's great. Thank you.
