### ISSUE TITLE
Automated crossbar test is failing

### ISSUE THREAD

**Issue by mbonneau** [voryx/Thruway#85]
Travis is failing.

**Comment by davidwdan** [comment]
I found a request path issue with the version of guzzle that ratchets requires (which is outdated).  Updating to guzzle/guzzle fixes that issue.

There's a secondary issue with crossbar throwing an error when we announce the `subscriber_metaevents` feature from the subscriber:

```
WAMP Internal Error (__init__() got an unexpected keyword argument 'subscriber_metaevents')

```
Looking at the spec, it looks like we're suppose to be announcing that meta event.
https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#subscriber-meta-events

I'll dig into it a bit more and maybe open an issue with crossbar.

**Comment by davidwdan** [comment]
Resolved with https://github.com/voryx/Thruway/commit/912671b49db5e2034e1ebb29cae6e26ea425619a
