### ISSUE TITLE
How to close a connection?

### ISSUE THREAD

**Issue by dethell** [voryx/Thruway#88]
I'm using Thruway in a Laravel controller that publishes to a stream based on ajax calls from an admin dashboard. I can open the connection just fine, but I'm unable to close the connection so the http request to Laravel just waits and hangs. Here's the code I'm trying:

            $connection = new Connection([
                "realm" => 'com.sessionradar.wamp.realm1',
                "onClose" => $onClose,
                "url" => 'ws://127.0.0.1:9090'
            ]);
            
            $connection->on('open', function (ClientSession $session)
            {
                
                // publish this notification
                $session->publish('com.sessionradar.notifications', [
                    "This is a test"
                ], [], [
                    "acknowledge" => true
                ])
                    ->then(function ()
                {
                    // echo "Publish Acknowledged!\n";
                    $connection->close();
                }, function ($error)
                {
                    // publish failed
                    // echo "Publish Error {$error}\n";
                    $connection->close();
                });
            });
            
            $connection->open();

Why is it that the connection->close call doesn't stop the connection and allow the process to finish?

**Comment by davidwdan** [comment]
@dethell It looks like you're missing a couple of use statements.  Your code should look more like this:

```PHP

connection->on('open', function (\Thruway\ClientSession $session) use ($connection) {

    //publish an event
    $session->publish('com.example.hello', ['Hello, world from PHP!!!'], [], ["acknowledge" => true])->then(
        function () use ($connection) {
            $connection->close(); //You must close the connection or this will hang
            echo "Publish Acknowledged!\n";
        },
        function ($error) {
            // publish failed
            echo "Publish Error {$error}\n";
        }
    );
  });

 $connection->open();

```

**Comment by dethell** [comment]
Wow, that was pretty basic. Thanks!
