### ISSUE TITLE
 List of connected users with roles 

### ISSUE THREAD

**Issue by mainman** [voryx/Thruway#90]
Hello,

In my app (chat) there are 2 roles user & power user.
Only the power user are able to see the connected users (role user).
The power user doesn't see his name in the list.
This list is just sent by a Pub in onSessionJoin / onSessionLeave (works well)

My app is like that :

- a PHP router with an AuthentificationProvider (with JWT) as internal client
- a PHP client who store the list of the connected users. (meta event onSessionJoin / onSessionLeave )

But in the $args (first parameter) of onSessionJoin, the key values of authprovider, authrole are empty...
However, in the JwtAuthentificationProvider, the processAuthenticate method returns the good values. (good authrole)

Please what I must do to get the good authrole in the onSessionJoin ?
Thanks

**Comment by mbonneau** [comment]
I just committed a fix for that in in 0.3-dev and 0.4-dev branches.

**Comment by mbonneau** [comment]
Hi @mainman ,

Have you had a chance to test the latest commit?

**Comment by mainman** [comment]
Hi Matt,

Just tested. But it is totally broke... Here is what I've got in the onSessionJoin first argument $args :
```php
array (
  0 => 
  stdClass::__set_state(array(
     'realm' => 'camhot',
     'authprovider' => NULL,
     'authid' => 'authenticated_user',
     'authrole' => 'authenticated_user',
     'authroles' => 
    array (
      0 => 'authenticated_user',
    ),
     'authmethod' => 'jwt',
     'session' => 33556481,
     'role_features' => 
    stdClass::__set_state(array(
       'caller' => 
      stdClass::__set_state(array(
         'features' => 
        stdClass::__set_state(array(
           'caller_identification' => true,
           'progressive_call_results' => true,
        )),
      )),
       'callee' => 
      stdClass::__set_state(array(
         'features' => 
        stdClass::__set_state(array(
           'progressive_call_results' => true,
        )),
      )),
       'publisher' => 
      stdClass::__set_state(array(
         'features' => 
        stdClass::__set_state(array(
           'subscriber_blackwhite_listing' => true,
           'publisher_exclusion' => true,
           'publisher_identification' => true,
        )),
      )),
       'subscriber' => 
      stdClass::__set_state(array(
         'features' => 
        stdClass::__set_state(array(
           'publisher_identification' => true,
        )),
      )),
    )),
  )),
)
```
The authid is not the real one, and the authrole I returned in the JwtAuthenticationProvider::processAuthenticate is not there.

I return :

```php
$authDetails = [
	"authmethod"   => "jwt",
	"authrole"     => $authRole,
	"authid"       => $authId,
	"authprovider" => "jwt"
];

return ["SUCCESS", $authDetails];
```
Hope you will find the issue.
Thanks !

**Comment by mbonneau** [comment]
Hi @mainman ,

What version are you requiring in composer.json?

**Comment by mainman** [comment]
dev-master

**Comment by mbonneau** [comment]
I do see this issue you are having now. One of the later commits caused the new behavior you are seeing. I am working on getting that fixed back up now.

**Comment by mainman** [comment]
Thanks Matt

**Comment by mainman** [comment]
@mbonneau If I have question, can I post them here ?
I must ban some client of my chat app, and I don't know how to force the connection to close from outside. Thanks

**Comment by mbonneau** [comment]
@mainman ,

I have pushed changes to both dev-master and 0.3 branches that will address the issues.

Please note that Thruway does not pass the authprovider through.

As far as general questions and discussion, the group (https://groups.google.com/forum/#!forum/thruway) would probably be a better place for that so that the watchers here don't see a bunch of extra traffic for discussions. We will try to be better about responding on the group.

Let me know if you are still having issues.

**Comment by mainman** [comment]
Hi Matt,
Thanks for your quick response. All is fine now, and I have my roles !
