### ISSUE TITLE
UTF-8 problem with (french) accented characters

### ISSUE THREAD

**Issue by mainman** [voryx/Thruway#91]
Hi
Just found that when a Autobahn.js client (HTML page charset is UTF-8) make a RPC call on an PHP client procedure, the accented characters are "encoded" like this :

Autobahn client send : é
PHP Client receive : Ã©

A Deserialization exception occurs in RatchetTransportProvider and I must do an utf8_decode on the string.
The problem is in Thruway\Serializer\JsonSerializer::deserialize line 37

Perhaps it's normal, but it seems weird.

Thanks

**Comment by mbonneau** [comment]
I am not an expert on UTF-8.

I did give your example character a try and it appears to work fine in my setup. The Ã© maps to ISO-8859 characters for the UTF-8 encoded é. (In my observation, you could see Ã© being sent in the network traffic in Chrome and then Thruway sending it back as \u00e9). Both, according to my limited research, are valid encodings in JSON (I am assuming the network tab in Chrome just doesn't display UTF-8). I do not experience the serialization errors you are experiencing.

A couple of ideas:

- Make sure your character set in PHP is set to UTF-8 (you can check on your unix-based machine with ```php -i | grep default_charset```
- I am not sure where you are seeing Ã© - if it is in a terminal, check to make sure the terminal supports UTF-8

Please let me know if this helps.

**Comment by mainman** [comment]
Hi
My blacklist class was the problem. mb_strtolower needs the the 2nd arg (encoding) or the string is breaked.
I am really sorry...
