### ISSUE TITLE
where is the Thruway document?

### ISSUE THREAD

**Issue by argb** [voryx/Thruway#92]
Is there any documents like Rachet?
Rachet don't support wamp v2,so I found thruway,but there is no document?!

**Comment by mbonneau** [comment]
There is not a lot of documentation right now on Thruway.

Until we have a chance to improve this, please see https://github.com/voryx/Thruway/issues/84#issuecomment-76882124 for a simple explanation.

You can also check out the Examples directory. If you get stuck, feel free to ask for help on the group at https://groups.google.com/forum/#!forum/thruway

**Comment by argb** [comment]
@mbonneau Thank you,I think Document is very necessary if you hope Thruway is widespread used.

**Comment by argb** [comment]
@mbonneau I found that Thruway is just a WAMP implementation ,not a websocket library like Ratchet,So Ratchet can do more things than Thruway,for example,Ratchet have $conn->send('xxx'),but Thruway can not do this,can not us websocket method directly.The only problem of Ratchet is don't support WAMP v2, if Ratchet combine thruway into ,that would be very good.
