### ISSUE TITLE
Problem with Authorization

### ISSUE THREAD

**Issue by adamlc** [voryx/Thruway#93]
Hey guys! Let me first say Thruway is great, very well written, despite little documentation I've got my head round it pretty fast :)

I am having issues though with Authorization. I followed the guide for the JWT auth provider and I've since tried to add the AuthorizationManager. For some reason though, from what I can tell onAuthenticationMessage is never called, even in AllPermissiveAuthorizationManager. Is there anything I'm doing wrong?

My code is in Laravel and in the IOC container, I can make it more generic for testing if required.

```php
<?php namespace Jumplead\WAMP\Support\Provider\Thruway;

use Thruway\Peer\Router;
use Illuminate\Support\ServiceProvider;

class RouterServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->singleton('Thruway\Peer\Router', function($app)
        {
            $loop = $app->make('react-loop');

            $router = new Router($loop);

            //Authentication
            $authManager = $app->make('Thruway\Authentication\AuthenticationManagerInterface');
            $router->setAuthenticationManager($authManager);
            $router->addInternalClient($authManager);

            $router->addInternalClient($app->make('Jumplead\WAMP\Authentication\JwtAuthenticationProvider'));

            //Authorization
            $router->setAuthorizationManager($app->make('Thruway\Authentication\AuthorizationManagerInterface'));

            //Transport
            $router->addTransportProvider($app->make('Thruway\Transport\RouterTransportProviderInterface'));

            return $router;
        });
    }
}
```

Just in case you're wondering, the interfaces are bound to the relevant classes in the IOC container:

Thruway\Authentication\AuthenticationManagerInterface > Thruway\Authentication\AuthenticationManager

Thruway\Authentication\AuthorizationManagerInterface > Thruway\Authentication\AuthorizationManager

Thruway\Transport\RouterTransportProviderInterface > Thruway\Transport\RatchetTransportProvider

Thanks in advance :)

**Comment by davidwdan** [comment]
What version of Thruway are you using?

You should be adding `AuthenticationManager` and `AuthorizationManager` to your router as modules instead of internal clients:

```PHP
public function register()
    {
        $this->app->singleton('Thruway\Peer\Router', function($app)
        {
            $loop = $app->make('react-loop');

            $router = new Router($loop);
            
            $router->registerModules([
                   // Authentication
                   new \Thruway\Authentication\AuthenticationManager(),
                   // Authorization for a specific realm 'realm1'
                   new \Thruway\Authentication\AuthorizationManager('realm1'),
            ]);

            $router->addInternalClient($app->make('Jumplead\WAMP\Authentication\JwtAuthenticationProvider'));

            return $router;
        });
    }

```

**Comment by adamlc** [comment]
@davidwdan thanks for getting back to me. I've just tried what you've suggested and unfortunately it still doesn't seem to be working :(

I'm using Thruway 0.3.5

I've removed everything out of the IOC container and it behaves exactly the same. So I'm pretty convinced thats not the issue.

Heres my logs from Thruway and Autobahn

```
[2015-04-30 07:09:16] local.DEBUG: [Thruway\Transport\RatchetTransportProvider 3499] onMessage: ([32,5315717121441792,{},"com.jumplead.client.1.activity"]) [] []
[2015-04-30 07:09:16] local.DEBUG: [Thruway\Subscription\SubscriptionGroup 3499] Added subscription to "exact":"com.jumplead.client.1.activity" [] []
```

```
AutobahnJS debug enabled
trying to create WAMP transport of type: websocket
using WAMP transport type: websocket
WebSocket transport send [1,"jumplead",{"roles":{"caller":{"features":{"caller_identification":true,"progressive_call_results":true}},"callee":{"features":{"progressive_call_results":true}},"publisher":{"features":{"subscriber_blackwhite_listing":true,"publisher_exclusion":true,"publisher_identification":true}},"subscriber":{"features":{"publisher_identification":true}}},"authmethods":["jwt","simplysimple"]}]
WebSocket transport receive [4,"jwt",{"challenge":{},"challenge_method":"jwt"}]
WebSocket transport send [5,"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRfaWQiOjEsInVzZXJfaWQiOjEsInRpbWV6b25lIjoiRXVyb3BlXC9Mb25kb24iLCJleHAiOjE0MzA1NTAxODJ9.to1YgXCmyC01X3-edaGzUHExF3K6cGPfOO9oF64trEw",{}]
WebSocket transport receive [2,265488866910900,{"authid":{"client_id":1,"user_id":1,"timezone":"Europe\/London","exp":1430550182},"authroles":["jumplead_user_1","authenticated_user"],"authrole":"jumplead_user_1","roles":{"broker":{"features":{"subscriber_blackwhite_listing":true,"publisher_exclusion":true,"subscriber_metaevents":true}},"dealer":{"features":{"caller_identification":true,"progressive_call_results":true}}}}]
WebSocket transport send [32,5315717121441792,{},"com.jumplead.client.1.activity"]
Successfully made the socket connection as 265488866910900.
WebSocket transport receive [33,5315717121441792,8356589210486627]
Connected to activity channel
```

The user at the moment doesn't have anything set in the AuthorizationManager. I've even tried setting allow to false in the addAuthorizationRule and it doesn't seem to make any difference :(

As I mentioned previously, I've tried adding debug code in AuthorizationManager and AllPermissiveAuthorizationManager and it never seems to be called.

Thanks for your help so far. If you need any more code let me know :)

**Comment by davidwdan** [comment]
Just quickly scanning your log, I do see one issue with this message:

```
WebSocket transport receive [2,265488866910900,{"authid":{"client_id":1,"user_id":1,"timezone":"Europe\/London","exp":1430550182},"authroles":["jumplead_user_1","authenticated_user"],"authrole":"jumplead_user_1","roles":{"broker":{"features":{"subscriber_blackwhite_listing":true,"publisher_exclusion":true,"subscriber_metaevents":true}},"dealer":{"features":{"caller_identification":true,"progressive_call_results":true}}}}]
```
The `authid` needs to be a string (in your case a 1), not an object.  It looks like you might be setting the entire deserialized JWT token as the `authid`.  

It's probably unrelated to the authorization issues, but it'll probably cause problems elsewhere.

That also means that `onAuthenticationMessage` is being called, because the router is responding with the authid that you set.


As for the Authorization, can you try this code?  Subscribing to `com.jumplead.client.1.activity` should fail.

```PHP

public function register()
{
    $this->app->singleton(
      'Thruway\Peer\Router',
      function ($app) {
          $loop   = $app->make('react-loop');
          $router = new Router($loop);

          $authorizationManager = new AuthorizationManager('jumplead');

          $rule         = new stdClass();
          $rule->role   = 'jumplead_user_1';
          $rule->action = 'subscribe';
          $rule->uri    = 'com.jumplead.client.1.activity';
          $rule->allow  = false;

          $authorizationManager->addAuthorizationRule([$rule]);
          $authorizationManager->setReady(true);

          $router->registerModules([
                // Authentication
              new \Thruway\Authentication\AuthenticationManager(),
              $authorizationManager
          ]);

          $router->addInternalClient(
            $app->make('Jumplead\WAMP\Authentication\JwtAuthenticationProvider')
          );

          return $router;
      }
    );
}

```

**Comment by adamlc** [comment]
@davidwdan the authid actually is a deserialized JWT token as you said, I needed to pass more variables around so I could do stuff with them later and it seemed to work OK. I have tried just setting it to a string too. I just used a small wrapper:

```php
<?php namespace Jumplead\WAMP\Authentication;

/**
 * Placeholder for JWT stdClass, so we can have a toString function.
 */
class AuthCredentials implements \JsonSerializable
{
    private $token;

    public function __construct($token)
    {
        $this->token = $token;
    }

    public function __set($name, $value)
    {
        $this->token->{$name} = $value;
    }

    public function __get($name)
    {
        return $this->token->{$name};
    }

    public function __isset($name)
    {
        return isset($this->token->{$name});
    }

    public function __unset($name)
    {
        unset($this->token->{$name});
    }

    public function __toString()
    {
        return json_encode($this->token);
    }

    public function jsonSerialize()
    {
        return $this->token;
    }
}
```
(probably not ideal and could be done a better way)

That aside it still didn't seem to work unfortunately. I'm honestly baffled, as I'm sure I have seen at working at some point when I showed one of my colleagues. 

I'll have another dry run through the code and see if I can figure out where it the call goes :)

**Comment by adamlc** [comment]
After delving into the code more it looks like Authorization was broken in 00488a3ac59128bd373a980d00412d9513ccdaf3, processAuthenticated is never called in Thruway\Realm as it looks like you're updating things to use the Event Dispatcher. 

So it looks like currently this isn't supported until its been reimplemented using the dispatcher! I might have a stab myself and submit a PR

**Comment by davidwdan** [comment]
I'm very sorry, I accidentally tagged the master branch with the last release.  We'll tag a 3.6 release on the correct branch and everything should work.

**Comment by mbonneau** [comment]
The event dispatcher is part of the 0.4/dev-master branch which has not had the authorization stuff ported over yet. If you switch to 0.3.6 or 0.3-dev, the authorization stuff should work for you.

Here is a working example on the 0.3 branch:

```
<?php

require_once __DIR__ . '/vendor/autoload.php';

class JwtAuthenticationProvider extends Thruway\Authentication\AbstractAuthProviderClient {
    private $jwtKey;

    public function __construct(Array $authRealms, $jwtKey) {
        $this->jwtKey = $jwtKey;
        parent::__construct($authRealms);
    }

    public function getMethodName() {
        return 'jwt';
    }

    public function processAuthenticate($signature, $extra = null)
    {
        $jwt = JWT::decode($signature, $this->jwtKey, ['HS256']);

        if (isset($jwt->authid)) {
            return ["SUCCESS", [
                "authid" => $jwt->authid,
                "authrole" => "niceguy"
            ]];
        } else {
            return ["FAILURE"];
        }
    }
}

$loop = \React\EventLoop\Factory::create();

$router = new \Thruway\Peer\Router($loop);

$router->registerModule(new \Thruway\Authentication\AuthenticationManager());

$router->addInternalClient(new JwtAuthenticationProvider(['realm1'], 'example_key'));

$authorizationManager = new \Thruway\Authentication\AuthorizationManager('realm1');

// set the default rule to allow, otherwise everything will be killed
$authorizationManager->flushAuthorizationRules(true);

$rule         = new stdClass();
$rule->role   = 'niceguy';
$rule->action = 'call';
$rule->uri    = 'some_rpc';
$rule->allow  = false;

$authorizationManager->addAuthorizationRule([$rule]);
$authorizationManager->setReady(true);

$router->registerModule($authorizationManager);

$router->addTransportProvider(new \Thruway\Transport\RatchetTransportProvider('127.0.0.1', 8765));

$router->start();
```

Here is a plunk to test it with: http://plnkr.co/edit/uZgIRjRasWxTtwS6dzw6?p=preview

**Comment by adamlc** [comment]
Fantastic its working now :dancer: 

Thanks for sorting it out guys! Mistakes happen :smile:

**Comment by mbonneau** [comment]
In the real world, you should use a deny by default strategy, or at the very least make sure you protect the RPCs:

add_authorization_rule
remove_authorization_rule
flush_authorization_rules
get_authorization_rules
test_authorization

Also, on subscriptions, if you don't deny and then allow on a more narrow uri, the clients could subscribe to a prefix matching rule that gives them everything (unless it is a whitelisted/blacklisted message).
